version: '3'

vars:
  ORCHESTRA_DIR: $HOME/ghq/github.com/yoshihiko555/ai-orchestra
  DOTFILES_CLAUDE: $HOME/ghq/github.com/yoshihiko555/dotfiles/claude/.claude
  DOTFILES_CLAUDE_ONLY: $HOME/ghq/github.com/yoshihiko555/dotfiles/shared/skills/claude-only
  DOTFILES_ROOT: $HOME/ghq/github.com/yoshihiko555/dotfiles
  HOME_CLAUDE: $HOME/.claude

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  sync:
    desc: Sync all orchestra files to dotfiles and deploy to ~/.claude
    cmds:
      - task: sync:agents
      - task: sync:hooks
      - task: sync:rules
      - task: sync:skills
      - task: sync:commands
      - task: sync:templates
      - task: deploy

  sync:agents:
    desc: Sync agent files to dotfiles
    dir: "{{.DOTFILES_CLAUDE}}/agents"
    cmds:
      - |
        echo "Syncing agents..."
        for f in {{.ORCHESTRA_DIR}}/agents/*.md; do
          [ -e "$f" ] || continue
          name=$(basename "$f")
          if [ ! -L "$name" ]; then
            ln -sf "$f" "$name"
            echo "  + $name"
          fi
        done
        echo "Done"

  sync:hooks:
    desc: Sync hook files to dotfiles
    dir: "{{.DOTFILES_CLAUDE}}/hooks"
    cmds:
      - |
        echo "Syncing hooks..."
        for f in {{.ORCHESTRA_DIR}}/hooks/*.py; do
          [ -e "$f" ] || continue
          name=$(basename "$f")
          if [ ! -L "$name" ]; then
            ln -sf "$f" "$name"
            echo "  + $name"
          fi
        done
        echo "Done"

  sync:rules:
    desc: Sync rule files to dotfiles
    dir: "{{.DOTFILES_CLAUDE}}/rules"
    cmds:
      - |
        echo "Syncing rules..."
        for f in {{.ORCHESTRA_DIR}}/rules/*.md; do
          [ -e "$f" ] || continue
          name=$(basename "$f")
          if [ ! -L "$name" ]; then
            ln -sf "$f" "$name"
            echo "  + $name"
          fi
        done
        echo "Done"

  sync:skills:
    desc: Sync skill directories to dotfiles
    cmds:
      - |
        echo "Syncing skills to claude-only..."
        cd {{.DOTFILES_CLAUDE_ONLY}}
        for d in {{.ORCHESTRA_DIR}}/skills/*/; do
          [ -d "$d" ] || continue
          name=$(basename "$d")
          if [ ! -L "$name" ]; then
            ln -sf "$d" "$name"
            echo "  + $name (claude-only)"
          fi
        done
      - |
        echo "Syncing skills to .claude/skills..."
        cd {{.DOTFILES_CLAUDE}}/skills
        for d in {{.ORCHESTRA_DIR}}/skills/*/; do
          [ -d "$d" ] || continue
          name=$(basename "$d")
          if [ ! -L "$name" ]; then
            ln -sf ../../../shared/skills/claude-only/$name $name
            echo "  + $name (.claude/skills)"
          fi
        done
        echo "Done"

  sync:commands:
    desc: Sync command files to dotfiles
    cmds:
      - |
        echo "Syncing commands..."
        mkdir -p {{.DOTFILES_CLAUDE}}/commands
        # Remove old non-symlink files first
        find "{{.DOTFILES_CLAUDE}}/commands" -maxdepth 1 -type f -delete 2>/dev/null || true
        # Create symlinks
        for f in {{.ORCHESTRA_DIR}}/commands/*.md; do
          [ -e "$f" ] || continue
          name=$(basename "$f")
          if [ ! -L "{{.DOTFILES_CLAUDE}}/commands/$name" ]; then
            ln -sf "$f" "{{.DOTFILES_CLAUDE}}/commands/$name"
            echo "  + $name"
          fi
        done
        echo "Done"

  sync:templates:
    desc: Sync template directories to dotfiles
    cmds:
      - |
        echo "Syncing templates..."
        mkdir -p {{.DOTFILES_CLAUDE}}/templates

        # project templates
        if [ ! -L "{{.DOTFILES_CLAUDE}}/templates/project" ]; then
          rm -rf "{{.DOTFILES_CLAUDE}}/templates/project" 2>/dev/null || true
          ln -sf "{{.ORCHESTRA_DIR}}/templates/project" "{{.DOTFILES_CLAUDE}}/templates/project"
          echo "  + templates/project"
        fi

        # codex templates
        if [ ! -L "{{.DOTFILES_CLAUDE}}/templates/codex" ]; then
          rm -rf "{{.DOTFILES_CLAUDE}}/templates/codex" 2>/dev/null || true
          ln -sf "{{.ORCHESTRA_DIR}}/templates/codex" "{{.DOTFILES_CLAUDE}}/templates/codex"
          echo "  + templates/codex"
        fi

        # gemini templates
        if [ ! -L "{{.DOTFILES_CLAUDE}}/templates/gemini" ]; then
          rm -rf "{{.DOTFILES_CLAUDE}}/templates/gemini" 2>/dev/null || true
          ln -sf "{{.ORCHESTRA_DIR}}/templates/gemini" "{{.DOTFILES_CLAUDE}}/templates/gemini"
          echo "  + templates/gemini"
        fi

        # project-settings.json
        if [ ! -L "{{.DOTFILES_CLAUDE}}/templates/project-settings.json" ]; then
          rm -f "{{.DOTFILES_CLAUDE}}/templates/project-settings.json" 2>/dev/null || true
          ln -sf "{{.ORCHESTRA_DIR}}/templates/project-settings.json" "{{.DOTFILES_CLAUDE}}/templates/project-settings.json"
          echo "  + templates/project-settings.json"
        fi

        echo "Done"

  deploy:
    desc: Deploy dotfiles to ~/.claude (create directory symlinks)
    cmds:
      - |
        echo "Deploying to ~/.claude..."
        mkdir -p {{.HOME_CLAUDE}}

        # agents
        if [ ! -L "{{.HOME_CLAUDE}}/agents" ]; then
          rm -rf "{{.HOME_CLAUDE}}/agents" 2>/dev/null || true
          ln -sf "{{.DOTFILES_CLAUDE}}/agents" "{{.HOME_CLAUDE}}/agents"
          echo "  + agents"
        fi

        # hooks
        if [ ! -L "{{.HOME_CLAUDE}}/hooks" ]; then
          rm -rf "{{.HOME_CLAUDE}}/hooks" 2>/dev/null || true
          ln -sf "{{.DOTFILES_CLAUDE}}/hooks" "{{.HOME_CLAUDE}}/hooks"
          echo "  + hooks"
        fi

        # rules
        if [ ! -L "{{.HOME_CLAUDE}}/rules" ]; then
          rm -rf "{{.HOME_CLAUDE}}/rules" 2>/dev/null || true
          ln -sf "{{.DOTFILES_CLAUDE}}/rules" "{{.HOME_CLAUDE}}/rules"
          echo "  + rules"
        fi

        # skills
        if [ ! -L "{{.HOME_CLAUDE}}/skills" ]; then
          rm -rf "{{.HOME_CLAUDE}}/skills" 2>/dev/null || true
          ln -sf "{{.DOTFILES_CLAUDE}}/skills" "{{.HOME_CLAUDE}}/skills"
          echo "  + skills"
        fi

        # commands (if exists in dotfiles)
        if [ -d "{{.DOTFILES_CLAUDE}}/commands" ] && [ ! -L "{{.HOME_CLAUDE}}/commands" ]; then
          rm -rf "{{.HOME_CLAUDE}}/commands" 2>/dev/null || true
          ln -sf "{{.DOTFILES_CLAUDE}}/commands" "{{.HOME_CLAUDE}}/commands"
          echo "  + commands"
        fi

        # templates
        if [ ! -L "{{.HOME_CLAUDE}}/templates" ]; then
          rm -rf "{{.HOME_CLAUDE}}/templates" 2>/dev/null || true
          ln -sf "{{.DOTFILES_CLAUDE}}/templates" "{{.HOME_CLAUDE}}/templates"
          echo "  + templates"
        fi

        echo "Done"

  stow:
    desc: "[Deprecated] Use 'deploy' instead. Run stow to deploy dotfiles"
    dir: "{{.DOTFILES_ROOT}}"
    cmds:
      - stow -R claude
      - echo "Stow complete"

  list:agents:
    desc: List all agents
    cmds:
      - ls -1 {{.ORCHESTRA_DIR}}/agents/*.md | xargs -n1 basename | sed 's/.md$//'

  list:hooks:
    desc: List all hooks
    cmds:
      - ls -1 {{.ORCHESTRA_DIR}}/hooks/*.py 2>/dev/null | xargs -n1 basename || echo "No hooks"

  list:skills:
    desc: List all skills
    cmds:
      - ls -1 {{.ORCHESTRA_DIR}}/skills/ 2>/dev/null || echo "No skills"

  add:agent:
    desc: "Create a new agent from template (usage: task add:agent -- agent-name)"
    cmds:
      - cp {{.ORCHESTRA_DIR}}/templates/agent-template.md {{.ORCHESTRA_DIR}}/agents/{{.CLI_ARGS}}.md
      - echo "Created {{.ORCHESTRA_DIR}}/agents/{{.CLI_ARGS}}.md"
      - echo "Edit the file, then run 'task sync'"

  add:skill:
    desc: "Create a new skill from template (usage: task add:skill -- skill-name)"
    cmds:
      - mkdir -p {{.ORCHESTRA_DIR}}/skills/{{.CLI_ARGS}}
      - cp {{.ORCHESTRA_DIR}}/templates/skill-template.md {{.ORCHESTRA_DIR}}/skills/{{.CLI_ARGS}}/SKILL.md
      - echo "Created {{.ORCHESTRA_DIR}}/skills/{{.CLI_ARGS}}/SKILL.md"
      - echo "Edit the file, then run 'task sync'"

  init:project:
    desc: "[Deprecated] Use '/init-orchestra' skill instead. Enable orchestra in a project"
    cmds:
      - |
        echo "⚠️  This task is deprecated."
        echo "Please use '/init-orchestra' skill in Claude Code instead."
        echo ""
        echo "The '/init-orchestra' skill provides:"
        echo "  - .claude/settings.json with all hooks"
        echo "  - CLAUDE.md template (if not exists)"
        echo "  - .claude/docs/ structure"
        echo "  - .codex/ configuration"
        echo "  - .gemini/ configuration"

  clean:
    desc: Remove broken symlinks from dotfiles and ~/.claude
    cmds:
      - |
        echo "Cleaning broken symlinks..."

        # Clean ~/.claude broken symlinks
        for dir in agents hooks rules skills commands templates; do
          link="{{.HOME_CLAUDE}}/$dir"
          if [ -L "$link" ] && [ ! -e "$link" ]; then
            rm -f "$link"
            echo "  - ~/.claude/$dir (broken)"
          fi
        done

        # Clean dotfiles broken symlinks
        find {{.DOTFILES_CLAUDE}}/agents -type l ! -exec test -e {} \; -delete 2>/dev/null || true
        find {{.DOTFILES_CLAUDE}}/hooks -type l ! -exec test -e {} \; -delete 2>/dev/null || true
        find {{.DOTFILES_CLAUDE}}/rules -type l ! -exec test -e {} \; -delete 2>/dev/null || true
        find {{.DOTFILES_CLAUDE_ONLY}} -maxdepth 1 -type l ! -exec test -e {} \; -delete 2>/dev/null || true
        find {{.DOTFILES_CLAUDE}}/skills -maxdepth 1 -type l ! -exec test -e {} \; -delete 2>/dev/null || true
        echo "Done"

  clean:all:
    desc: Remove all orchestra symlinks from dotfiles and ~/.claude (for restore)
    cmds:
      - |
        echo "Removing all orchestra symlinks..."

        # Remove ~/.claude directory symlinks
        echo "Cleaning ~/.claude symlinks..."
        for dir in agents hooks rules skills commands templates; do
          if [ -L "{{.HOME_CLAUDE}}/$dir" ]; then
            rm -f "{{.HOME_CLAUDE}}/$dir"
            echo "  - ~/.claude/$dir"
          fi
        done

        # Remove dotfiles symlinks (use find to catch all symlinks)
        echo "Cleaning dotfiles symlinks..."
        # agents - remove all symlinks
        find "{{.DOTFILES_CLAUDE}}/agents" -maxdepth 1 -type l -delete 2>/dev/null || true
        echo "  - dotfiles agents"
        # hooks - remove all symlinks
        find "{{.DOTFILES_CLAUDE}}/hooks" -maxdepth 1 -type l -delete 2>/dev/null || true
        echo "  - dotfiles hooks"
        # rules - remove all symlinks
        find "{{.DOTFILES_CLAUDE}}/rules" -maxdepth 1 -type l -delete 2>/dev/null || true
        echo "  - dotfiles rules"
        # skills - remove all symlinks (both locations)
        find "{{.DOTFILES_CLAUDE_ONLY}}" -maxdepth 1 -type l -delete 2>/dev/null || true
        find "{{.DOTFILES_CLAUDE}}/skills" -maxdepth 1 -type l -delete 2>/dev/null || true
        echo "  - dotfiles skills"
        # commands - remove all symlinks AND regular files (legacy cleanup)
        find "{{.DOTFILES_CLAUDE}}/commands" -maxdepth 1 -type l -delete 2>/dev/null || true
        find "{{.DOTFILES_CLAUDE}}/commands" -maxdepth 1 -type f -name "*.md" -delete 2>/dev/null || true
        echo "  - dotfiles commands"
        # templates - remove all symlinks
        find "{{.DOTFILES_CLAUDE}}/templates" -maxdepth 1 -type l -delete 2>/dev/null || true
        echo "  - dotfiles templates"
        echo "Done"

  restore:
    desc: Remove and recreate all orchestra symlinks (use after path changes)
    cmds:
      - task: clean:all
      - task: sync
