version: "3"

vars:
  ORCHESTRA_DIR: $HOME/ghq/github.com/yoshihiko555/ai-orchestra

includes:
  list:
    taskfile: ./taskfiles/list.yml
    flatten: true
    vars:
      ORCHESTRA_DIR: "{{.ORCHESTRA_DIR}}"

