version: '3'

vars:
  ORCHESTRA_DIR: ~/ghq/github.com/yoshihiko555/ai-orchestra
  DOTFILES_CLAUDE: ~/ghq/github.com/yoshihiko555/dotfiles/claude/.claude
  DOTFILES_CLAUDE_ONLY: ~/ghq/github.com/yoshihiko555/dotfiles/shared/skills/claude-only
  DOTFILES_ROOT: ~/ghq/github.com/yoshihiko555/dotfiles
  HOME_CLAUDE: $HOME/.claude

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  sync:
    desc: Sync all orchestra files to dotfiles and deploy to ~/.claude
    cmds:
      - task: sync:agents
      - task: sync:hooks
      - task: sync:rules
      - task: sync:skills
      - task: deploy

  sync:agents:
    desc: Sync agent files to dotfiles
    dir: "{{.DOTFILES_CLAUDE}}/agents"
    cmds:
      - |
        echo "Syncing agents..."
        for f in {{.ORCHESTRA_DIR}}/agents/*.md; do
          [ -e "$f" ] || continue
          name=$(basename "$f")
          if [ ! -L "$name" ]; then
            ln -sf "$f" "$name"
            echo "  + $name"
          fi
        done
        echo "Done"

  sync:hooks:
    desc: Sync hook files to dotfiles
    dir: "{{.DOTFILES_CLAUDE}}/hooks"
    cmds:
      - |
        echo "Syncing hooks..."
        for f in {{.ORCHESTRA_DIR}}/hooks/*.py; do
          [ -e "$f" ] || continue
          name=$(basename "$f")
          if [ ! -L "$name" ]; then
            ln -sf "$f" "$name"
            echo "  + $name"
          fi
        done
        echo "Done"

  sync:rules:
    desc: Sync rule files to dotfiles
    dir: "{{.DOTFILES_CLAUDE}}/rules"
    cmds:
      - |
        echo "Syncing rules..."
        for f in {{.ORCHESTRA_DIR}}/rules/*.md; do
          [ -e "$f" ] || continue
          name=$(basename "$f")
          if [ ! -L "$name" ]; then
            ln -sf "$f" "$name"
            echo "  + $name"
          fi
        done
        echo "Done"

  sync:skills:
    desc: Sync skill directories to dotfiles
    cmds:
      - |
        echo "Syncing skills to claude-only..."
        cd {{.DOTFILES_CLAUDE_ONLY}}
        for d in {{.ORCHESTRA_DIR}}/skills/*/; do
          [ -d "$d" ] || continue
          name=$(basename "$d")
          if [ ! -L "$name" ]; then
            ln -sf "$d" "$name"
            echo "  + $name (claude-only)"
          fi
        done
      - |
        echo "Syncing skills to .claude/skills..."
        cd {{.DOTFILES_CLAUDE}}/skills
        for d in {{.ORCHESTRA_DIR}}/skills/*/; do
          [ -d "$d" ] || continue
          name=$(basename "$d")
          if [ ! -L "$name" ]; then
            ln -sf ../../../shared/skills/claude-only/$name $name
            echo "  + $name (.claude/skills)"
          fi
        done
        echo "Done"

  deploy:
    desc: Deploy dotfiles to ~/.claude (create directory symlinks)
    cmds:
      - |
        echo "Deploying to ~/.claude..."
        mkdir -p {{.HOME_CLAUDE}}

        # agents
        if [ ! -L "{{.HOME_CLAUDE}}/agents" ]; then
          rm -rf "{{.HOME_CLAUDE}}/agents" 2>/dev/null || true
          ln -sf "{{.DOTFILES_CLAUDE}}/agents" "{{.HOME_CLAUDE}}/agents"
          echo "  + agents"
        fi

        # hooks
        if [ ! -L "{{.HOME_CLAUDE}}/hooks" ]; then
          rm -rf "{{.HOME_CLAUDE}}/hooks" 2>/dev/null || true
          ln -sf "{{.DOTFILES_CLAUDE}}/hooks" "{{.HOME_CLAUDE}}/hooks"
          echo "  + hooks"
        fi

        # rules
        if [ ! -L "{{.HOME_CLAUDE}}/rules" ]; then
          rm -rf "{{.HOME_CLAUDE}}/rules" 2>/dev/null || true
          ln -sf "{{.DOTFILES_CLAUDE}}/rules" "{{.HOME_CLAUDE}}/rules"
          echo "  + rules"
        fi

        # skills
        if [ ! -L "{{.HOME_CLAUDE}}/skills" ]; then
          rm -rf "{{.HOME_CLAUDE}}/skills" 2>/dev/null || true
          ln -sf "{{.DOTFILES_CLAUDE}}/skills" "{{.HOME_CLAUDE}}/skills"
          echo "  + skills"
        fi

        # commands (if exists in dotfiles)
        if [ -d "{{.DOTFILES_CLAUDE}}/commands" ] && [ ! -L "{{.HOME_CLAUDE}}/commands" ]; then
          rm -rf "{{.HOME_CLAUDE}}/commands" 2>/dev/null || true
          ln -sf "{{.DOTFILES_CLAUDE}}/commands" "{{.HOME_CLAUDE}}/commands"
          echo "  + commands"
        fi

        echo "Done"

  stow:
    desc: "[Deprecated] Use 'deploy' instead. Run stow to deploy dotfiles"
    dir: "{{.DOTFILES_ROOT}}"
    cmds:
      - stow -R claude
      - echo "Stow complete"

  list:agents:
    desc: List all agents
    cmds:
      - ls -1 {{.ORCHESTRA_DIR}}/agents/*.md | xargs -n1 basename | sed 's/.md$//'

  list:hooks:
    desc: List all hooks
    cmds:
      - ls -1 {{.ORCHESTRA_DIR}}/hooks/*.py 2>/dev/null | xargs -n1 basename || echo "No hooks"

  list:skills:
    desc: List all skills
    cmds:
      - ls -1 {{.ORCHESTRA_DIR}}/skills/ 2>/dev/null || echo "No skills"

  add:agent:
    desc: "Create a new agent from template (usage: task add:agent -- agent-name)"
    cmds:
      - cp {{.ORCHESTRA_DIR}}/templates/agent-template.md {{.ORCHESTRA_DIR}}/agents/{{.CLI_ARGS}}.md
      - echo "Created {{.ORCHESTRA_DIR}}/agents/{{.CLI_ARGS}}.md"
      - echo "Edit the file, then run 'task sync'"

  add:skill:
    desc: "Create a new skill from template (usage: task add:skill -- skill-name)"
    cmds:
      - mkdir -p {{.ORCHESTRA_DIR}}/skills/{{.CLI_ARGS}}
      - cp {{.ORCHESTRA_DIR}}/templates/skill-template.md {{.ORCHESTRA_DIR}}/skills/{{.CLI_ARGS}}/SKILL.md
      - echo "Created {{.ORCHESTRA_DIR}}/skills/{{.CLI_ARGS}}/SKILL.md"
      - echo "Edit the file, then run 'task sync'"

  init:project:
    desc: "Enable orchestra in a project (run in project directory)"
    cmds:
      - mkdir -p .claude
      - |
        if [ -f .claude/settings.json ]; then
          echo "Warning: .claude/settings.json already exists"
          echo "Manually merge with: {{.ORCHESTRA_DIR}}/templates/project-settings.json"
        else
          cp {{.ORCHESTRA_DIR}}/templates/project-settings.json .claude/settings.json
          echo "Created .claude/settings.json"
          echo "Orchestra is now enabled for this project"
        fi

  clean:
    desc: Remove broken symlinks from dotfiles and ~/.claude
    cmds:
      - |
        echo "Cleaning broken symlinks..."

        # Clean ~/.claude broken symlinks
        for dir in agents hooks rules skills commands; do
          link="{{.HOME_CLAUDE}}/$dir"
          if [ -L "$link" ] && [ ! -e "$link" ]; then
            rm -f "$link"
            echo "  - ~/.claude/$dir (broken)"
          fi
        done

        # Clean dotfiles broken symlinks
        find {{.DOTFILES_CLAUDE}}/agents -type l ! -exec test -e {} \; -delete 2>/dev/null || true
        find {{.DOTFILES_CLAUDE}}/hooks -type l ! -exec test -e {} \; -delete 2>/dev/null || true
        find {{.DOTFILES_CLAUDE}}/rules -type l ! -exec test -e {} \; -delete 2>/dev/null || true
        find {{.DOTFILES_CLAUDE_ONLY}} -maxdepth 1 -type l ! -exec test -e {} \; -delete 2>/dev/null || true
        find {{.DOTFILES_CLAUDE}}/skills -maxdepth 1 -type l ! -exec test -e {} \; -delete 2>/dev/null || true
        echo "Done"

  clean:all:
    desc: Remove all orchestra symlinks from dotfiles and ~/.claude (for restore)
    cmds:
      - |
        echo "Removing all orchestra symlinks..."

        # Remove ~/.claude directory symlinks
        echo "Cleaning ~/.claude symlinks..."
        for dir in agents hooks rules skills commands; do
          if [ -L "{{.HOME_CLAUDE}}/$dir" ]; then
            rm -f "{{.HOME_CLAUDE}}/$dir"
            echo "  - ~/.claude/$dir"
          fi
        done

        # Remove dotfiles symlinks
        echo "Cleaning dotfiles symlinks..."
        # agents
        for f in {{.ORCHESTRA_DIR}}/agents/*.md; do
          [ -e "$f" ] || continue
          name=$(basename "$f")
          rm -f "{{.DOTFILES_CLAUDE}}/agents/$name"
        done
        echo "  - dotfiles agents"
        # hooks
        for f in {{.ORCHESTRA_DIR}}/hooks/*.py; do
          [ -e "$f" ] || continue
          name=$(basename "$f")
          rm -f "{{.DOTFILES_CLAUDE}}/hooks/$name"
        done
        echo "  - dotfiles hooks"
        # rules
        for f in {{.ORCHESTRA_DIR}}/rules/*.md; do
          [ -e "$f" ] || continue
          name=$(basename "$f")
          rm -f "{{.DOTFILES_CLAUDE}}/rules/$name"
        done
        echo "  - dotfiles rules"
        # skills
        for d in {{.ORCHESTRA_DIR}}/skills/*/; do
          [ -d "$d" ] || continue
          name=$(basename "$d")
          rm -f "{{.DOTFILES_CLAUDE_ONLY}}/$name"
          rm -f "{{.DOTFILES_CLAUDE}}/skills/$name"
        done
        echo "  - dotfiles skills"
        echo "Done"

  restore:
    desc: Remove and recreate all orchestra symlinks (use after path changes)
    cmds:
      - task: clean:all
      - task: sync
