"""sync-orchestra.py の sync_claudeignore / _strip_header のテスト。

既存パターン（module_loader.load_module + tmp_path）に従う。
"""

from __future__ import annotations

from pathlib import Path

from tests.module_loader import load_module

sync_mod = load_module("sync_orchestra", "scripts/sync-orchestra.py")
sync_claudeignore = sync_mod.sync_claudeignore
_strip_header = sync_mod._strip_header
CLAUDEIGNORE_HEADER = sync_mod.CLAUDEIGNORE_HEADER
LOCAL_SECTION_HEADER = sync_mod.LOCAL_SECTION_HEADER


# ---------------------------------------------------------------------------
# _strip_header
# ---------------------------------------------------------------------------


class TestStripHeader:
    def test_strips_comment_and_blank_lines(self) -> None:
        content = "# header\n# line2\n\nnode_modules/\ndist/\n"
        assert _strip_header(content) == "node_modules/\ndist/\n"

    def test_no_header(self) -> None:
        content = "node_modules/\n"
        assert _strip_header(content) == "node_modules/\n"

    def test_only_header(self) -> None:
        content = "# just comments\n# more\n\n"
        assert _strip_header(content) == ""

    def test_empty(self) -> None:
        assert _strip_header("") == ""


# ---------------------------------------------------------------------------
# sync_claudeignore
# ---------------------------------------------------------------------------


def _setup_orchestra(tmp_path: Path, base_body: str) -> Path:
    """テンプレートを配置した orchestra ディレクトリを作成して返す。"""
    orchestra = tmp_path / "orchestra"
    tpl_dir = orchestra / "templates" / "project"
    tpl_dir.mkdir(parents=True)
    tpl_file = tpl_dir / ".claudeignore"
    tpl_file.write_text(
        "# header\n# line2\n\n" + base_body,
        encoding="utf-8",
    )
    return orchestra


class TestSyncClaudeignoreBaseOnly:
    """ベーステンプレートのみ（.claudeignore.local なし）"""

    def test_generates_file(self, tmp_path: Path) -> None:
        project = tmp_path / "project"
        project.mkdir()
        orchestra = _setup_orchestra(tmp_path, "node_modules/\ndist/\n")

        result = sync_claudeignore(project, orchestra)

        assert result is True
        dst = project / ".claudeignore"
        assert dst.exists()
        content = dst.read_text(encoding="utf-8")
        assert "node_modules/" in content
        assert "dist/" in content

    def test_header_present(self, tmp_path: Path) -> None:
        project = tmp_path / "project"
        project.mkdir()
        orchestra = _setup_orchestra(tmp_path, "node_modules/\n")

        sync_claudeignore(project, orchestra)

        content = (project / ".claudeignore").read_text(encoding="utf-8")
        assert "auto-generated by AI Orchestra" in content
        assert "DO NOT EDIT" in content


class TestSyncClaudeignoreWithLocal:
    """ベース + .claudeignore.local マージ"""

    def test_merge(self, tmp_path: Path) -> None:
        project = tmp_path / "project"
        project.mkdir()
        orchestra = _setup_orchestra(tmp_path, "node_modules/\n")

        local = project / ".claudeignore.local"
        local.write_text("# local\ndata/\n*.sqlite3\n", encoding="utf-8")

        result = sync_claudeignore(project, orchestra)

        assert result is True
        content = (project / ".claudeignore").read_text(encoding="utf-8")
        assert "node_modules/" in content
        assert "data/" in content
        assert "*.sqlite3" in content

    def test_local_section_heading(self, tmp_path: Path) -> None:
        project = tmp_path / "project"
        project.mkdir()
        orchestra = _setup_orchestra(tmp_path, "node_modules/\n")

        local = project / ".claudeignore.local"
        local.write_text("data/\n", encoding="utf-8")

        sync_claudeignore(project, orchestra)

        content = (project / ".claudeignore").read_text(encoding="utf-8")
        assert "Project-specific patterns (from .claudeignore.local)" in content

    def test_empty_local_no_section(self, tmp_path: Path) -> None:
        """空の .claudeignore.local ではローカルセクションが追加されない"""
        project = tmp_path / "project"
        project.mkdir()
        orchestra = _setup_orchestra(tmp_path, "node_modules/\n")

        local = project / ".claudeignore.local"
        local.write_text("# just a comment\n", encoding="utf-8")

        sync_claudeignore(project, orchestra)

        content = (project / ".claudeignore").read_text(encoding="utf-8")
        assert LOCAL_SECTION_HEADER.strip() not in content


class TestSyncClaudeignoreIdempotency:
    """冪等性: 2回目の実行で差分なし"""

    def test_second_run_returns_false(self, tmp_path: Path) -> None:
        project = tmp_path / "project"
        project.mkdir()
        orchestra = _setup_orchestra(tmp_path, "node_modules/\n")

        first = sync_claudeignore(project, orchestra)
        second = sync_claudeignore(project, orchestra)

        assert first is True
        assert second is False

    def test_second_run_with_local_returns_false(self, tmp_path: Path) -> None:
        project = tmp_path / "project"
        project.mkdir()
        orchestra = _setup_orchestra(tmp_path, "node_modules/\n")

        local = project / ".claudeignore.local"
        local.write_text("data/\n", encoding="utf-8")

        first = sync_claudeignore(project, orchestra)
        second = sync_claudeignore(project, orchestra)

        assert first is True
        assert second is False


class TestSyncClaudeignoreBaseUpdate:
    """ベーステンプレート変更後に再生成される"""

    def test_regenerates_on_template_change(self, tmp_path: Path) -> None:
        project = tmp_path / "project"
        project.mkdir()
        orchestra = _setup_orchestra(tmp_path, "node_modules/\n")

        sync_claudeignore(project, orchestra)

        # テンプレートを更新
        tpl = orchestra / "templates" / "project" / ".claudeignore"
        tpl.write_text("# header\n\nnode_modules/\nnew_pattern/\n", encoding="utf-8")

        result = sync_claudeignore(project, orchestra)

        assert result is True
        content = (project / ".claudeignore").read_text(encoding="utf-8")
        assert "new_pattern/" in content


class TestSyncClaudeignoreMissingTemplate:
    """テンプレート不在でスキップ"""

    def test_returns_false_no_file_created(self, tmp_path: Path) -> None:
        project = tmp_path / "project"
        project.mkdir()
        orchestra = tmp_path / "orchestra"
        orchestra.mkdir()

        result = sync_claudeignore(project, orchestra)

        assert result is False
        assert not (project / ".claudeignore").exists()
