#!/usr/bin/env python3
"""LP-2 loop-harness scheduler: resident poller that discovers, spawns, and monitors workers.

One resident process per project. Each poll cycle: reap finished `loop_driver.py` workers
(restarting abnormal exits unless the loop is `failed`/`stopped`), then spawn new workers
for labeled Issues up to the concurrency cap. At startup, verifies repo-identity for any
existing loop runs and safety-stops mismatches before touching them.

See `docs/design/loop-harness-cli.md` 3 節 (authoritative design) for the contract this
module must not deviate from.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shlex
import subprocess
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any
from xml.sax.saxutils import escape as xml_escape

_SCRIPT_DIR = Path(__file__).resolve().parent
_LIB_DIR = _SCRIPT_DIR.parent / "lib"
if str(_LIB_DIR) not in sys.path:
    sys.path.insert(0, str(_LIB_DIR))

import loop_common as lc  # noqa: E402
import loop_definition as ld  # noqa: E402
import loop_driver_support as lds  # noqa: E402
import worktree_manager as wm  # noqa: E402

DEFAULT_DEFINITION_ID = "issue-loop"
DEFAULT_CONCURRENCY_LIMIT = 2
DEFAULT_POLL_INTERVAL_SECONDS = 300

_ACTIVE_STATUSES = frozenset({"running", "waiting_external"})
# G7: "passed" must also be non-restartable. A worker that already reached `passed` and then
# exits abnormally (e.g. killed mid-teardown after writing the final status) must not be
# treated as a restartable crash - the loop is done; respawning would re-attach a finished run.
_NON_RESTARTABLE_STATUSES = frozenset({"failed", "stopped", "passed"})
# Terminal outcomes for discovery purposes (#10): a labeled Issue whose loop_id already
# reached one of these must not be auto-regenerated by the next poll cycle just because the
# label is still on the Issue. Resuming a terminal loop is an explicit operator action.
_TERMINAL_STATUSES = frozenset({"passed", "failed", "stopped"})


def main(argv: list[str] | None = None) -> int:
    """CLI entry point: `loop_scheduler.py [--project <path>] [print-launchd|print-cron]`."""
    args = _parse_args(argv)
    project = _project_dir(args.project)
    if args.command == "print-launchd":
        _ensure_scheduler_log_dir(project)
        print(render_launchd_plist(project, definition_id=args.definition))
        return 0
    if args.command == "print-cron":
        _ensure_scheduler_log_dir(project)
        print(render_cron_entry(project, definition_id=args.definition))
        return 0
    run_scheduler(project, args.definition, max_cycles=args.max_cycles)
    return 0


def _ensure_scheduler_log_dir(project_dir: str) -> None:
    """Create `.claude/loop/` at template-generation time (SN4), not at job-start time.

    launchd opens `StandardOutPath`/`StandardErrorPath` for redirection *before* it exec's
    `ProgramArguments` - so the `mkdir -p ... && exec ...` wrapper baked into
    `render_launchd_plist`'s template (#H17) very likely runs too late to matter: launchd may
    already have failed to open the (nonexistent) log paths by the time that wrapper shell
    starts. Creating the directory here, once, when the operator runs
    `print-launchd`/`print-cron` to generate the install artifact, guarantees it exists before
    the job is ever installed/loaded, independent of that in-template `mkdir -p`'s actual
    effectiveness.
    """
    log_dir = Path(project_dir).resolve() / ".claude" / "loop"
    log_dir.mkdir(parents=True, exist_ok=True)


def _parse_args(argv: list[str] | None) -> argparse.Namespace:
    """Parse loop_scheduler.py CLI arguments."""
    parser = argparse.ArgumentParser(prog="loop_scheduler.py", description=__doc__)
    parser.add_argument("--project")
    parser.add_argument("--definition", default=DEFAULT_DEFINITION_ID)
    parser.add_argument(
        "--max-cycles",
        type=int,
        default=None,
        help="exit after N poll cycles instead of running forever (test/debug use)",
    )
    subparsers = parser.add_subparsers(dest="command")
    subparsers.add_parser("print-launchd", help="print a launchd plist template to stdout")
    subparsers.add_parser("print-cron", help="print a cron entry template to stdout")
    return parser.parse_args(argv)


def _project_dir(value: str | None) -> str:
    """Resolve project dir from --project or cwd's git root."""
    if value:
        return str(Path(value).resolve())
    current = Path.cwd().resolve()
    for candidate in (current, *current.parents):
        if (candidate / ".git").exists():
            return str(candidate)
    raise lc.RootResolutionError("could not find git repository root")


# -- config resolution (packages/loop-harness/config/loop-harness.yaml) ------------------------


def concurrency_limit(project_dir: str) -> int:
    """Return the configured `lp2.concurrency_limit` (default 2)."""
    config = ld.load_config(project_dir)
    return int(_nested(config, ("lp2", "concurrency_limit"), DEFAULT_CONCURRENCY_LIMIT))


def priority_labels(project_dir: str) -> list[str]:
    """Return the priority-label vocabulary, highest priority first (default: none).

    docs/design/loop-harness-cli.md 3.1 節 mentions a `priority:high`-style label as the
    top sort key "when present" and says the vocabulary is config-defined, but 5.1 節's
    config key tree does not actually enumerate such a key. This implements it as an
    optional `lp2.priority_labels` list so the base behavior without the key stays plain
    `created_at` ascending FIFO (see final report for this design decision).
    """
    config = ld.load_config(project_dir)
    value = _nested(config, ("lp2", "priority_labels"), [])
    return [str(item) for item in value] if isinstance(value, list) else []


def _nested(source: dict[str, Any], path: tuple[str, ...], default: Any) -> Any:
    """Read a nested mapping value, falling back to default on any miss."""
    current: Any = source
    for key in path:
        if not isinstance(current, dict) or key not in current:
            return default
        current = current[key]
    return current


# -- loop-definition-derived discovery parameters (3.1 節: never hardcode the label) ------------


def _trigger_lp2(definition: ld.LoopDefinition) -> dict[str, Any]:
    """Return the `trigger.lp2` mapping, or raise if the definition has none."""
    lp2 = definition.trigger.get("lp2")
    if not isinstance(lp2, dict):
        raise ld.DefinitionValidationError(
            f"{definition.id}: trigger.lp2 is required for scheduler"
        )
    return lp2


def resolve_label(definition: ld.LoopDefinition) -> str:
    """Return the label to poll for, resolved from the loop definition (never hardcoded)."""
    label = _trigger_lp2(definition).get("label")
    if not label:
        raise ld.DefinitionValidationError(f"{definition.id}: trigger.lp2.label is required")
    return str(label)


def resolve_poll_interval(definition: ld.LoopDefinition) -> int:
    """Return the discovery poll interval in seconds for this loop definition."""
    return int(_trigger_lp2(definition).get("poll_interval_seconds", DEFAULT_POLL_INTERVAL_SECONDS))


# -- discovery (3.1 節) --------------------------------------------------------------------------


def _repo_name_with_owner(project_dir: str) -> str:
    """Return `owner/repo` for the repository at project_dir."""
    completed = subprocess.run(
        ["gh", "repo", "view", "--json", "nameWithOwner", "-q", ".nameWithOwner"],
        cwd=project_dir,
        capture_output=True,
        text=True,
        timeout=30,
        check=True,
    )
    return completed.stdout.strip()


def _gh_list_issues(repo: str, label: str, project_dir: str) -> str:
    """Run `gh api .../issues` (paginated) and return its raw stdout, or "" on failure.

    `cwd=project_dir` (SN5): without it, `gh` resolves the target host/auth from whatever
    directory the resident scheduler process happens to have been started in (or its
    parent's cwd), not the actual project repository - misresolving the host on GH
    Enterprise setups (or any environment with per-directory `gh` auth/host config)
    mirrors the fix already applied in `_repo_name_with_owner`.

    `check=False`: a failed `gh` call must not raise and take the resident scheduler process
    down with it (#34). Callers treat "" the same as an empty result set and log the failure.
    `--paginate` avoids silently truncating discovery at the default 30-item page (#9); with
    `--paginate` and no `-q`/`--jq`, `gh api` writes one JSON array per page back-to-back
    (not a single combined array), so parsing must handle multiple concatenated JSON documents
    (see `_parse_paginated_json`).

    A `timeout=30` expiry is treated the same as a nonzero exit (#F20): `subprocess.run` raises
    `TimeoutExpired` instead of returning a `CompletedProcess`, which would otherwise violate
    this function's "failure returns \"\"" contract and take the resident scheduler down with it.

    A missing `gh` executable (or any other launch failure) raises `FileNotFoundError`/`OSError`
    instead of `TimeoutExpired` (#H2): without also catching `OSError` here, a `gh`-less
    environment would raise on every single poll cycle and never reach the "failure returns
    \"\"" contract at all.
    """
    try:
        completed = subprocess.run(
            [
                "gh",
                "api",
                f"repos/{repo}/issues",
                "--method",
                "GET",
                "--paginate",
                "-f",
                f"labels={label}",
                "-f",
                "state=open",
                "-f",
                "sort=created",
                "-f",
                "direction=asc",
            ],
            cwd=project_dir,
            capture_output=True,
            text=True,
            timeout=30,
            check=False,
        )
    except subprocess.TimeoutExpired:
        print(
            lc.redact(f"loop_scheduler: gh api issues timed out (repo={repo}, label={label})"),
            file=sys.stderr,
        )
        return ""
    except OSError as exc:
        print(
            lc.redact(
                f"loop_scheduler: gh api issues failed to launch (repo={repo}, label={label}): "
                f"{exc}"
            ),
            file=sys.stderr,
        )
        return ""
    if completed.returncode != 0:
        print(
            lc.redact(
                f"loop_scheduler: gh api issues failed (rc={completed.returncode}): "
                f"{completed.stderr.strip()}"
            ),
            file=sys.stderr,
        )
        return ""
    return completed.stdout


def _parse_paginated_json(raw: str) -> list[Any]:
    """Parse one or more concatenated JSON array documents (as emitted by `gh api --paginate`).

    Each page is a separate top-level JSON array written directly after the previous one with
    no separator, so a plain `json.loads` fails past the first page. Decode documents one at a
    time from wherever the previous document ended.
    """
    text = raw.strip()
    if not text:
        return []
    decoder = json.JSONDecoder()
    items: list[Any] = []
    index = 0
    length = len(text)
    while index < length:
        while index < length and text[index].isspace():
            index += 1
        if index >= length:
            break
        parsed, end = decoder.raw_decode(text, index)
        if isinstance(parsed, list):
            items.extend(parsed)
        index = end
    return items


def list_labeled_issues(project_dir: str, label: str) -> list[dict[str, Any]]:
    """Return the open, non-PR Issues carrying label, as parsed `gh api` JSON objects.

    `GET /repos/{repo}/issues` also returns pull requests (they carry a `pull_request` key);
    those must be excluded from loop discovery (#9).
    """
    repo = _repo_name_with_owner(project_dir)
    raw = _gh_list_issues(repo, label, project_dir)
    data = _parse_paginated_json(raw)
    return [item for item in data if isinstance(item, dict) and "pull_request" not in item]


def sort_candidates(
    issues: list[dict[str, Any]], priority_order: list[str]
) -> list[dict[str, Any]]:
    """Sort by priority-label rank (lower index = higher priority), then `created_at` ascending."""

    def rank(issue: dict[str, Any]) -> int:
        names = {item.get("name") for item in issue.get("labels", []) if isinstance(item, dict)}
        for index, candidate_label in enumerate(priority_order):
            if candidate_label in names:
                return index
        return len(priority_order)

    return sorted(issues, key=lambda issue: (rank(issue), str(issue.get("created_at") or "")))


def active_loop_ids(project_dir: str) -> set[str]:
    """Return loop_ids whose state.json status is running/waiting_external."""
    root = lc.loop_root(project_dir)
    if not root.is_dir():
        return set()
    active: set[str] = set()
    for entry in root.iterdir():
        state = _try_load_state(entry, project_dir)
        if state is not None and state.status in _ACTIVE_STATUSES:
            active.add(entry.name)
    return active


def _try_load_state(entry: Path, project_dir: str) -> lc.LoopState | None:
    """Load state.json under a `.claude/loop/<loop_id>/` entry, or None if absent/invalid."""
    if not entry.is_dir() or not (entry / "state.json").is_file():
        return None
    try:
        return lc.load_state(entry.name, project_dir)
    except lc.LoopHarnessError:
        return None


def _terminal_loop_ids(project_dir: str) -> set[str]:
    """Return loop_ids whose state.json status is a terminal outcome (passed/failed/stopped)."""
    root = lc.loop_root(project_dir)
    if not root.is_dir():
        return set()
    terminal: set[str] = set()
    for entry in root.iterdir():
        state = _try_load_state(entry, project_dir)
        if state is not None and state.status in _TERMINAL_STATUSES:
            terminal.add(entry.name)
    return terminal


def _pending_loop_ids(project_dir: str) -> set[str]:
    """Return loop_ids whose state.json status is "pending" (initial run_maker in flight).

    `lc.attach()` only accepts `running`/`waiting_external` status and raises
    `InvalidStateError` for `pending` - a `loop_id` still in `pending` has never completed its
    first action, so a duplicate worker spawned for the same still-labeled Issue would try to
    attach, fail immediately, and (per `should_restart`) be retried again next cycle: a
    restart storm (#G10). Unlike a terminal status, there is no automatic resolution here -
    something is wrong with the original worker - so this is treated as "exclude from
    discovery, wait for a human" rather than respawned.
    """
    root = lc.loop_root(project_dir)
    if not root.is_dir():
        return set()
    pending: set[str] = set()
    for entry in root.iterdir():
        state = _try_load_state(entry, project_dir)
        if state is not None and state.status == "pending":
            pending.add(entry.name)
    return pending


def discover_loop_ids(
    project_dir: str,
    definition: ld.LoopDefinition,
    *,
    excluded: frozenset[str] = frozenset(),
) -> list[str]:
    """Discover new loop_ids: labeled open Issues, priority/created_at ordered, minus active,
    terminal, and pending ones (#10: a terminal loop_id must not be regenerated just because
    its Issue still carries the label, resuming it is an explicit operator action; #G10: a
    still-pending loop_id cannot be attached to either, so re-spawning it would only restart-
    storm against an immediate attach failure)."""
    label = resolve_label(definition)
    issues = list_labeled_issues(project_dir, label)
    ordered = sort_candidates(issues, priority_labels(project_dir))
    skip = (
        active_loop_ids(project_dir)
        | _terminal_loop_ids(project_dir)
        | _pending_loop_ids(project_dir)
        | excluded
    )
    loop_ids: list[str] = []
    for issue in ordered:
        number = issue.get("number")
        if not isinstance(number, int):
            continue
        loop_id = wm.compute_loop_id(project_dir, number)
        if loop_id in skip:
            continue
        loop_ids.append(loop_id)
    return loop_ids


# -- spawn / monitor / restart (3.2, 3.3 節) ------------------------------------------------------


def spawn_worker(
    loop_id: str, project_dir: str, definition_id: str = DEFAULT_DEFINITION_ID
) -> subprocess.Popen[bytes]:
    """Spawn one `loop_driver.py --loop-id <id> --project <path> --definition <id>` child
    (detached session).

    Uses `sys.executable` rather than a hardcoded `"python3"` (#F10): the scheduler itself may
    be running under a venv/uv-managed interpreter, and a hardcoded `python3` could resolve to
    a different (or missing) interpreter for the worker child.

    `--definition` must reflect the loop definition discovery actually used (#G3): without it
    the child always falls back to `loop_driver.py`'s own `DEFAULT_DEFINITION_ID` for a
    brand-new loop (`_start_new_loop`), silently ignoring `--definition` passed to
    `loop_scheduler.py` at startup. It has no effect on an `attach()` (existing loop) since
    that path resolves the definition from the persisted `state.definition_id` instead.
    """
    return subprocess.Popen(
        [
            sys.executable,
            str(_SCRIPT_DIR / "loop_driver.py"),
            "--loop-id",
            loop_id,
            "--project",
            project_dir,
            "--definition",
            definition_id,
        ],
        stdin=subprocess.DEVNULL,
        start_new_session=True,
    )


def should_restart(status: str) -> bool:
    """Return True unless status is a terminal state a human must investigate first (3.3 節),
    or still `pending` (#H3/#H11).

    A `pending` loop's worker never completed its first action, so `lc.attach()` rejects it
    outright (`InvalidStateError`) - restarting it here would just restart-storm against an
    immediate attach failure every cycle. Recovery for a genuinely orphaned `pending` loop (dead
    worker, expired lease) is handled separately by `recover_orphaned_pending_loops`, which
    retires the stale state dir instead of respawning a worker against it.
    """
    return status not in _NON_RESTARTABLE_STATUSES and status != "pending"


# Mirrors `loop_driver.EXIT_FOREIGN_LEASE`; kept as a local literal instead of importing
# `loop_driver.py` from this sibling script to avoid a script-to-script import dependency.
_EXIT_FOREIGN_LEASE = 3


def lp2_lease_ttl_seconds(project_dir: str) -> int:
    """Return the configured LP-2 lease TTL (also used as the foreign-lease restart cooldown)."""
    config = ld.load_config(project_dir)
    return int(_nested(config, ("lock", "ttl_seconds", "lp2"), 300))


@dataclass
class SchedulerRuntime:
    """In-process worker bookkeeping across poll cycles (not persisted to disk)."""

    workers: dict[str, subprocess.Popen[bytes]] = field(default_factory=dict)
    stopped_loop_ids: set[str] = field(default_factory=set)
    # code H4: loop_id -> monotonic deadline before which a foreign-lease-rejected worker must
    # not be respawned (anti restart-storm guard; in-memory/per-scheduler-process only).
    foreign_lease_cooldown_until: dict[str, float] = field(default_factory=dict)


def _respawn_expired_cooldowns(runtime: SchedulerRuntime, project_dir: str) -> list[str]:
    """Respawn any `loop_id` whose foreign-lease cooldown has elapsed (code H4).

    Respects the concurrency cap (#11): if all worker slots are occupied, a still-expired
    cooldown is left in `foreign_lease_cooldown_until` (so it stays excluded from fresh
    discovery via `spawn_new_workers`) and is retried on a later cycle once a slot frees up.
    """
    now = time.monotonic()
    expired = [
        loop_id
        for loop_id, deadline in runtime.foreign_lease_cooldown_until.items()
        if now >= deadline
    ]
    available = concurrency_limit(project_dir) - len(runtime.workers)
    respawned: list[str] = []
    for loop_id in expired:
        if loop_id in runtime.workers or loop_id in runtime.stopped_loop_ids:
            del runtime.foreign_lease_cooldown_until[loop_id]
            continue
        state = _try_load_state(lc.loop_dir(loop_id, project_dir), project_dir)
        if state is None or not should_restart(state.status):
            del runtime.foreign_lease_cooldown_until[loop_id]
            continue
        if available <= 0:
            continue
        del runtime.foreign_lease_cooldown_until[loop_id]
        runtime.workers[loop_id] = spawn_worker(loop_id, project_dir)
        respawned.append(loop_id)
        available -= 1
    return respawned


def _is_lease_expired(loop_id: str, project_dir: str) -> bool:
    """Return True when loop_id's lease is absent or past its TTL (no live owner holds it)."""
    lock = lc._read_lock(lc.lock_path(loop_id, project_dir))  # noqa: SLF001 - see _safe_stop_repo_identity_mismatch precedent
    return lock is None or not lc.is_lease_alive(lock)


def _untracked_live_active_loop_ids(runtime: SchedulerRuntime, project_dir: str) -> set[str]:
    """Return active (running/waiting_external) loop_ids with a live lease this process has
    not tracked in `runtime.workers` (SN1).

    This is exactly the set `respawn_orphaned_active_loops` correctly leaves alone (a live
    lease means some owner - typically a previous scheduler process's still-running child
    left behind by a scheduler restart - still holds it, so respawning would create a
    duplicate worker). `discover_loop_ids` already excludes all of `active_loop_ids()`
    (tracked or not) from fresh candidates, so these loop_ids can never be spawned as
    duplicates. But they still occupy a real, live concurrency slot even though
    `len(runtime.workers)` does not reflect it - without counting them here too,
    `spawn_new_workers`'s naive `concurrency_limit - len(runtime.workers)` availability
    calculation would undercount actual occupancy and spawn brand-new workers past the
    configured cap.
    """
    return {
        loop_id
        for loop_id in active_loop_ids(project_dir)
        if loop_id not in runtime.workers and not _is_lease_expired(loop_id, project_dir)
    }


def respawn_orphaned_active_loops(runtime: SchedulerRuntime, project_dir: str) -> list[str]:
    """Respawn active-status loops this process lost track of, e.g. after a restart (#F4).

    `discover_loop_ids` permanently excludes any loop_id in `active_loop_ids` (state.json
    status running/waiting_external) so discovery never regenerates an already-active loop.
    But `SchedulerRuntime.workers` is in-memory only: if the scheduler process itself
    restarts, `workers` starts empty, so a loop left running/waiting_external by the previous
    process becomes untracked *and* permanently invisible to discovery, with no path back to
    a worker actually being spawned for it. Only loops whose lease has actually expired are
    eligible here - a live lease means some owner (this process's own earlier-cycle child, or
    another host/process) still holds it, so respawning would create a duplicate worker.

    `stopped` (and `failed`) loops are never touched here because `active_loop_ids` only ever
    returns running/waiting_external, never a terminal status - so EV-51 (a safety-stopped
    loop is never auto-restarted) holds structurally, not via an extra check in this function.
    """
    available = concurrency_limit(project_dir) - len(runtime.workers)
    respawned: list[str] = []
    for loop_id in active_loop_ids(project_dir):
        if available <= 0:
            break
        if loop_id in runtime.workers or loop_id in runtime.stopped_loop_ids:
            continue
        if loop_id in runtime.foreign_lease_cooldown_until:
            continue
        if not _is_lease_expired(loop_id, project_dir):
            continue
        runtime.workers[loop_id] = spawn_worker(loop_id, project_dir)
        respawned.append(loop_id)
        available -= 1
    return respawned


# Marker embedded in a retired `pending` loop's state-dir name (#H3/#H11). Real loop_ids are
# always `<repo-identity-hash>-issue-<N>` (see `worktree_manager.compute_loop_id`), which never
# contains this substring, so filtering on it cannot collide with a live loop_id. Defined in
# `loop_common.py` (as `ORPHANED_PENDING_MARKER`, SM1) so `loop_status.py` shares the same
# literal for purge-eligibility/display handling; aliased here under the historical private
# name to avoid rewriting every call site in this file.
_ORPHANED_PENDING_MARKER = lc.ORPHANED_PENDING_MARKER


def recover_orphaned_pending_loops(runtime: SchedulerRuntime, project_dir: str) -> list[str]:
    """Retire genuinely orphaned `pending` loops so their Issue can be discovered afresh
    (#H3/#H11).

    `should_restart("pending")` now refuses to respawn a `pending` loop (its worker never
    completed the first action, and `lc.attach()` rejects `pending` outright). But
    `discover_loop_ids` also permanently excludes any still-`pending` loop_id from discovery
    (#G10) - so, taken together, a `pending` loop whose worker died (or whose owning scheduler
    process itself restarted) had no path back at all: not respawned, not rediscovered,
    invisible forever even though its Issue still carries the label.

    This does not respawn a worker - `lc.attach()` would reject `pending` regardless, and a
    fresh worker cannot safely resume another worker's in-flight initial `run_maker` action.
    Instead, once the loop's lease has genuinely expired (no live owner could still complete
    it), the state dir is renamed aside to `<loop_id>.orphaned-<n>` under `.claude/loop/`
    (automating the Issue #205 manual runbook step of moving the stale dir out of the way and
    letting a fresh `start` reuse the Issue/worktree). Renaming (not deleting) preserves the
    abandoned run's journal/state for post-mortem, while `wm.compute_loop_id` for the same
    Issue number resolves to the same original `loop_id`, whose directory no longer exists, so
    the next discovery cycle treats it as a brand-new candidate.

    Loops still tracked in `runtime.workers` (this process's own in-flight worker, whose
    `state.json` simply has not yet reflected the first completed action) are left untouched,
    as is any loop whose lease is still alive (another owner might still complete it).
    """
    root = lc.loop_root(project_dir)
    if not root.is_dir():
        return []
    recovered: list[str] = []
    for entry in sorted(root.iterdir()):
        if not entry.is_dir() or _ORPHANED_PENDING_MARKER in entry.name:
            continue
        loop_id = entry.name
        if loop_id in runtime.workers:
            continue
        state = _try_load_state(entry, project_dir)
        if state is None or state.status != "pending":
            continue
        if not _is_lease_expired(loop_id, project_dir):
            continue
        _retire_orphaned_pending_dir(entry)
        recovered.append(loop_id)
    return recovered


def _retire_orphaned_pending_dir(entry: Path) -> None:
    """Rename an orphaned-pending loop's state dir aside so discovery treats it as gone."""
    root = entry.parent
    suffix = 1
    target = root / f"{entry.name}{_ORPHANED_PENDING_MARKER}{suffix}"
    while target.exists():
        suffix += 1
        target = root / f"{entry.name}{_ORPHANED_PENDING_MARKER}{suffix}"
    entry.rename(target)
    print(
        lc.redact(f"loop_scheduler: recovered orphaned pending loop {entry.name} -> {target.name}"),
        file=sys.stderr,
    )


def reap_finished_workers(runtime: SchedulerRuntime, project_dir: str) -> list[str]:
    """Poll tracked workers; restart abnormal exits unless failed/stopped. Return respawned ids.

    SN6: dead workers are reaped (freeing their concurrency slots in `runtime.workers`) *before*
    `_respawn_expired_cooldowns` is checked, not after. Checking cooldowns first would compute
    `_respawn_expired_cooldowns`'s own concurrency-cap headroom against the still-stale
    `len(runtime.workers)` count - including workers that are about to be reaped by this very
    call - starving a cooldown-elapsed loop of a slot that is in fact freeing up in this same
    cycle, deferring its restart to (at least) the next poll interval instead.
    """
    finished = [loop_id for loop_id, proc in runtime.workers.items() if proc.poll() is not None]
    respawned: list[str] = []
    for loop_id in finished:
        proc = runtime.workers.pop(loop_id)
        if proc.returncode == 0 or loop_id in runtime.stopped_loop_ids:
            continue
        if proc.returncode == _EXIT_FOREIGN_LEASE:
            # The worker never reached `LoopDriver` (rejected at lease acquisition), so
            # `state.json.status` is still "running" (owned by whoever holds the live
            # lease). Respawning immediately every cycle would restart-storm until that
            # foreign lease's own TTL naturally expires; cool down instead.
            runtime.foreign_lease_cooldown_until[loop_id] = (
                time.monotonic() + lp2_lease_ttl_seconds(project_dir)
            )
            continue
        state = _try_load_state(lc.loop_dir(loop_id, project_dir), project_dir)
        if state is None or not should_restart(state.status):
            continue
        runtime.workers[loop_id] = spawn_worker(loop_id, project_dir)
        respawned.append(loop_id)
    respawned.extend(_respawn_expired_cooldowns(runtime, project_dir))
    return respawned


def spawn_new_workers(
    runtime: SchedulerRuntime, project_dir: str, definition: ld.LoopDefinition
) -> list[str]:
    """Spawn newly discovered workers up to the concurrency cap (3.2 節).

    SN1: occupancy also counts `_untracked_live_active_loop_ids` - active loops with a live
    lease this process has not tracked in `runtime.workers` (e.g. left running by a previous
    scheduler process across a restart). `respawn_orphaned_active_loops` correctly does not
    touch them (their lease is still alive), so they never enter `runtime.workers`, but they
    are still real, live workers occupying a concurrency slot. Without counting them here,
    `concurrency_limit - len(runtime.workers)` alone would undercount actual occupancy and
    spawn brand-new workers past the configured cap.
    """
    occupied = len(runtime.workers) + len(_untracked_live_active_loop_ids(runtime, project_dir))
    available = concurrency_limit(project_dir) - occupied
    if available <= 0:
        return []
    # #11: loop_ids mid-cooldown must also be excluded so discovery does not treat a
    # foreign-lease-rejected loop as a fresh candidate while it is waiting to be respawned.
    excluded = (
        runtime.stopped_loop_ids | set(runtime.workers) | set(runtime.foreign_lease_cooldown_until)
    )
    candidates = discover_loop_ids(project_dir, definition, excluded=excluded)
    spawned: list[str] = []
    for loop_id in candidates[:available]:
        runtime.workers[loop_id] = spawn_worker(loop_id, project_dir, definition.id)
        spawned.append(loop_id)
    return spawned


def run_cycle(runtime: SchedulerRuntime, project_dir: str, definition: ld.LoopDefinition) -> None:
    """One discovery -> cap check -> spawn / monitor / restart poll cycle.

    SN6: `reap_finished_workers` (which frees dead workers' slots, then respawns any
    cooldown-elapsed loop against the now-current slot count - see that function's docstring)
    runs first, ahead of `recover_orphaned_pending_loops` and `respawn_orphaned_active_loops`,
    so a slot a cooldown-elapsed loop is waiting on is never first handed to an unrelated
    recovered/orphaned-active loop instead.
    """
    reap_finished_workers(runtime, project_dir)
    # Must run before spawn_new_workers (#H3/#H11): retiring a stale `pending` state dir this
    # cycle lets discovery treat the same Issue as a fresh candidate in this same cycle,
    # instead of only on the next poll.
    recover_orphaned_pending_loops(runtime, project_dir)
    respawn_orphaned_active_loops(runtime, project_dir)
    spawn_new_workers(runtime, project_dir, definition)


# -- startup repo-identity verification (3.4 節: safety stop) ------------------------------------


def verify_repo_identity_at_startup(project_dir: str) -> list[str]:
    """Safety-stop any existing loop whose recorded repo-identity mismatches; return stopped ids.

    SN8: a mismatched loop whose lease is still alive is deliberately excluded from the
    returned list (see `_safe_stop_repo_identity_mismatch`) - it is neither stopped nor
    treated as already-handled, so it is re-evaluated on the next call (e.g. after the
    scheduler process restarts) once the lease has actually expired.
    """
    expected = wm.resolve_repo_identity_hash(project_dir)
    root = lc.loop_root(project_dir)
    if not root.is_dir():
        return []
    stopped: list[str] = []
    for entry in sorted(root.iterdir()):
        # A retired orphaned-pending dir (see `recover_orphaned_pending_loops`) still carries
        # the original `state.loop_id` inside its state.json, but its directory name has been
        # renamed aside with `_ORPHANED_PENDING_MARKER`. Without this filter,
        # `_safe_stop_repo_identity_mismatch(state, ...)` below would write a brand-new
        # `stopped` state.json at the *original* (no-suffix) loop_dir path - which no longer
        # exists - permanently orphaning both dirs: the original path becomes an unwanted
        # terminal state blocking Issue rediscovery, and the renamed dir is left untouched
        # (still `pending`, never cleaned up).
        if not entry.is_dir() or _ORPHANED_PENDING_MARKER in entry.name:
            continue
        state = _try_load_state(entry, project_dir)
        if state is None or state.status in _NON_RESTARTABLE_STATUSES:
            continue
        if state.repo_identity_hash == expected:
            continue
        if _safe_stop_repo_identity_mismatch(state, project_dir):
            stopped.append(state.loop_id)
    return stopped


def _safe_stop_repo_identity_mismatch(state: lc.LoopState, project_dir: str) -> bool:
    """Journal-first -> state -> mandatory macOS notify -> no Issue comment (3.4 節).
    Return True iff the stop was actually written.

    Written directly (not via `loop_driver_support.persist_safe_stop`) because the
    scheduler holds no lease for a loop it is refusing to touch precisely because the
    repository identity looks wrong; a foreign/stale lease token is not evidence this
    write is unsafe the way it is for the driver's own in-flight writes.

    SN8: this function does not itself fence its `state.json` write against a live
    lease (see above - it deliberately holds none). If `state.loop_id`'s lease is still
    alive, a detached worker legitimately owns it and would overwrite this unfenced
    `stopped` write with its own next in-flight persist moments later, silently
    reverting the safety-stop. Guard against that by skipping the write entirely while
    the lease is alive (logging a warning instead) - the loop is left untouched and
    excluded from the returned `stopped` set, so it is retried (not permanently
    swallowed) the next time `verify_repo_identity_at_startup` runs, by which point the
    worker will have exited or its lease will have expired and this write can no longer
    race a live owner.
    """
    if not _is_lease_expired(state.loop_id, project_dir):
        print(
            lc.redact(
                f"loop_scheduler: {state.loop_id} repo_identity_mismatch detected but its "
                "lease is still held by a live worker; deferring safety-stop until the "
                "lease expires"
            ),
            file=sys.stderr,
        )
        return False
    lc.append_journal_event(
        state.loop_id,
        project_dir,
        "stopped",
        "scheduler",
        None,
        {"stop_reason": "repo_identity_mismatch"},
    )
    state.status = "stopped"
    state.stop_reason = "repo_identity_mismatch"
    state.pending_action = None
    state.state_version += 1
    state.updated_at = lc.now_iso()
    lc._write_state(state, project_dir)  # noqa: SLF001 - package-internal writer, see docstring
    lc.emit_loop_audit_event(
        "loop_stop",
        project_dir,
        {
            "loop_id": state.loop_id,
            "phase": state.phase,
            "final_status": "stopped",
            "stop_reason": "repo_identity_mismatch",
            "pr_number": state.pr_number,
        },
    )
    lds.notify_macos("loop-harness", lc.redact(f"{state.loop_id}: repo_identity_mismatch"))
    print(
        lc.redact(f"loop_scheduler: {state.loop_id} stopped (repo_identity_mismatch)"),
        file=sys.stderr,
    )
    return True


# -- main poll loop --------------------------------------------------------------------------


def run_scheduler(
    project_dir: str,
    definition_id: str = DEFAULT_DEFINITION_ID,
    *,
    max_cycles: int | None = None,
) -> None:
    """Run the resident scheduler loop (forever unless max_cycles is given for tests)."""
    definition = ld.load_all_definitions(project_dir).get(definition_id)
    if definition is None:
        raise ld.DefinitionValidationError(f"loop definition not found: {definition_id}")
    runtime = SchedulerRuntime()
    runtime.stopped_loop_ids.update(verify_repo_identity_at_startup(project_dir))
    poll_interval = resolve_poll_interval(definition)
    cycles = 0
    while max_cycles is None or cycles < max_cycles:
        try:
            run_cycle(runtime, project_dir, definition)
        except Exception as exc:  # noqa: BLE001 - a resident poller must survive a bad cycle (#21)
            print(lc.redact(f"loop_scheduler: poll cycle failed: {exc}"), file=sys.stderr)
        cycles += 1
        if max_cycles is not None and cycles >= max_cycles:
            break
        time.sleep(poll_interval)


# -- cron / launchd templates (3.5 節: template generation only, no auto-install) ----------------


def _project_slug(project_dir: str) -> str:
    """Return a short stable hash of project_dir, for a per-project-unique launchd label
    (#H16): multiple projects sharing the same `loop_scheduler.py` script path (e.g. installed
    from the same ai-orchestra package into different repos) must not collide on one fixed
    label - launchd treats the label as a unique job identifier, so a second project's
    `launchctl load` would either silently no-op or clobber the first project's job.
    """
    material = str(Path(project_dir).resolve())
    return hashlib.sha256(material.encode("utf-8")).hexdigest()[:12]


def render_launchd_plist(
    project_dir: str,
    script_path: Path | None = None,
    python_bin: str | None = None,
    definition_id: str = DEFAULT_DEFINITION_ID,
) -> str:
    """Render a launchd plist template for `--install-launchd`-style manual setup.

    Every interpolated path is XML-escaped (#12): an unescaped `&`/`<`/`>` in `project_dir`
    would otherwise produce invalid plist XML.

    Uses `sys.executable` rather than a hardcoded `/usr/bin/python3` (#G8): a launchd job
    started with the system interpreter cannot import a venv/uv-managed dependency the
    scheduler itself was actually installed under, so the resident job would die immediately
    on start. Mirrors the same fix already applied to `spawn_worker` (#F10).

    `--definition` is only appended when it differs from `DEFAULT_DEFINITION_ID` (#H15):
    without it, `--install-launchd`-generated jobs for a non-default loop definition would
    silently poll the wrong (default) definition's label/interval forever.

    The `Label` is suffixed with a hash of `project_dir` (#H16, see `_project_slug`) so
    multiple projects never collide on one fixed launchd job identifier.

    The `ProgramArguments` command is wrapped in `/bin/sh -c 'mkdir -p ... && exec ...'` (#H17):
    `.claude/loop/` may not exist yet on a fresh checkout, and launchd's `StandardOutPath` /
    `StandardErrorPath` redirection fails outright (job never starts) if its parent directory
    is missing - unlike a shell's `>>` redirection, launchd does not create it. `exec` replaces
    the shell so the scheduler still becomes the tracked/`KeepAlive`-monitored process,
    matching a plain direct invocation for restart purposes.

    SN4: the in-template `mkdir -p` above is unlikely to actually help on its own - launchd
    opens `StandardOutPath`/`StandardErrorPath` for redirection *before* `ProgramArguments` is
    exec'd, so by the time `mkdir -p` in this wrapper shell runs, launchd may have already
    failed to open those paths. The log dir is therefore also (redundantly, but authoritatively)
    created eagerly by `main()`'s `print-launchd` handler at template-generation time - i.e. the
    log dir is expected to already exist by the time this plist is ever installed/loaded. The
    in-template `mkdir -p` is left in place as a harmless belt-and-suspenders guard (e.g. if the
    log dir is deleted after generation but before install).
    """
    script = str(script_path or _SCRIPT_DIR / "loop_scheduler.py")
    project = str(Path(project_dir).resolve())
    python = str(python_bin or sys.executable)
    log_dir = f"{project}/.claude/loop"
    stdout_log = f"{log_dir}/scheduler.stdout.log"
    stderr_log = f"{log_dir}/scheduler.stderr.log"
    label = f"com.ai-orchestra.loop-scheduler.{_project_slug(project)}"
    definition_args = ""
    if definition_id != DEFAULT_DEFINITION_ID:
        definition_args = f" --definition {shlex.quote(definition_id)}"
    exec_command = (
        f"mkdir -p {shlex.quote(log_dir)} && exec {shlex.quote(python)} {shlex.quote(script)} "
        f"--project {shlex.quote(project)}{definition_args}"
    )
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" '
        '"http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n'
        '<plist version="1.0">\n'
        "<dict>\n"
        "  <key>Label</key>\n"
        f"  <string>{xml_escape(label)}</string>\n"
        "  <key>ProgramArguments</key>\n"
        "  <array>\n"
        "    <string>/bin/sh</string>\n"
        "    <string>-c</string>\n"
        f"    <string>{xml_escape(exec_command)}</string>\n"
        "  </array>\n"
        "  <key>RunAtLoad</key>\n"
        "  <true/>\n"
        "  <key>KeepAlive</key>\n"
        "  <true/>\n"
        "  <key>StandardOutPath</key>\n"
        f"  <string>{xml_escape(stdout_log)}</string>\n"
        "  <key>StandardErrorPath</key>\n"
        f"  <string>{xml_escape(stderr_log)}</string>\n"
        "</dict>\n"
        "</plist>\n"
    )


def render_cron_entry(
    project_dir: str,
    script_path: Path | None = None,
    python_bin: str | None = None,
    definition_id: str = DEFAULT_DEFINITION_ID,
) -> str:
    """Render a cron entry template: `pgrep` guard that restarts the scheduler if it died.

    Every interpolated path is shell-quoted individually (#12): an unescaped `project_dir`
    containing whitespace or shell metacharacters (`;`, `|`, `&`, ...) would otherwise split
    into extra tokens or inject additional commands into the crontab line.

    Uses `sys.executable` rather than a hardcoded `/usr/bin/python3` (#G8), matching the same
    fix in `render_launchd_plist` and `spawn_worker` (#F10): cron's own minimal environment
    would otherwise invoke a system interpreter that cannot import a venv/uv-managed
    dependency the scheduler was actually installed under.

    `--definition` is only appended when it differs from `DEFAULT_DEFINITION_ID` (#H15),
    mirroring `render_launchd_plist`: otherwise a cron-restarted scheduler for a non-default
    loop definition would silently fall back to polling the default definition's label.

    `pgrep -f` matches against the *entire* pattern string given, so the guard now matches on
    `<script> --project <project>` (not the script path alone) (#H16): with multiple projects
    installed from the same `loop_scheduler.py` script, a script-path-only pattern would treat
    any other project's already-running scheduler as "this project's scheduler is alive" and
    skip starting a new one for the current project entirely.

    `script`/`project` are `re.escape`-d before being embedded in the `pgrep -f` pattern
    (SM2): `pgrep -f` interprets its argument as a POSIX extended regular expression, not a
    literal string, so an unescaped path containing ERE metacharacters (`( ) + [ ] * ? |`
    etc. - all legal filesystem-path characters) could fail to match at all or match the
    wrong process. This is unrelated to the `shlex.quote` calls elsewhere in this function,
    which only protect *shell* parsing of the crontab line, not `pgrep`'s own regex parsing
    of the (already shell-unescaped) pattern string it receives. `render_launchd_plist` has
    no equivalent issue: its `ProgramArguments` array passes the script path as a literal
    argv element (no shell/regex re-parsing), so no such escaping is needed there.

    The cron line is prefixed with `mkdir -p <log dir> &&` (#H17): `.claude/loop/` may not
    exist yet on a fresh checkout, and the shell's `>> ... 2>&1` redirection at the end of this
    line fails outright (whole command errors out, scheduler never starts) if its parent
    directory is missing.

    Known limitation (#13, accepted as-is): `pgrep -f <pattern>` can also match the cron
    wrapper shell's own argv, since the *entire* crontab command line (including this pgrep
    invocation's own text) is visible to `pgrep -f` and literally contains the pattern text a
    second time in the fallback `python3 <script> --project <project>` invocation. A textual
    pattern tweak (e.g. the classic `[l]oop_scheduler.py` bracket trick) cannot fix this
    because the self-match comes from the fallback command's own text, not from the pgrep
    invocation. A correct fix needs a pidfile/flock-based liveness check written by
    `loop_scheduler.py` at startup, which is a larger, riskier change than a
    template-rendering fix belongs in; left as a template TODO for a follow-up rather than
    bundled here.

    Every literal `%` in the assembled line is escaped to `\\%` (SN7): `crontab` treats an
    unescaped `%` as a newline at the crontab-file-parsing stage, *before* the shell ever
    sees the line - splitting the command there (and feeding the remainder to the command's
    stdin) regardless of any `shlex.quote` shell-quoting already applied. A `project_dir`
    containing a literal `%` (a legal filesystem-path character) would otherwise silently
    truncate this cron entry into a broken, partially-executed command.
    """
    script = str(script_path or _SCRIPT_DIR / "loop_scheduler.py")
    project = str(Path(project_dir).resolve())
    python = str(python_bin or sys.executable)
    log_dir = f"{project}/.claude/loop"
    log_path = f"{log_dir}/scheduler.log"
    definition_args = ""
    if definition_id != DEFAULT_DEFINITION_ID:
        definition_args = f" --definition {shlex.quote(definition_id)}"
    # `pgrep -f <pattern>` treats <pattern> as a POSIX extended regular expression, not a
    # literal string (SM2): an unescaped `script`/`project` containing ERE metacharacters
    # (`( ) + [ ] * ? |` etc., all legal in a filesystem path) would either fail to match at
    # all (e.g. an unbalanced `(`) or match something other than the literal path intended.
    # `re.escape` backslash-escapes those metacharacters so pgrep matches them literally.
    pgrep_pattern = f"{re.escape(script)} --project {re.escape(project)}"
    line = (
        f"*/5 * * * * mkdir -p {shlex.quote(log_dir)} && "
        f"pgrep -f {shlex.quote(pgrep_pattern)} || "
        f"{shlex.quote(python)} {shlex.quote(script)} --project {shlex.quote(project)}"
        f"{definition_args} >> {shlex.quote(log_path)} 2>&1\n"
    )
    return line.replace("%", "\\%")


if __name__ == "__main__":
    sys.exit(main())
