#!/usr/bin/env python3
"""LP-2 loop-harness scheduler: resident poller that discovers, spawns, and monitors workers.

One resident process per project. Each poll cycle: reap finished `loop_driver.py` workers
(restarting abnormal exits unless the loop is `failed`/`stopped`), then spawn new workers
for labeled Issues up to the concurrency cap. At startup, verifies repo-identity for any
existing loop runs and safety-stops mismatches before touching them.

See `docs/design/loop-harness-cli.md` 3 節 (authoritative design) for the contract this
module must not deviate from.
"""

from __future__ import annotations

import argparse
import fcntl
import hashlib
import json
import os
import re
import shlex
import subprocess
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any
from xml.sax.saxutils import escape as xml_escape

_SCRIPT_DIR = Path(__file__).resolve().parent
_LIB_DIR = _SCRIPT_DIR.parent / "lib"
if str(_LIB_DIR) not in sys.path:
    sys.path.insert(0, str(_LIB_DIR))

import loop_common as lc  # noqa: E402
import loop_definition as ld  # noqa: E402
import loop_driver_support as lds  # noqa: E402
import worktree_manager as wm  # noqa: E402

DEFAULT_DEFINITION_ID = "issue-loop"
DEFAULT_CONCURRENCY_LIMIT = 2
DEFAULT_POLL_INTERVAL_SECONDS = 300

_ACTIVE_STATUSES = frozenset({"running", "waiting_external"})
# G7: "passed" must also be non-restartable. A worker that already reached `passed` and then
# exits abnormally (e.g. killed mid-teardown after writing the final status) must not be
# treated as a restartable crash - the loop is done; respawning would re-attach a finished run.
_NON_RESTARTABLE_STATUSES = frozenset({"failed", "stopped", "passed"})
# Terminal outcomes for discovery purposes (#10): a labeled Issue whose loop_id already
# reached one of these must not be auto-regenerated by the next poll cycle just because the
# label is still on the Issue. Resuming a terminal loop is an explicit operator action.
_TERMINAL_STATUSES = frozenset({"passed", "failed", "stopped"})
# SN2: suffix for a purged loop's lightweight tombstone file, written by
# `loop_status.purge_loop` directly under `.claude/loop/` (never inside a per-loop dir, so it
# survives that dir's `rmtree`). Kept as a local literal instead of importing `loop_status.py`
# from this sibling script (mirrors the `_EXIT_FOREIGN_LEASE` precedent below, avoiding a
# script-to-script import dependency) - both scripts must agree on this exact literal.
_TOMBSTONE_SUFFIX = ".tombstone.json"


def main(argv: list[str] | None = None) -> int:
    """CLI entry point:
    `loop_scheduler.py [--project <path>] [print-launchd|print-cron|is-alive]`."""
    args = _parse_args(argv)
    project = _project_dir(args.project)
    if args.command == "print-launchd":
        _ensure_scheduler_log_dir(project)
        print(render_launchd_plist(project, definition_id=args.definition))
        return 0
    if args.command == "print-cron":
        _ensure_scheduler_log_dir(project)
        print(render_cron_entry(project, definition_id=args.definition))
        return 0
    if args.command == "is-alive":
        return 0 if is_scheduler_alive(project, definition_id=args.definition) else 1
    run_scheduler(project, args.definition, max_cycles=args.max_cycles)
    return 0


def _ensure_scheduler_log_dir(project_dir: str) -> None:
    """Create `.claude/loop/` at template-generation time (SN4), not at job-start time.

    launchd opens `StandardOutPath`/`StandardErrorPath` for redirection *before* it exec's
    `ProgramArguments` - so the `mkdir -p ... && exec ...` wrapper baked into
    `render_launchd_plist`'s template (#H17) very likely runs too late to matter: launchd may
    already have failed to open the (nonexistent) log paths by the time that wrapper shell
    starts. Creating the directory here, once, when the operator runs
    `print-launchd`/`print-cron` to generate the install artifact, guarantees it exists before
    the job is ever installed/loaded, independent of that in-template `mkdir -p`'s actual
    effectiveness.
    """
    log_dir = Path(project_dir).resolve() / ".claude" / "loop"
    log_dir.mkdir(parents=True, exist_ok=True)


def _parse_args(argv: list[str] | None) -> argparse.Namespace:
    """Parse loop_scheduler.py CLI arguments."""
    parser = argparse.ArgumentParser(prog="loop_scheduler.py", description=__doc__)
    parser.add_argument("--project")
    parser.add_argument("--definition", default=DEFAULT_DEFINITION_ID)
    parser.add_argument(
        "--max-cycles",
        type=int,
        default=None,
        help="exit after N poll cycles instead of running forever (test/debug use)",
    )
    subparsers = parser.add_subparsers(dest="command")
    subparsers.add_parser("print-launchd", help="print a launchd plist template to stdout")
    subparsers.add_parser("print-cron", help="print a cron entry template to stdout")
    subparsers.add_parser(
        "is-alive",
        help=(
            "exit 0 if a resident scheduler already holds the pidfile flock for "
            "--project/--definition (Issue #216), exit 1 otherwise"
        ),
    )
    return parser.parse_args(argv)


def _project_dir(value: str | None) -> str:
    """Resolve project dir from --project or cwd's git root."""
    if value:
        return str(Path(value).resolve())
    current = Path.cwd().resolve()
    for candidate in (current, *current.parents):
        if (candidate / ".git").exists():
            return str(candidate)
    raise lc.RootResolutionError("could not find git repository root")


# -- config resolution (packages/loop-harness/config/loop-harness.yaml) ------------------------


def concurrency_limit(project_dir: str) -> int:
    """Return the configured `lp2.concurrency_limit` (default 2)."""
    config = ld.load_config(project_dir)
    return int(_nested(config, ("lp2", "concurrency_limit"), DEFAULT_CONCURRENCY_LIMIT))


def priority_labels(project_dir: str) -> list[str]:
    """Return the priority-label vocabulary, highest priority first (default: none).

    docs/design/loop-harness-cli.md 3.1 節 mentions a `priority:high`-style label as the
    top sort key "when present" and says the vocabulary is config-defined, but 5.1 節's
    config key tree does not actually enumerate such a key. This implements it as an
    optional `lp2.priority_labels` list so the base behavior without the key stays plain
    `created_at` ascending FIFO (see final report for this design decision).
    """
    config = ld.load_config(project_dir)
    value = _nested(config, ("lp2", "priority_labels"), [])
    return [str(item) for item in value] if isinstance(value, list) else []


def _nested(source: dict[str, Any], path: tuple[str, ...], default: Any) -> Any:
    """Read a nested mapping value, falling back to default on any miss."""
    current: Any = source
    for key in path:
        if not isinstance(current, dict) or key not in current:
            return default
        current = current[key]
    return current


# -- loop-definition-derived discovery parameters (3.1 節: never hardcode the label) ------------


def _trigger_lp2(definition: ld.LoopDefinition) -> dict[str, Any]:
    """Return the `trigger.lp2` mapping, or raise if the definition has none."""
    lp2 = definition.trigger.get("lp2")
    if not isinstance(lp2, dict):
        raise ld.DefinitionValidationError(
            f"{definition.id}: trigger.lp2 is required for scheduler"
        )
    return lp2


def resolve_label(definition: ld.LoopDefinition) -> str:
    """Return the label to poll for, resolved from the loop definition (never hardcoded)."""
    label = _trigger_lp2(definition).get("label")
    if not label:
        raise ld.DefinitionValidationError(f"{definition.id}: trigger.lp2.label is required")
    return str(label)


def resolve_poll_interval(definition: ld.LoopDefinition) -> int:
    """Return the discovery poll interval in seconds for this loop definition."""
    return int(_trigger_lp2(definition).get("poll_interval_seconds", DEFAULT_POLL_INTERVAL_SECONDS))


# -- discovery (3.1 節) --------------------------------------------------------------------------


def _repo_name_with_owner(project_dir: str) -> str:
    """Return `owner/repo` for the repository at project_dir."""
    completed = subprocess.run(
        ["gh", "repo", "view", "--json", "nameWithOwner", "-q", ".nameWithOwner"],
        cwd=project_dir,
        capture_output=True,
        text=True,
        timeout=30,
        check=True,
    )
    return completed.stdout.strip()


def _gh_list_issues(repo: str, label: str, project_dir: str) -> str:
    """Run `gh api .../issues` (paginated) and return its raw stdout, or "" on failure.

    `cwd=project_dir` (SN5): without it, `gh` resolves the target host/auth from whatever
    directory the resident scheduler process happens to have been started in (or its
    parent's cwd), not the actual project repository - misresolving the host on GH
    Enterprise setups (or any environment with per-directory `gh` auth/host config)
    mirrors the fix already applied in `_repo_name_with_owner`.

    `check=False`: a failed `gh` call must not raise and take the resident scheduler process
    down with it (#34). Callers treat "" the same as an empty result set and log the failure.
    `--paginate` avoids silently truncating discovery at the default 30-item page (#9); with
    `--paginate` and no `-q`/`--jq`, `gh api` writes one JSON array per page back-to-back
    (not a single combined array), so parsing must handle multiple concatenated JSON documents
    (see `_parse_paginated_json`).

    A `timeout=30` expiry is treated the same as a nonzero exit (#F20): `subprocess.run` raises
    `TimeoutExpired` instead of returning a `CompletedProcess`, which would otherwise violate
    this function's "failure returns \"\"" contract and take the resident scheduler down with it.

    A missing `gh` executable (or any other launch failure) raises `FileNotFoundError`/`OSError`
    instead of `TimeoutExpired` (#H2): without also catching `OSError` here, a `gh`-less
    environment would raise on every single poll cycle and never reach the "failure returns
    \"\"" contract at all.
    """
    try:
        completed = subprocess.run(
            [
                "gh",
                "api",
                f"repos/{repo}/issues",
                "--method",
                "GET",
                "--paginate",
                "-f",
                f"labels={label}",
                "-f",
                "state=open",
                "-f",
                "sort=created",
                "-f",
                "direction=asc",
            ],
            cwd=project_dir,
            capture_output=True,
            text=True,
            timeout=30,
            check=False,
        )
    except subprocess.TimeoutExpired:
        print(
            lc.redact(f"loop_scheduler: gh api issues timed out (repo={repo}, label={label})"),
            file=sys.stderr,
        )
        return ""
    except OSError as exc:
        print(
            lc.redact(
                f"loop_scheduler: gh api issues failed to launch (repo={repo}, label={label}): "
                f"{exc}"
            ),
            file=sys.stderr,
        )
        return ""
    if completed.returncode != 0:
        print(
            lc.redact(
                f"loop_scheduler: gh api issues failed (rc={completed.returncode}): "
                f"{completed.stderr.strip()}"
            ),
            file=sys.stderr,
        )
        return ""
    return completed.stdout


def _parse_paginated_json(raw: str) -> list[Any]:
    """Parse one or more concatenated JSON array documents (as emitted by `gh api --paginate`).

    Each page is a separate top-level JSON array written directly after the previous one with
    no separator, so a plain `json.loads` fails past the first page. Decode documents one at a
    time from wherever the previous document ended.
    """
    text = raw.strip()
    if not text:
        return []
    decoder = json.JSONDecoder()
    items: list[Any] = []
    index = 0
    length = len(text)
    while index < length:
        while index < length and text[index].isspace():
            index += 1
        if index >= length:
            break
        parsed, end = decoder.raw_decode(text, index)
        if isinstance(parsed, list):
            items.extend(parsed)
        index = end
    return items


def list_labeled_issues(project_dir: str, label: str) -> list[dict[str, Any]]:
    """Return the open, non-PR Issues carrying label, as parsed `gh api` JSON objects.

    `GET /repos/{repo}/issues` also returns pull requests (they carry a `pull_request` key);
    those must be excluded from loop discovery (#9).
    """
    repo = _repo_name_with_owner(project_dir)
    raw = _gh_list_issues(repo, label, project_dir)
    data = _parse_paginated_json(raw)
    return [item for item in data if isinstance(item, dict) and "pull_request" not in item]


def sort_candidates(
    issues: list[dict[str, Any]], priority_order: list[str]
) -> list[dict[str, Any]]:
    """Sort by priority-label rank (lower index = higher priority), then `created_at` ascending."""

    def rank(issue: dict[str, Any]) -> int:
        names = {item.get("name") for item in issue.get("labels", []) if isinstance(item, dict)}
        for index, candidate_label in enumerate(priority_order):
            if candidate_label in names:
                return index
        return len(priority_order)

    return sorted(issues, key=lambda issue: (rank(issue), str(issue.get("created_at") or "")))


def active_loop_ids(project_dir: str) -> set[str]:
    """Return loop_ids whose state.json status is running/waiting_external."""
    root = lc.loop_root(project_dir)
    if not root.is_dir():
        return set()
    active: set[str] = set()
    for entry in root.iterdir():
        state = _try_load_state(entry, project_dir)
        if state is not None and state.status in _ACTIVE_STATUSES:
            active.add(entry.name)
    return active


def _try_load_state(entry: Path, project_dir: str) -> lc.LoopState | None:
    """Load state.json under a `.claude/loop/<loop_id>/` entry, or None if absent/invalid."""
    if not entry.is_dir() or not (entry / "state.json").is_file():
        return None
    try:
        return lc.load_state(entry.name, project_dir)
    except lc.LoopHarnessError:
        return None


def _terminal_loop_ids(project_dir: str) -> set[str]:
    """Return loop_ids whose state.json status is a terminal outcome (passed/failed/stopped),
    plus any loop_id with a purge tombstone (SN2).

    A purged loop's state.json is gone entirely (nothing left to report a status for), but it
    must still count as terminal for discovery purposes (#10's rationale extends unchanged to
    a purged loop) - otherwise a purged Issue that still carries the label would be treated as
    a brand-new candidate the moment the next poll cycle runs, defeating the whole point of
    purging it in the first place.
    """
    root = lc.loop_root(project_dir)
    if not root.is_dir():
        return set()
    terminal: set[str] = set()
    for entry in root.iterdir():
        state = _try_load_state(entry, project_dir)
        if state is not None and state.status in _TERMINAL_STATUSES:
            terminal.add(entry.name)
    terminal |= _tombstoned_loop_ids(project_dir)
    return terminal


def _tombstoned_loop_ids(project_dir: str) -> set[str]:
    """Return loop_ids with a purge tombstone (SN2, see `_TOMBSTONE_SUFFIX`)."""
    root = lc.loop_root(project_dir)
    if not root.is_dir():
        return set()
    tombstoned: set[str] = set()
    for entry in root.glob(f"*{_TOMBSTONE_SUFFIX}"):
        loop_id = entry.name[: -len(_TOMBSTONE_SUFFIX)]
        if loop_id:
            tombstoned.add(loop_id)
    return tombstoned


def _pending_loop_ids(project_dir: str) -> set[str]:
    """Return loop_ids whose state.json status is "pending" (initial run_maker in flight).

    `lc.attach()` only accepts `running`/`waiting_external` status and raises
    `InvalidStateError` for `pending` - a `loop_id` still in `pending` has never completed its
    first action, so a duplicate worker spawned for the same still-labeled Issue would try to
    attach, fail immediately, and (per `should_restart`) be retried again next cycle: a
    restart storm (#G10). Unlike a terminal status, there is no automatic resolution here -
    something is wrong with the original worker - so this is treated as "exclude from
    discovery, wait for a human" rather than respawned.
    """
    root = lc.loop_root(project_dir)
    if not root.is_dir():
        return set()
    pending: set[str] = set()
    for entry in root.iterdir():
        state = _try_load_state(entry, project_dir)
        if state is not None and state.status == "pending":
            pending.add(entry.name)
    return pending


def discover_loop_ids(
    project_dir: str,
    definition: ld.LoopDefinition,
    *,
    excluded: frozenset[str] = frozenset(),
) -> list[str]:
    """Discover new loop_ids: labeled open Issues, priority/created_at ordered, minus active,
    terminal, and pending ones (#10: a terminal loop_id must not be regenerated just because
    its Issue still carries the label, resuming it is an explicit operator action; #G10: a
    still-pending loop_id cannot be attached to either, so re-spawning it would only restart-
    storm against an immediate attach failure)."""
    label = resolve_label(definition)
    issues = list_labeled_issues(project_dir, label)
    ordered = sort_candidates(issues, priority_labels(project_dir))
    skip = (
        active_loop_ids(project_dir)
        | _terminal_loop_ids(project_dir)
        | _pending_loop_ids(project_dir)
        | excluded
    )
    loop_ids: list[str] = []
    for issue in ordered:
        number = issue.get("number")
        if not isinstance(number, int):
            continue
        loop_id = wm.compute_loop_id(project_dir, number)
        if loop_id in skip:
            continue
        loop_ids.append(loop_id)
    return loop_ids


# -- spawn / monitor / restart (3.2, 3.3 節) ------------------------------------------------------


def spawn_worker(
    loop_id: str, project_dir: str, definition_id: str = DEFAULT_DEFINITION_ID
) -> subprocess.Popen[bytes]:
    """Spawn one `loop_driver.py --loop-id <id> --project <path> --definition <id>` child
    (detached session).

    Uses `sys.executable` rather than a hardcoded `"python3"` (#F10): the scheduler itself may
    be running under a venv/uv-managed interpreter, and a hardcoded `python3` could resolve to
    a different (or missing) interpreter for the worker child.

    `--definition` must reflect the loop definition discovery actually used (#G3): without it
    the child always falls back to `loop_driver.py`'s own `DEFAULT_DEFINITION_ID` for a
    brand-new loop (`_start_new_loop`), silently ignoring `--definition` passed to
    `loop_scheduler.py` at startup. It has no effect on an `attach()` (existing loop) since
    that path resolves the definition from the persisted `state.definition_id` instead.
    """
    return subprocess.Popen(
        [
            sys.executable,
            str(_SCRIPT_DIR / "loop_driver.py"),
            "--loop-id",
            loop_id,
            "--project",
            project_dir,
            "--definition",
            definition_id,
        ],
        stdin=subprocess.DEVNULL,
        start_new_session=True,
    )


def should_restart(status: str) -> bool:
    """Return True unless status is a terminal state a human must investigate first (3.3 節),
    or still `pending` (#H3/#H11).

    A `pending` loop's worker never completed its first action, so `lc.attach()` rejects it
    outright (`InvalidStateError`) - restarting it here would just restart-storm against an
    immediate attach failure every cycle. Recovery for a genuinely orphaned `pending` loop (dead
    worker, expired lease) is handled separately by `recover_orphaned_pending_loops`, which
    retires the stale state dir instead of respawning a worker against it.
    """
    return status not in _NON_RESTARTABLE_STATUSES and status != "pending"


# Mirrors `loop_driver.EXIT_FOREIGN_LEASE`; kept as a local literal instead of importing
# `loop_driver.py` from this sibling script to avoid a script-to-script import dependency.
_EXIT_FOREIGN_LEASE = 3


def lp2_lease_ttl_seconds(project_dir: str) -> int:
    """Return the configured LP-2 lease TTL (also used as the foreign-lease restart cooldown)."""
    config = ld.load_config(project_dir)
    return int(_nested(config, ("lock", "ttl_seconds", "lp2"), 300))


@dataclass
class SchedulerRuntime:
    """In-process worker bookkeeping across poll cycles (not persisted to disk)."""

    workers: dict[str, subprocess.Popen[bytes]] = field(default_factory=dict)
    stopped_loop_ids: set[str] = field(default_factory=set)
    # code H4: loop_id -> monotonic deadline before which a foreign-lease-rejected worker must
    # not be respawned (anti restart-storm guard; in-memory/per-scheduler-process only).
    foreign_lease_cooldown_until: dict[str, float] = field(default_factory=dict)


def _respawn_expired_cooldowns(runtime: SchedulerRuntime, project_dir: str) -> list[str]:
    """Respawn any `loop_id` whose foreign-lease cooldown has elapsed (code H4).

    Respects the concurrency cap (#11): if all worker slots are occupied, a still-expired
    cooldown is left in `foreign_lease_cooldown_until` (so it stays excluded from fresh
    discovery via `spawn_new_workers`) and is retried on a later cycle once a slot frees up
    (SN1: via `_available_worker_slots`, shared with `spawn_new_workers` and
    `respawn_orphaned_active_loops`).

    The (git-resolution-requiring) `_available_worker_slots` call is skipped entirely when
    there is nothing expired to respawn - this function runs every poll cycle regardless of
    whether any foreign-lease cooldown is even pending, so paying for an occupancy
    calculation nobody needs on the common empty-cooldown cycle would be wasted work.

    J1: `_recheck_repo_identity_before_respawn` re-verifies repo-identity immediately before
    respawning any expired-cooldown loop_id here, for the same reason it guards
    `respawn_orphaned_active_loops` and `reap_finished_workers`'s crash-restart branch - see
    that helper's docstring.
    """
    now = time.monotonic()
    expired = [
        loop_id
        for loop_id, deadline in runtime.foreign_lease_cooldown_until.items()
        if now >= deadline
    ]
    if not expired:
        return []
    available = _available_worker_slots(runtime, project_dir)
    respawned: list[str] = []
    expected_repo_identity_hash: str | None = None
    for loop_id in expired:
        if loop_id in runtime.workers or loop_id in runtime.stopped_loop_ids:
            del runtime.foreign_lease_cooldown_until[loop_id]
            continue
        state = _try_load_state(lc.loop_dir(loop_id, project_dir), project_dir)
        if state is None or not should_restart(state.status):
            del runtime.foreign_lease_cooldown_until[loop_id]
            continue
        if available <= 0:
            continue
        if expected_repo_identity_hash is None:
            expected_repo_identity_hash = wm.resolve_repo_identity_hash(project_dir)
        if not _recheck_repo_identity_before_respawn(
            loop_id, project_dir, expected_repo_identity_hash, runtime, state=state
        ):
            del runtime.foreign_lease_cooldown_until[loop_id]
            continue
        del runtime.foreign_lease_cooldown_until[loop_id]
        runtime.workers[loop_id] = spawn_worker(loop_id, project_dir)
        respawned.append(loop_id)
        available -= 1
    return respawned


def _is_lease_expired(loop_id: str, project_dir: str) -> bool:
    """Return True when loop_id's lease is absent or past its TTL (no live owner holds it)."""
    lock = lc._read_lock(lc.lock_path(loop_id, project_dir))  # noqa: SLF001 - see _safe_stop_repo_identity_mismatch precedent
    return lock is None or not lc.is_lease_alive(lock)


def _untracked_live_active_loop_ids(runtime: SchedulerRuntime, project_dir: str) -> set[str]:
    """Return active (running/waiting_external) *and* still-pending loop_ids with a live lease
    this process has not tracked in `runtime.workers` (SN1, extended by #I2 for `pending`).

    This is exactly the set `respawn_orphaned_active_loops` correctly leaves alone (a live
    lease means some owner - typically a previous scheduler process's still-running child
    left behind by a scheduler restart - still holds it, so respawning would create a
    duplicate worker). `discover_loop_ids` already excludes all of `active_loop_ids()`
    (tracked or not) from fresh candidates, so these loop_ids can never be spawned as
    duplicates. But they still occupy a real, live concurrency slot even though
    `len(runtime.workers)` does not reflect it - without counting them here too,
    `spawn_new_workers`'s naive `concurrency_limit - len(runtime.workers)` availability
    calculation would undercount actual occupancy and spawn brand-new workers past the
    configured cap.

    #I2: a `pending` loop with a live lease (its worker's first `run_maker` is still in
    flight - typically left behind, like the active case above, by a previous scheduler
    process across a restart) is likewise untracked in a fresh `runtime.workers`, and
    `_pending_loop_ids` only keeps `discover_loop_ids` from re-spawning a duplicate for the
    *same* Issue (#G10) - it has no effect on the cap used when spawning workers for *other*
    Issues. Such a loop is never eligible for respawn/attach itself (`should_restart` and
    `lc.attach()` both reject `pending`), but it still holds a real, live slot until it
    finishes or its lease expires (at which point `recover_orphaned_pending_loops` retires it
    and frees the slot for real). A `pending` loop whose lease has already expired is left out
    here on purpose: it is orphan-recovery material (`recover_orphaned_pending_loops`), not a
    live occupant of a slot.
    """
    live_active = {
        loop_id
        for loop_id in active_loop_ids(project_dir)
        if loop_id not in runtime.workers and not _is_lease_expired(loop_id, project_dir)
    }
    live_pending = {
        loop_id
        for loop_id in _pending_loop_ids(project_dir)
        if loop_id not in runtime.workers and not _is_lease_expired(loop_id, project_dir)
    }
    return live_active | live_pending


def _available_worker_slots(runtime: SchedulerRuntime, project_dir: str) -> int:
    """Return concurrency slots still free, counting tracked workers *and* untracked-live
    active/pending loops (SN1, extended by #I2 for `pending`).

    `respawn_orphaned_active_loops` and the cooldown-respawn path (`_respawn_expired_
    cooldowns`) previously computed availability from `concurrency_limit - len(runtime.
    workers)` alone - the exact same undercount `spawn_new_workers` used to have before
    `_untracked_live_active_loop_ids` was introduced for it (see that function's docstring).
    An untracked-but-live active loop (e.g. left running by a previous scheduler process
    across a restart) still occupies a real concurrency slot that neither of those two other
    respawn paths' naive calculation reflected, letting either spawn a worker past the
    configured cap whenever one was present. All three spawn/respawn paths now share this one
    occupancy calculation.
    """
    occupied = len(runtime.workers) + len(_untracked_live_active_loop_ids(runtime, project_dir))
    return concurrency_limit(project_dir) - occupied


def _recheck_repo_identity_before_respawn(
    loop_id: str,
    project_dir: str,
    expected_repo_identity_hash: str,
    runtime: SchedulerRuntime,
    state: lc.LoopState | None = None,
) -> bool:
    """Re-verify `loop_id`'s recorded repo-identity immediately before any respawn path
    (`respawn_orphaned_active_loops`, `_respawn_expired_cooldowns`, `reap_finished_workers`'s
    crash-restart branch) actually spawns a worker for it (J1).

    `verify_repo_identity_at_startup` only runs once, at scheduler startup. SN8 deliberately
    leaves a mismatched loop whose lease was still alive at that moment neither stopped nor
    tracked in `runtime.stopped_loop_ids` (see `_safe_stop_repo_identity_mismatch`'s own
    docstring) - the intent being it gets re-evaluated once the lease actually expires.
    But none of the three respawn paths re-ran the identity check on their own before this fix,
    so once that lease later expired mid-poll-loop, each would happily spawn a fresh
    `loop_driver.py` for a loop_id whose recorded repo-identity belongs to a different
    repository entirely. This reuses `_safe_stop_repo_identity_mismatch`'s own lease-aware
    stop/skip decision (and `_try_load_state`'s state (re)load, when the caller has not
    already loaded one) instead of duplicating either.

    Returns True when it is safe to respawn `loop_id` (repo identity matches, or the state
    could not be (re)loaded / already reached a terminal status - the caller's own subsequent
    handling covers that). Returns False when a mismatch was detected: the loop is either
    safety-stopped just now (lease already expired - `loop_id` is also added to
    `runtime.stopped_loop_ids` so later cycles stop reconsidering it) or left untouched for
    now (lease still alive - deferred to the next call, mirroring
    `verify_repo_identity_at_startup`'s own SN8 deferral).
    """
    if state is None:
        state = _try_load_state(lc.loop_dir(loop_id, project_dir), project_dir)
    if state is None or state.status in _NON_RESTARTABLE_STATUSES:
        return True
    if state.repo_identity_hash == expected_repo_identity_hash:
        return True
    if _safe_stop_repo_identity_mismatch(state, project_dir, expected_repo_identity_hash):
        runtime.stopped_loop_ids.add(loop_id)
    return False


def respawn_orphaned_active_loops(runtime: SchedulerRuntime, project_dir: str) -> list[str]:
    """Respawn active-status loops this process lost track of, e.g. after a restart (#F4).

    `discover_loop_ids` permanently excludes any loop_id in `active_loop_ids` (state.json
    status running/waiting_external) so discovery never regenerates an already-active loop.
    But `SchedulerRuntime.workers` is in-memory only: if the scheduler process itself
    restarts, `workers` starts empty, so a loop left running/waiting_external by the previous
    process becomes untracked *and* permanently invisible to discovery, with no path back to
    a worker actually being spawned for it. Only loops whose lease has actually expired are
    eligible here - a live lease means some owner (this process's own earlier-cycle child, or
    another host/process) still holds it, so respawning would create a duplicate worker.

    `stopped` (and `failed`) loops are never touched here because `active_loop_ids` only ever
    returns running/waiting_external, never a terminal status - so EV-51 (a safety-stopped
    loop is never auto-restarted) holds structurally, not via an extra check in this function.

    SN1: availability is computed via `_available_worker_slots` (tracked workers plus
    untracked-live active loops), not `concurrency_limit - len(runtime.workers)` alone - see
    that helper's docstring for why the naive count undercounts real occupancy.

    J1: `_recheck_repo_identity_before_respawn` re-verifies repo-identity immediately before
    respawning any loop_id here - see that helper's docstring for why the once-at-startup
    `verify_repo_identity_at_startup` check alone is insufficient for a loop whose lease was
    still alive at startup and only expires later, mid-poll-loop.
    """
    available = _available_worker_slots(runtime, project_dir)
    respawned: list[str] = []
    expected_repo_identity_hash: str | None = None
    for loop_id in active_loop_ids(project_dir):
        if available <= 0:
            break
        if loop_id in runtime.workers or loop_id in runtime.stopped_loop_ids:
            continue
        if loop_id in runtime.foreign_lease_cooldown_until:
            continue
        if not _is_lease_expired(loop_id, project_dir):
            continue
        if expected_repo_identity_hash is None:
            expected_repo_identity_hash = wm.resolve_repo_identity_hash(project_dir)
        if not _recheck_repo_identity_before_respawn(
            loop_id, project_dir, expected_repo_identity_hash, runtime
        ):
            continue
        runtime.workers[loop_id] = spawn_worker(loop_id, project_dir)
        respawned.append(loop_id)
        available -= 1
    return respawned


# Marker embedded in a retired `pending` loop's state-dir name (#H3/#H11). Real loop_ids are
# always `<repo-identity-hash>-issue-<N>` (see `worktree_manager.compute_loop_id`), which never
# contains this substring, so filtering on it cannot collide with a live loop_id. Defined in
# `loop_common.py` (as `ORPHANED_PENDING_MARKER`, SM1) so `loop_status.py` shares the same
# literal for purge-eligibility/display handling; aliased here under the historical private
# name to avoid rewriting every call site in this file.
_ORPHANED_PENDING_MARKER = lc.ORPHANED_PENDING_MARKER


def recover_orphaned_pending_loops(runtime: SchedulerRuntime, project_dir: str) -> list[str]:
    """Retire genuinely orphaned `pending` loops so their Issue can be discovered afresh
    (#H3/#H11).

    `should_restart("pending")` now refuses to respawn a `pending` loop (its worker never
    completed the first action, and `lc.attach()` rejects `pending` outright). But
    `discover_loop_ids` also permanently excludes any still-`pending` loop_id from discovery
    (#G10) - so, taken together, a `pending` loop whose worker died (or whose owning scheduler
    process itself restarted) had no path back at all: not respawned, not rediscovered,
    invisible forever even though its Issue still carries the label.

    This does not respawn a worker - `lc.attach()` would reject `pending` regardless, and a
    fresh worker cannot safely resume another worker's in-flight initial `run_maker` action.
    Instead, once the loop's lease has genuinely expired (no live owner could still complete
    it), the state dir is renamed aside to `<loop_id>.orphaned-<n>` under `.claude/loop/`
    (automating the Issue #205 manual runbook step of moving the stale dir out of the way and
    letting a fresh `start` reuse the Issue) and the loop's worktree is best-effort cleaned up
    (#I7, see `_retire_orphaned_pending_dir`) so the next `start` for the same Issue does not
    silently resume from whatever uncommitted/partial edits the dead Maker left behind. Renaming
    (not deleting) the state dir preserves the abandoned run's journal/state for post-mortem,
    while `wm.compute_loop_id` for the same Issue number resolves to the same original
    `loop_id`, whose directory no longer exists, so the next discovery cycle treats it as a
    brand-new candidate.

    Loops still tracked in `runtime.workers` (this process's own in-flight worker, whose
    `state.json` simply has not yet reflected the first completed action) are left untouched,
    as is any loop whose lease is still alive (another owner might still complete it).
    """
    root = lc.loop_root(project_dir)
    if not root.is_dir():
        return []
    recovered: list[str] = []
    for entry in sorted(root.iterdir()):
        if not entry.is_dir() or _ORPHANED_PENDING_MARKER in entry.name:
            continue
        loop_id = entry.name
        if loop_id in runtime.workers:
            continue
        state = _try_load_state(entry, project_dir)
        if state is None or state.status != "pending":
            continue
        if not _is_lease_expired(loop_id, project_dir):
            continue
        _retire_orphaned_pending_dir(entry, project_dir)
        recovered.append(loop_id)
    return recovered


def _retire_orphaned_pending_dir(entry: Path, project_dir: str) -> None:
    """Rename an orphaned-pending loop's state dir aside so discovery treats it as gone, and
    best-effort clean up its worktree (#I7).

    `worktree_manager.create_worktree` reuses an existing worktree directory on the expected
    branch as-is (never resets/cleans it) - without this cleanup, a dead Maker's uncommitted or
    partial edits would silently carry over into the fresh run this retirement is meant to
    enable, and could later be committed/pushed as if the new run authored them. Worktree
    removal is deliberately best-effort and never blocks retiring the state dir itself (that
    rename is what actually frees the Issue for rediscovery): a missing/already-removed
    worktree, or a `git worktree remove` failure, is only warned about.
    """
    root = entry.parent
    suffix = 1
    target = root / f"{entry.name}{_ORPHANED_PENDING_MARKER}{suffix}"
    while target.exists():
        suffix += 1
        target = root / f"{entry.name}{_ORPHANED_PENDING_MARKER}{suffix}"
    loop_id = entry.name
    entry.rename(target)
    print(
        lc.redact(f"loop_scheduler: recovered orphaned pending loop {loop_id} -> {target.name}"),
        file=sys.stderr,
    )
    _cleanup_orphaned_pending_worktree(loop_id, project_dir)


def _cleanup_orphaned_pending_worktree(loop_id: str, project_dir: str) -> None:
    """Best-effort removal of the worktree left behind by a retired orphaned-pending loop
    (#I7). Never raises: a cleanup failure must not block the state-dir retirement that already
    happened - it is only warned about here."""
    issue_number = lds.issue_number_from_loop_id(loop_id)
    if issue_number is None:
        return
    worktree_path = Path(wm.worktree_path_for(project_dir, issue_number))
    if not worktree_path.exists():
        return
    try:
        wm.remove_worktree(project_dir, issue_number, force=True)
    except wm.WorktreeError as exc:
        print(
            lc.redact(
                f"loop_scheduler: failed to clean up worktree for retired pending loop "
                f"{loop_id}: {exc}"
            ),
            file=sys.stderr,
        )


def reap_finished_workers(runtime: SchedulerRuntime, project_dir: str) -> list[str]:
    """Poll tracked workers; restart abnormal exits unless failed/stopped. Return respawned ids.

    SN6: dead workers are reaped (freeing their concurrency slots in `runtime.workers`) *before*
    `_respawn_expired_cooldowns` is checked, not after. Checking cooldowns first would compute
    `_respawn_expired_cooldowns`'s own concurrency-cap headroom against the still-stale
    `len(runtime.workers)` count - including workers that are about to be reaped by this very
    call - starving a cooldown-elapsed loop of a slot that is in fact freeing up in this same
    cycle, deferring its restart to (at least) the next poll interval instead.

    RH4: crash-restart candidates (the abnormal-exit, non-terminal, non-foreign-lease branch
    below) are collected into a list and spawned only *after* every finished worker has been
    popped from `runtime.workers` - not spawned immediately inline per finished worker as this
    used to do. Spawning immediately bypassed `_available_worker_slots` entirely: with cap=2,
    one dead worker + one live tracked worker + one untracked-but-live active loop (SN1) already
    fully occupies the cap, yet an inline immediate restart of the dead one would still spawn a
    third concurrent worker regardless. Restarts are now capped by the same shared
    `_available_worker_slots` occupancy calculation `_respawn_expired_cooldowns`,
    `respawn_orphaned_active_loops`, and `spawn_new_workers` already use; any candidate left over
    once slots run out is simply not restarted this cycle (its `state.json` status stays
    non-terminal, so it is picked up again - once its lease actually expires - by
    `respawn_orphaned_active_loops` on a later cycle instead of being lost).

    J1: `_recheck_repo_identity_before_respawn` re-verifies repo-identity immediately before
    restarting any crash-restart candidate below - see that helper's docstring for why the
    once-at-startup `verify_repo_identity_at_startup` check alone is insufficient here too.
    `restart_candidates` carries each candidate's already-loaded `state` along with its
    `loop_id` so the recheck does not need to reload state.json a second time.
    """
    finished = [loop_id for loop_id, proc in runtime.workers.items() if proc.poll() is not None]
    restart_candidates: list[tuple[str, lc.LoopState]] = []
    for loop_id in finished:
        proc = runtime.workers.pop(loop_id)
        if proc.returncode == 0 or loop_id in runtime.stopped_loop_ids:
            continue
        if proc.returncode == _EXIT_FOREIGN_LEASE:
            # The worker never reached `LoopDriver` (rejected at lease acquisition), so
            # `state.json.status` is still "running" (owned by whoever holds the live
            # lease). Respawning immediately every cycle would restart-storm until that
            # foreign lease's own TTL naturally expires; cool down instead.
            runtime.foreign_lease_cooldown_until[loop_id] = (
                time.monotonic() + lp2_lease_ttl_seconds(project_dir)
            )
            continue
        state = _try_load_state(lc.loop_dir(loop_id, project_dir), project_dir)
        if state is None or not should_restart(state.status):
            continue
        restart_candidates.append((loop_id, state))
    respawned: list[str] = []
    if restart_candidates:
        available = _available_worker_slots(runtime, project_dir)
        expected_repo_identity_hash: str | None = None
        for loop_id, state in restart_candidates:
            if available <= 0:
                break
            if expected_repo_identity_hash is None:
                expected_repo_identity_hash = wm.resolve_repo_identity_hash(project_dir)
            if not _recheck_repo_identity_before_respawn(
                loop_id, project_dir, expected_repo_identity_hash, runtime, state=state
            ):
                continue
            runtime.workers[loop_id] = spawn_worker(loop_id, project_dir)
            respawned.append(loop_id)
            available -= 1
    respawned.extend(_respawn_expired_cooldowns(runtime, project_dir))
    return respawned


def spawn_new_workers(
    runtime: SchedulerRuntime, project_dir: str, definition: ld.LoopDefinition
) -> list[str]:
    """Spawn newly discovered workers up to the concurrency cap (3.2 節).

    SN1: occupancy is computed via `_available_worker_slots`, which also counts
    `_untracked_live_active_loop_ids` - active loops with a live lease this process has not
    tracked in `runtime.workers` (e.g. left running by a previous scheduler process across a
    restart). `respawn_orphaned_active_loops` correctly does not touch them (their lease is
    still alive), so they never enter `runtime.workers`, but they are still real, live workers
    occupying a concurrency slot. Without counting them, `concurrency_limit -
    len(runtime.workers)` alone would undercount actual occupancy and spawn brand-new workers
    past the configured cap - the same undercount `_available_worker_slots` now also fixes for
    `respawn_orphaned_active_loops` and `_respawn_expired_cooldowns`.
    """
    available = _available_worker_slots(runtime, project_dir)
    if available <= 0:
        return []
    # #11: loop_ids mid-cooldown must also be excluded so discovery does not treat a
    # foreign-lease-rejected loop as a fresh candidate while it is waiting to be respawned.
    excluded = (
        runtime.stopped_loop_ids | set(runtime.workers) | set(runtime.foreign_lease_cooldown_until)
    )
    candidates = discover_loop_ids(project_dir, definition, excluded=excluded)
    spawned: list[str] = []
    for loop_id in candidates[:available]:
        runtime.workers[loop_id] = spawn_worker(loop_id, project_dir, definition.id)
        spawned.append(loop_id)
    return spawned


def run_cycle(runtime: SchedulerRuntime, project_dir: str, definition: ld.LoopDefinition) -> None:
    """One discovery -> cap check -> spawn / monitor / restart poll cycle.

    SN6: `reap_finished_workers` (which frees dead workers' slots, then respawns any
    cooldown-elapsed loop against the now-current slot count - see that function's docstring)
    runs first, ahead of `recover_orphaned_pending_loops` and `respawn_orphaned_active_loops`,
    so a slot a cooldown-elapsed loop is waiting on is never first handed to an unrelated
    recovered/orphaned-active loop instead.
    """
    reap_finished_workers(runtime, project_dir)
    # Must run before spawn_new_workers (#H3/#H11): retiring a stale `pending` state dir this
    # cycle lets discovery treat the same Issue as a fresh candidate in this same cycle,
    # instead of only on the next poll.
    recover_orphaned_pending_loops(runtime, project_dir)
    respawn_orphaned_active_loops(runtime, project_dir)
    spawn_new_workers(runtime, project_dir, definition)


# -- startup repo-identity verification (3.4 節: safety stop) ------------------------------------


def verify_repo_identity_at_startup(project_dir: str) -> list[str]:
    """Safety-stop any existing loop whose recorded repo-identity mismatches; return stopped ids.

    SN8: a mismatched loop whose lease is still alive is deliberately excluded from the
    returned list (see `_safe_stop_repo_identity_mismatch`) - it is neither stopped nor
    treated as already-handled, so it is re-evaluated on the next call (e.g. after the
    scheduler process restarts) once the lease has actually expired.
    """
    expected = wm.resolve_repo_identity_hash(project_dir)
    root = lc.loop_root(project_dir)
    if not root.is_dir():
        return []
    stopped: list[str] = []
    for entry in sorted(root.iterdir()):
        # A retired orphaned-pending dir (see `recover_orphaned_pending_loops`) still carries
        # the original `state.loop_id` inside its state.json, but its directory name has been
        # renamed aside with `_ORPHANED_PENDING_MARKER`. Without this filter,
        # `_safe_stop_repo_identity_mismatch(state, ...)` below would write a brand-new
        # `stopped` state.json at the *original* (no-suffix) loop_dir path - which no longer
        # exists - permanently orphaning both dirs: the original path becomes an unwanted
        # terminal state blocking Issue rediscovery, and the renamed dir is left untouched
        # (still `pending`, never cleaned up).
        if not entry.is_dir() or _ORPHANED_PENDING_MARKER in entry.name:
            continue
        state = _try_load_state(entry, project_dir)
        if state is None or state.status in _NON_RESTARTABLE_STATUSES:
            continue
        if state.repo_identity_hash == expected:
            continue
        if _safe_stop_repo_identity_mismatch(state, project_dir, expected):
            stopped.append(state.loop_id)
    return stopped


def _reload_for_safe_stop(
    state: lc.LoopState, project_dir: str, expected_repo_identity_hash: str
) -> lc.LoopState | None:
    """Re-load `state.loop_id`'s current state right after acquiring its coord lock (RH1).

    Return `None` whenever the stale, pre-lock `state` passed in must not be written through:
    the state dir vanished (purged), a purge tombstone now exists for it, its status already
    reached a terminal outcome, its `state_version` moved on (someone else wrote a newer state
    under this same coord lock in the meantime), or its repo-identity mismatch has since
    resolved itself. Otherwise return the freshly-reloaded state to write the stop onto.

    `verify_repo_identity_at_startup` necessarily reads `state` (the value passed in here)
    *before* acquiring this per-loop coord lock: the lock is keyed on `state.loop_id`, which is
    only known once state.json has already been read once. Between that read and the caller
    acquiring the lock, a concurrent `purge_loop` (RH3: tombstone-then-rmtree, both run under
    this very coord lock) can complete entirely - leaving a now-purged, tombstoned loop with no
    lock.json at all (`_is_lease_expired` returns True for a missing lock, so the existing
    lease-liveness check alone does not catch this). Writing the stale `state` through
    unconditionally at that point would resurrect a brand-new `stopped` state.json inside a
    directory `purge_loop`'s `rmtree` just deleted (`lc._write_state` recreates the parent dir
    via `_ensure_dir`), directly contradicting the tombstone that already marks this loop_id
    terminal/purged.
    """
    if state.loop_id in _tombstoned_loop_ids(project_dir):
        return None
    current = _try_load_state(lc.loop_dir(state.loop_id, project_dir), project_dir)
    if current is None:
        return None
    if current.status in _NON_RESTARTABLE_STATUSES:
        return None
    if current.state_version != state.state_version:
        return None
    if current.repo_identity_hash == expected_repo_identity_hash:
        return None
    return current


def _safe_stop_repo_identity_mismatch(
    state: lc.LoopState, project_dir: str, expected_repo_identity_hash: str
) -> bool:
    """Journal-first -> state -> mandatory macOS notify -> no Issue comment (3.4 節).
    Return True iff the stop was actually written.

    Written directly (not via `loop_driver_support.persist_safe_stop`) because the
    scheduler holds no lease for a loop it is refusing to touch precisely because the
    repository identity looks wrong; a foreign/stale lease token is not evidence this
    write is unsafe the way it is for the driver's own in-flight writes.

    SN8: this function does not itself fence its `state.json` write against a live
    lease (see above - it deliberately holds none). If `state.loop_id`'s lease is still
    alive, a detached worker legitimately owns it and would overwrite this unfenced
    `stopped` write with its own next in-flight persist moments later, silently
    reverting the safety-stop. Guard against that by skipping the write entirely while
    the lease is alive (logging a warning instead) - the loop is left untouched and
    excluded from the returned `stopped` set, so it is retried (not permanently
    swallowed) the next time `verify_repo_identity_at_startup` runs, by which point the
    worker will have exited or its lease will have expired and this write can no longer
    race a live owner.

    SN-flock: the lease check + write is additionally held under `lc.held_coord_lock` (a
    fixed, purge-independent path shared with `loop_status._purge_if_still_safe` and
    `loop_common.resume`/`reacquire_lease`, see their docstrings), so this write cannot race a
    concurrent purge of the same `loop_id` either (not just a live worker's own lease as
    covered above).

    RH1: `state` (the caller's pre-coord-lock read) is re-validated via `_reload_for_safe_stop`
    immediately after the lease-liveness check above, once this call actually holds the coord
    lock - see that helper's docstring for the stale-read race this closes. The rest of this
    function writes the freshly-reloaded state (not the stale `state` argument).
    """
    with lc.held_coord_lock(state.loop_id, project_dir):
        if not _is_lease_expired(state.loop_id, project_dir):
            print(
                lc.redact(
                    f"loop_scheduler: {state.loop_id} repo_identity_mismatch detected but its "
                    "lease is still held by a live worker; deferring safety-stop until the "
                    "lease expires"
                ),
                file=sys.stderr,
            )
            return False
        current = _reload_for_safe_stop(state, project_dir, expected_repo_identity_hash)
        if current is None:
            print(
                lc.redact(
                    f"loop_scheduler: {state.loop_id} repo_identity_mismatch stop skipped - its "
                    "state was purged, changed, or already resolved while waiting for the "
                    "coord lock"
                ),
                file=sys.stderr,
            )
            return False
        state = current
        lc.append_journal_event(
            state.loop_id,
            project_dir,
            "stopped",
            "scheduler",
            None,
            {"stop_reason": "repo_identity_mismatch"},
        )
        state.status = "stopped"
        state.stop_reason = "repo_identity_mismatch"
        state.pending_action = None
        state.state_version += 1
        state.updated_at = lc.now_iso()
        lc._write_state(state, project_dir)  # noqa: SLF001 - package-internal writer, see docstring
    lc.emit_loop_audit_event(
        "loop_stop",
        project_dir,
        {
            "loop_id": state.loop_id,
            "phase": state.phase,
            "final_status": "stopped",
            "stop_reason": "repo_identity_mismatch",
            "pr_number": state.pr_number,
        },
    )
    lds.notify_macos("loop-harness", lc.redact(f"{state.loop_id}: repo_identity_mismatch"))
    print(
        lc.redact(f"loop_scheduler: {state.loop_id} stopped (repo_identity_mismatch)"),
        file=sys.stderr,
    )
    return True


# -- single-instance guard (Issue #216: pidfile + flock, replaces regex-based pgrep liveness) --


def scheduler_pidfile_path(project_dir: str, definition_id: str = DEFAULT_DEFINITION_ID) -> Path:
    """Return the fixed pidfile path a resident scheduler flocks for the duration of its run
    (Issue #216), and the sole liveness signal `is_scheduler_alive`/the `is-alive` CLI
    subcommand probe against.

    Scoped per (project_dir, definition_id) - not per-project alone - matching J4's existing
    cron pgrep-pattern precedent: a project running multiple concurrent schedulers for
    different `--definition` values (or one non-default definition alongside the default) is
    an intentional, supported configuration, and each such scheduler must be guarded
    independently rather than mutually excluding each other.

    Uses `loop_common.loop_root` (root-worktree-resolved `.claude/loop/`) rather than a plain
    `Path(project_dir).resolve() / ".claude" / "loop"` (PR #230 Codex P1 fix): loop state
    (`state.json`/`journal.jsonl`/`coord.lock`, all addressed via `loop_root` too) always lives
    under the *root* worktree regardless of which worktree `--project` points at, per the
    repo's linked-worktree layout. A scheduler started with `--project <linked-worktree>` and
    one started with `--project <root-worktree>` therefore discover/spawn/monitor against the
    exact same shared state - so their single-instance guard must flock the exact same pidfile
    too, or two "different" schedulers (by pidfile) could concurrently drive one shared set of
    loops, breaking both the single-instance guarantee and the concurrency cap. The earlier
    plain-resolve choice optimized for avoiding an extra git subprocess call at
    render/probe/startup time, but that correctness gap outweighs the cost; every caller here -
    `run_scheduler`, `is_scheduler_alive`, and the rendered cron guard's own runtime `is-alive`
    invocation - now agrees on exactly one inode via this same resolution.

    `loop_root`/`resolve_root_worktree` fails closed (raises `RootResolutionError`) when git
    resolution itself fails (e.g. not a git repo, `git` unavailable) rather than falling back to
    an unverified guess; see `run_scheduler`'s and `is_scheduler_alive`'s docstrings for how
    each caller handles that.
    """
    if definition_id != DEFAULT_DEFINITION_ID:
        lc._validate_safe_id("definition_id", definition_id)  # noqa: SLF001 - reuse shared id-safety guard
    state_root = lc.loop_root(project_dir)
    if definition_id == DEFAULT_DEFINITION_ID:
        return state_root / "scheduler.pid"
    return state_root / f"scheduler.{definition_id}.pid"


def _acquire_scheduler_lock(project_dir: str, definition_id: str) -> Any:
    """Try to become the single resident scheduler for (project_dir, definition_id) by taking
    a non-blocking exclusive flock on `scheduler_pidfile_path` (Issue #216).

    Returns the open file handle on success - the caller MUST keep a reference to it for as
    long as this process is acting as the scheduler; the flock is released automatically by
    the kernel the moment the fd is closed or this process exits (including a crash), so no
    explicit unlock call is needed or attempted. Returns None if another live scheduler already
    holds the lock, in which case the caller must not proceed.

    This is the actual single-instance guarantee (the `is-alive` CLI probe below, and cron's
    `is-alive || fallback` guard, only avoid a redundant spawn attempt as an optimization): even
    if two schedulers were started concurrently (e.g. a manual start racing launchd's
    `KeepAlive` restart, or two cron ticks firing back to back), only one can ever win this
    flock - the loser calls this, gets None, and exits immediately without touching any loop
    state.
    """
    path = scheduler_pidfile_path(project_dir, definition_id)
    path.parent.mkdir(parents=True, exist_ok=True)
    fd = os.open(path, os.O_CREAT | os.O_RDWR, lc.FILE_MODE)
    handle = os.fdopen(fd, "r+", encoding="utf-8")
    try:
        fcntl.flock(handle.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
    except BlockingIOError:
        handle.close()
        return None
    handle.seek(0)
    handle.truncate()
    handle.write(json.dumps({"pid": os.getpid(), "started_at": lc.now_iso()}) + "\n")
    handle.flush()
    return handle


def is_scheduler_alive(project_dir: str, definition_id: str = DEFAULT_DEFINITION_ID) -> bool:
    """Probe whether a resident scheduler for (project_dir, definition_id) currently holds
    `scheduler_pidfile_path`'s flock (Issue #216) - the liveness check backing the `is-alive`
    CLI subcommand cron's restart guard now calls, replacing the old `pgrep -f <pattern>`
    regex-over-argv match (removed here; see `render_cron_entry`'s prior #13 self-match
    docstring for why that approach was structurally unreliable).

    Unlike a regex match over process command lines, this can never be fooled by an unrelated
    process - including the cron wrapper shell invoking this very probe - whose argv happens to
    contain matching text: the kernel enforces flock mutual exclusion directly against the same
    `_acquire_scheduler_lock` call a live scheduler takes at startup and holds for its entire
    lifetime, released automatically the instant that process exits or crashes (stale-pidfile-
    safe by construction - there is no separate pid-liveness check to go stale).

    Fail-closed design (PR #230 Codex P1 follow-up): if `scheduler_pidfile_path` cannot resolve
    the root worktree (`loop_common.RootResolutionError` - not a git repo, `git` unavailable,
    etc.), this returns `False` ("not alive") rather than raising. That is safe, not fail-open:
    the actual single-instance guarantee lives in `run_scheduler`/`_acquire_scheduler_lock`,
    which independently hits the exact same `RootResolutionError` on the exact same input and
    refuses to start (see its docstring) - so a `False` here only ever triggers a harmless
    fallback-spawn attempt that itself declines to start, instead of this probe crashing with a
    bare traceback on every cron tick.
    """
    try:
        path = scheduler_pidfile_path(project_dir, definition_id)
    except lc.RootResolutionError:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    fd = os.open(path, os.O_CREAT | os.O_RDWR, lc.FILE_MODE)
    try:
        fcntl.flock(fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
    except BlockingIOError:
        return True
    else:
        fcntl.flock(fd, fcntl.LOCK_UN)
        return False
    finally:
        os.close(fd)


# -- main poll loop --------------------------------------------------------------------------


def run_scheduler(
    project_dir: str,
    definition_id: str = DEFAULT_DEFINITION_ID,
    *,
    max_cycles: int | None = None,
) -> None:
    """Run the resident scheduler loop (forever unless max_cycles is given for tests).

    Refuses to start (Issue #216) when another live scheduler for the same
    (project_dir, definition_id) already holds `scheduler_pidfile_path`'s flock - see
    `_acquire_scheduler_lock`. This replaces the old cron-only, regex-based `pgrep -f
    <pattern>` liveness guard, whose self-match limitation (#13) meant a dead scheduler could
    be mistaken for a live one and never restarted; the pidfile/flock check here is enforced by
    the scheduler itself at startup, independent of which mechanism (cron, launchd, or a manual
    invocation) started it.

    Also refuses to start, fail-closed, if `scheduler_pidfile_path` cannot resolve the root
    worktree (`loop_common.RootResolutionError`, PR #230 Codex P1 follow-up: not a git repo,
    `git` unavailable, etc.). Proceeding anyway would mean running with no verified
    single-instance guard at all - silently reintroducing the exact double-start risk this
    Issue closes - so an unresolvable root worktree is treated the same as "another scheduler
    already holds the lock": log and exit without touching any loop state.
    """
    try:
        lock_handle = _acquire_scheduler_lock(project_dir, definition_id)
    except lc.RootResolutionError as exc:
        print(
            lc.redact(
                f"loop_scheduler: could not resolve the root worktree for {project_dir} "
                f"({exc}); refusing to start without a verified single-instance guard"
            ),
            file=sys.stderr,
        )
        return
    if lock_handle is None:
        print(
            lc.redact(
                f"loop_scheduler: a scheduler for definition {definition_id!r} is already "
                f"running in {project_dir}; exiting"
            ),
            file=sys.stderr,
        )
        return
    try:
        definition = ld.load_all_definitions(project_dir).get(definition_id)
        if definition is None:
            raise ld.DefinitionValidationError(f"loop definition not found: {definition_id}")
        runtime = SchedulerRuntime()
        runtime.stopped_loop_ids.update(verify_repo_identity_at_startup(project_dir))
        poll_interval = resolve_poll_interval(definition)
        cycles = 0
        while max_cycles is None or cycles < max_cycles:
            try:
                run_cycle(runtime, project_dir, definition)
            except Exception as exc:  # noqa: BLE001 - a resident poller must survive a bad cycle (#21)
                print(lc.redact(f"loop_scheduler: poll cycle failed: {exc}"), file=sys.stderr)
            cycles += 1
            if max_cycles is not None and cycles >= max_cycles:
                break
            time.sleep(poll_interval)
    finally:
        lock_handle.close()


# -- cron / launchd templates (3.5 節: template generation only, no auto-install) ----------------


def _project_slug(project_dir: str) -> str:
    """Return a short stable hash of project_dir, for a per-project-unique launchd label
    (#H16): multiple projects sharing the same `loop_scheduler.py` script path (e.g. installed
    from the same ai-orchestra package into different repos) must not collide on one fixed
    label - launchd treats the label as a unique job identifier, so a second project's
    `launchctl load` would either silently no-op or clobber the first project's job.
    """
    material = str(Path(project_dir).resolve())
    return hashlib.sha256(material.encode("utf-8")).hexdigest()[:12]


# RM3: any C0 control character other than TAB (#x9) and LF (#xA) - this deliberately also
# matches CR (#xD, 0x0D falls in the 0x0B-0x1F span below), see `_reject_launchd_unsafe_chars`.
_LAUNCHD_UNSAFE_CHARS_RE = re.compile(r"[\x00-\x08\x0b-\x1f]")


def _reject_launchd_unsafe_chars(value: str, field_name: str) -> None:
    """Fail closed (RM3) when a launchd-interpolated value contains CR or another control
    character XML 1.0 does not treat as plain, unchanged text.

    `render_launchd_plist` XML-escapes `&`/`<`/`>` (#12), but that alone does not cover control
    characters. A literal CR (`\\r`) is not illegal XML content, but XML 1.0 mandates line-ending
    normalization at parse time (CR, CRLF, and a lone CR are all folded to a single LF) - so a
    `project_dir`/script/interpreter/`--definition` value containing a literal CR would silently
    resolve to a *different* string the moment any XML parser (including launchd's own plist
    reader) reads this file back, with no error to signal the mismatch between what was
    rendered here and what launchd actually invokes. Any other C0 control character outside the
    small XML-1.0-legal set (TAB `#x9`, LF `#xA`, CR `#xD`) is not merely re-normalized but
    outright illegal XML 1.0 content, producing a plist no XML parser can parse at all.

    Neither failure mode has a character-level escape available at the plist-XML level (unlike
    `&`/`<`/`>`, which `xml_escape` already handles) - refusing to render is the only safe
    outcome here, mirroring `_reject_cron_unsafe_chars`'s CR/LF fail-closed precedent for
    `render_cron_entry`. A lone LF is intentionally *not* rejected here (unlike the cron guard,
    which fails closed on LF too): LF is XML-1.0-legal and passes through XML parsing completely
    unchanged - no normalization applies to it - so it carries neither of the two failure modes
    above.
    """
    if _LAUNCHD_UNSAFE_CHARS_RE.search(value):
        raise ValueError(
            f"{field_name} must not contain CR or other control characters for a launchd "
            f"plist: {value!r}"
        )


def render_launchd_plist(
    project_dir: str,
    script_path: Path | None = None,
    python_bin: str | None = None,
    definition_id: str = DEFAULT_DEFINITION_ID,
) -> str:
    """Render a launchd plist template for `--install-launchd`-style manual setup.

    Every interpolated path is XML-escaped (#12): an unescaped `&`/`<`/`>` in `project_dir`
    would otherwise produce invalid plist XML.

    Uses `sys.executable` rather than a hardcoded `/usr/bin/python3` (#G8): a launchd job
    started with the system interpreter cannot import a venv/uv-managed dependency the
    scheduler itself was actually installed under, so the resident job would die immediately
    on start. Mirrors the same fix already applied to `spawn_worker` (#F10).

    `--definition` is only appended when it differs from `DEFAULT_DEFINITION_ID` (#H15):
    without it, `--install-launchd`-generated jobs for a non-default loop definition would
    silently poll the wrong (default) definition's label/interval forever.

    The `Label` is suffixed with a hash of `project_dir` (#H16, see `_project_slug`) so
    multiple projects never collide on one fixed launchd job identifier.

    J6: the `Label` is additionally suffixed with `definition_id` whenever it differs from
    `DEFAULT_DEFINITION_ID`, mirroring J4's cron-guard fix. `launchd.plist(5)` requires `Label`
    to uniquely identify the job to launchd; without this, generating plists for both the
    default loop and a non-default `--definition` in the same project would produce two plists
    with identical labels (only `ProgramArguments` differs), and loading the second collides
    with the first - one definition's label queue silently never gets scheduled. The raw
    `definition_id` (not a hash/slug) is used as the suffix, same as it already appears
    verbatim in `--definition` within `ProgramArguments` below - it needs no extra
    sanitization beyond what this function already applies to it (the `_reject_launchd_unsafe_
    chars` control-character check above, plus `xml_escape` on the assembled `label` itself).

    The `ProgramArguments` command is wrapped in `/bin/sh -c 'mkdir -p ... && exec ...'` (#H17):
    `.claude/loop/` may not exist yet on a fresh checkout, and launchd's `StandardOutPath` /
    `StandardErrorPath` redirection fails outright (job never starts) if its parent directory
    is missing - unlike a shell's `>>` redirection, launchd does not create it. `exec` replaces
    the shell so the scheduler still becomes the tracked/`KeepAlive`-monitored process,
    matching a plain direct invocation for restart purposes.

    SN4: the in-template `mkdir -p` above is unlikely to actually help on its own - launchd
    opens `StandardOutPath`/`StandardErrorPath` for redirection *before* `ProgramArguments` is
    exec'd, so by the time `mkdir -p` in this wrapper shell runs, launchd may have already
    failed to open those paths. The log dir is therefore also (redundantly, but authoritatively)
    created eagerly by `main()`'s `print-launchd` handler at template-generation time - i.e. the
    log dir is expected to already exist by the time this plist is ever installed/loaded. The
    in-template `mkdir -p` is left in place as a harmless belt-and-suspenders guard (e.g. if the
    log dir is deleted after generation but before install).

    RM3: every interpolated value (`script`/`project`/`python`/`definition_id`) is also
    rejected outright (`ValueError`) if it contains a literal CR or any other XML-1.0-illegal
    control character - see `_reject_launchd_unsafe_chars` for why `xml_escape` alone (which
    only covers `&`/`<`/`>`) does not protect against those. This mirrors
    `render_cron_entry`'s SN-cron CR/LF fail-closed guard, applied to launchd's XML format
    instead of crontab's line-oriented one.

    Issue #216: unlike `render_cron_entry`, this template has never needed a pgrep-style
    liveness guard of its own - `KeepAlive: true` already restarts a scheduler that exits or
    crashes, and a duplicate resident (e.g. a manual invocation started alongside an
    already-loaded launchd job) is now rejected by the scheduler's own startup flock in
    `run_scheduler`/`_acquire_scheduler_lock`, independent of which mechanism started it.
    """
    script = str(script_path or _SCRIPT_DIR / "loop_scheduler.py")
    project = str(Path(project_dir).resolve())
    python = str(python_bin or sys.executable)
    for value, field_name in (
        (script, "script_path"),
        (project, "project_dir"),
        (python, "python_bin"),
        (definition_id, "definition_id"),
    ):
        _reject_launchd_unsafe_chars(value, field_name)
    log_dir = f"{project}/.claude/loop"
    stdout_log = f"{log_dir}/scheduler.stdout.log"
    stderr_log = f"{log_dir}/scheduler.stderr.log"
    label = f"com.ai-orchestra.loop-scheduler.{_project_slug(project)}"
    definition_args = ""
    if definition_id != DEFAULT_DEFINITION_ID:
        definition_args = f" --definition {shlex.quote(definition_id)}"
        # J6: keep the label unique per non-default definition too - see docstring above.
        label += f".{definition_id}"
    exec_command = (
        f"mkdir -p {shlex.quote(log_dir)} && exec {shlex.quote(python)} {shlex.quote(script)} "
        f"--project {shlex.quote(project)}{definition_args}"
    )
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" '
        '"http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n'
        '<plist version="1.0">\n'
        "<dict>\n"
        "  <key>Label</key>\n"
        f"  <string>{xml_escape(label)}</string>\n"
        "  <key>ProgramArguments</key>\n"
        "  <array>\n"
        "    <string>/bin/sh</string>\n"
        "    <string>-c</string>\n"
        f"    <string>{xml_escape(exec_command)}</string>\n"
        "  </array>\n"
        "  <key>RunAtLoad</key>\n"
        "  <true/>\n"
        "  <key>KeepAlive</key>\n"
        "  <true/>\n"
        "  <key>StandardOutPath</key>\n"
        f"  <string>{xml_escape(stdout_log)}</string>\n"
        "  <key>StandardErrorPath</key>\n"
        f"  <string>{xml_escape(stderr_log)}</string>\n"
        "</dict>\n"
        "</plist>\n"
    )


def _reject_cron_unsafe_chars(value: str, field_name: str) -> None:
    """Fail closed (SN-cron) when a cron-interpolated value contains a literal CR/LF.

    See `render_cron_entry`'s SN-cron docstring note for why this cannot be escaped away the
    way `%` is (SN7) and must instead refuse to render at all.
    """
    if "\n" in value or "\r" in value:
        raise ValueError(f"{field_name} must not contain CR/LF for a cron entry: {value!r}")


def render_cron_entry(
    project_dir: str,
    script_path: Path | None = None,
    python_bin: str | None = None,
    definition_id: str = DEFAULT_DEFINITION_ID,
) -> str:
    """Render a cron entry template: an `is-alive` pidfile/flock probe restarts the scheduler
    if it died (Issue #216).

    Every interpolated path is shell-quoted individually (#12): an unescaped `project_dir`
    containing whitespace or shell metacharacters (`;`, `|`, `&`, ...) would otherwise split
    into extra tokens or inject additional commands into the crontab line.

    Uses `sys.executable` rather than a hardcoded `/usr/bin/python3` (#G8), matching the same
    fix in `render_launchd_plist` and `spawn_worker` (#F10): cron's own minimal environment
    would otherwise invoke a system interpreter that cannot import a venv/uv-managed
    dependency the scheduler was actually installed under.

    `--definition` is only appended when it differs from `DEFAULT_DEFINITION_ID` (#H15),
    mirroring `render_launchd_plist`: otherwise a cron-restarted scheduler for a non-default
    loop definition would silently fall back to polling the default definition's label.

    The cron line is prefixed with `mkdir -p <log dir> &&` (#H17): `.claude/loop/` may not
    exist yet on a fresh checkout, and the shell's `>> ... 2>&1` redirection at the end of this
    line fails outright (whole command errors out, scheduler never starts) if its parent
    directory is missing.

    Issue #216 (supersedes #13's `pgrep -f <pattern>` self-match guard and J4's matching
    definition-id-in-pattern fix, both removed here): the liveness guard is now
    `<script> --project <project>[--definition <id>] is-alive` (see `is_scheduler_alive`),
    which flocks the exact same `scheduler_pidfile_path` a live scheduler holds for its entire
    run - not a regex over process command lines. This closes the old self-match failure mode
    structurally rather than by best-effort PID exclusion: a `pgrep -f` pattern could always
    coincidentally match the cron wrapper shell's own argv (which literally contains the
    fallback command's text a second time), making a dead scheduler look alive forever and
    permanently skip the restart. `is-alive`'s exit code depends only on whether the flock is
    actually held, so it cannot self-match. Both the `is-alive` probe and the fallback spawn
    share the same `--project`/`--definition` argument construction (`project_args`) as a
    single source of truth, so there is no separate pattern to keep in sync with the fallback
    command the way the old `pgrep_pattern` was.

    Every literal `%` in the assembled line is escaped to `\\%` (SN7): `crontab` treats an
    unescaped `%` as a newline at the crontab-file-parsing stage, *before* the shell ever
    sees the line - splitting the command there (and feeding the remainder to the command's
    stdin) regardless of any `shlex.quote` shell-quoting already applied. A `project_dir`
    containing a literal `%` (a legal filesystem-path character) would otherwise silently
    truncate this cron entry into a broken, partially-executed command.

    SN-cron: a literal CR/LF in any interpolated value fails closed (`ValueError`) instead of
    being rendered. `shlex.quote` only protects *shell* word-splitting/metacharacters within
    the assembled line, and (unlike `%`, fixed above by SN7's escape) an embedded CR/LF cannot
    be escaped away at the crontab-file level either - crontab treats a raw newline in a field
    value as its own line terminator at the file-parsing stage, splitting one intended cron
    entry into two (a malformed second "command"), regardless of any quoting applied to the
    line's text. Since there is no crontab-level escape for this (unlike `%`), refusing to
    render is the only safe outcome for a `project_dir`/script/interpreter path containing one
    (CR/LF is technically legal in a POSIX filename, if vanishingly rare in practice).
    """
    script = str(script_path or _SCRIPT_DIR / "loop_scheduler.py")
    project = str(Path(project_dir).resolve())
    python = str(python_bin or sys.executable)
    for value, field_name in (
        (script, "script_path"),
        (project, "project_dir"),
        (python, "python_bin"),
        (definition_id, "definition_id"),
    ):
        _reject_cron_unsafe_chars(value, field_name)
    log_dir = f"{project}/.claude/loop"
    log_path = f"{log_dir}/scheduler.log"
    definition_args = ""
    if definition_id != DEFAULT_DEFINITION_ID:
        definition_args = f" --definition {shlex.quote(definition_id)}"
    project_args = f"--project {shlex.quote(project)}{definition_args}"
    is_alive_command = f"{shlex.quote(python)} {shlex.quote(script)} {project_args} is-alive"
    fallback_command = (
        f"{shlex.quote(python)} {shlex.quote(script)} {project_args} >> "
        f"{shlex.quote(log_path)} 2>&1"
    )
    line = (
        f"*/5 * * * * mkdir -p {shlex.quote(log_dir)} && {is_alive_command} || {fallback_command}\n"
    )
    return line.replace("%", "\\%")


if __name__ == "__main__":
    sys.exit(main())
