"""Context テンプレートの生成・検証・同期を担当する Mixin。"""

from __future__ import annotations

import datetime
import os
import re
import stat
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any, NamedTuple, Protocol


@dataclass(frozen=True)
class ContextSpecEntry:
    name: str
    source_rels: tuple[str, ...]
    managed_rels: tuple[str, ...]
    template_rel: str
    project_rel: str
    required_pkg: str | None


class _SyncOutcome(NamedTuple):
    ok: bool
    changed: bool


class _MalformedManagedBlockError(Exception):
    pass


class _ContextHost(Protocol):
    """ContextMixin が利用側に要求するインターフェース。"""

    orchestra_dir: Path
    CONTEXT_SPECS: tuple[ContextSpecEntry, ...]

    def get_project_dir(self, project: str | None) -> Path: ...
    def load_orchestra_json(self, project_dir: Path) -> dict[str, Any]: ...


class ContextMixin:
    """OrchestraManager に context 管理機能を提供する Mixin。

    利用側は _ContextHost Protocol を満たすこと。
    """

    # Protocol で宣言した属性を型チェッカーに認識させる
    orchestra_dir: Path
    CONTEXT_SPECS: tuple[ContextSpecEntry, ...]

    MANAGED_BLOCK_BEGIN = (
        "<!-- BEGIN ai-orchestra: managed by `orchex context sync` "
        "(edits inside this block are overwritten) -->"
    )
    MANAGED_BLOCK_END = "<!-- END ai-orchestra -->"
    GENERATED_MARKER = "<!-- DO NOT EDIT: generated by `orchex context build` -->"
    LEGACY_CONTEXT_FILES = (".gemini/GEMINI.md", "CLAUDE.md")
    SHADOWING_CLAUDE_FILENAMES = ("CLAUDE.md", ".claude/CLAUDE.md", "CLAUDE.local.md")

    SEVERITY_MARKER_PATTERN = re.compile(
        r"^[ \t]*<!-- severity-definitions: output-contracts/([A-Za-z0-9_-]+) -->[ \t]*$",
        re.MULTILINE,
    )
    SEVERITY_MARKER_CANDIDATE_PATTERN = re.compile(r"<!--.*severity-definitions")
    SEVERITY_SECTION_HEADING = "## 重要度の定義"
    SECTION_BOUNDARY_PATTERN = re.compile(r"^#{1,2} ")
    TABLE_SEPARATOR_CELL_PATTERN = re.compile(r":?-+:?")
    UNESCAPED_PIPE_PATTERN = re.compile(r"(?<!\\)\|")
    FENCE_LINE_PATTERN = re.compile(r"^ {0,3}(`{3,}|~{3,})")
    MAX_BACKUP_NAME_ATTEMPTS = 100

    def get_project_dir(self, project: str | None) -> Path: ...

    def _load_context_file(self, path: Path) -> str:
        """context テンプレートファイルを読み込む（存在しなければ終了）。"""
        if not path.exists():
            print(f"エラー: context テンプレートが見つかりません: {path}", file=sys.stderr)
            sys.exit(1)
        try:
            return path.read_text(encoding="utf-8").strip()
        except OSError as e:
            print(
                f"エラー: context テンプレートの読み込みに失敗: {path} ({e})",
                file=sys.stderr,
            )
            sys.exit(1)

    def _render_fragment_group(self, rels: tuple[str, ...], joiner: str) -> str:
        """templates/context の断片を展開して連結する。"""
        expanded_contents: list[str] = []
        for rel in rels:
            source_path = self.orchestra_dir / "templates" / "context" / rel
            source_content = self._load_context_file(source_path)
            expanded_content, _ = self._expand_severity_definitions(source_content, source_path)
            expanded_contents.append(expanded_content)
        return joiner.join(expanded_contents)

    def _build_managed_block(self, body: str, nl: str = "\n") -> str:
        """管理対象の本文を境界マーカーで囲む。"""
        normalized_body = body.replace("\r\n", "\n").replace("\r", "\n")
        if nl != "\n":
            normalized_body = normalized_body.replace("\n", nl)
        return nl.join([self.MANAGED_BLOCK_BEGIN, "", normalized_body, "", self.MANAGED_BLOCK_END])

    def _render_context_content(
        self,
        source_rels: tuple[str, ...],
        managed_rels: tuple[str, ...],
    ) -> str:
        """templates/context の断片から1つの文書を生成する。"""
        source_content = self._render_fragment_group(source_rels, "\n\n---\n\n").rstrip("\n")
        if not managed_rels:
            return source_content + "\n"

        managed_body = self._render_fragment_group(managed_rels, "\n\n")
        managed_block = self._build_managed_block(managed_body, nl="\n")
        return source_content + "\n\n" + managed_block + "\n"

    def _expand_severity_definitions(
        self, content: str, source_path: Path
    ) -> tuple[str, list[str]]:
        """重要度定義マーカーを facet 由来の箇条書きへ展開する。"""
        self._validate_severity_markers(content, source_path)
        facet_names: list[str] = []
        expansions: dict[str, str] = {}

        def replace_marker(match: re.Match[str]) -> str:
            name = match.group(1)
            if name not in expansions:
                facet_names.append(name)
                expansions[name] = self._load_severity_expansion(name)
            return expansions[name]

        expanded = self.SEVERITY_MARKER_PATTERN.sub(replace_marker, content)
        return expanded, facet_names

    def _validate_severity_markers(self, content: str, source_path: Path) -> None:
        """不正な重要度定義マーカーを検出して終了する。"""
        for line in content.splitlines():
            if not self.SEVERITY_MARKER_CANDIDATE_PATTERN.search(line):
                continue
            if self.SEVERITY_MARKER_PATTERN.fullmatch(line):
                continue
            print(
                f"エラー: severity-definitions マーカーが不正です ({line}): {source_path}",
                file=sys.stderr,
            )
            sys.exit(1)

    def _load_severity_expansion(self, name: str) -> str:
        """output-contract facet から重要度定義の箇条書きを組み立てる。"""
        facet_path = self.orchestra_dir / "facets" / "output-contracts" / f"{name}.md"
        content = self._load_severity_facet(facet_path)
        section_lines = self._extract_severity_section(content, facet_path)
        severity_lines = self._extract_severity_lines(section_lines, facet_path)
        return "\n".join(severity_lines)

    def _load_severity_facet(self, facet_path: Path) -> str:
        """重要度定義を持つ facet ファイルを読み込む。"""
        if not facet_path.exists():
            print(f"エラー: 重要度 facet が見つかりません: {facet_path}", file=sys.stderr)
            sys.exit(1)
        try:
            return facet_path.read_text(encoding="utf-8")
        except OSError as e:
            print(
                f"エラー: 重要度 facet の読み込みに失敗: {facet_path} ({e})",
                file=sys.stderr,
            )
            sys.exit(1)

    def _extract_severity_section(self, content: str, facet_path: Path) -> list[str]:
        """重要度の定義セクション本文を抽出する。"""
        lines = content.splitlines()
        try:
            heading_index = lines.index(self.SEVERITY_SECTION_HEADING)
        except ValueError:
            print(
                f"エラー: 重要度の定義セクションが見つかりません: {facet_path}",
                file=sys.stderr,
            )
            sys.exit(1)

        section_lines: list[str] = []
        for line in lines[heading_index + 1 :]:
            if self.SECTION_BOUNDARY_PATTERN.match(line):
                break
            section_lines.append(line)
        return section_lines

    def _extract_severity_lines(self, section_lines: list[str], facet_path: Path) -> list[str]:
        """セクション内の最初の表から重要度行を抽出する。"""
        table_start = self._find_markdown_table_start(section_lines)
        severity_lines: list[str] = []
        if table_start is not None:
            for row in section_lines[table_start + 2 :]:
                if not self._is_markdown_table_row(row):
                    break
                severity_lines.append(self._format_severity_row(row, facet_path))

        if severity_lines:
            return severity_lines
        print(f"エラー: 重要度の定義テーブルにデータ行がありません: {facet_path}", file=sys.stderr)
        sys.exit(1)

    def _find_markdown_table_start(self, lines: list[str]) -> int | None:
        """最初の Markdown 表のヘッダー行位置を返す。"""
        for index in range(len(lines) - 1):
            if not self._is_markdown_table_row(lines[index]):
                continue
            if self._is_markdown_table_separator(lines[index + 1]):
                return index
        return None

    @staticmethod
    def _is_markdown_table_row(line: str) -> bool:
        """行が両端にパイプを持つ Markdown 表形式か判定する。"""
        stripped = line.strip()
        return stripped.startswith("|") and stripped.endswith("|")

    def _is_markdown_table_separator(self, line: str) -> bool:
        """行が Markdown 表の区切り行か判定する。"""
        if not self._is_markdown_table_row(line):
            return False
        cells = self._split_markdown_table_row(line)
        return bool(cells) and all(
            self.TABLE_SEPARATOR_CELL_PATTERN.fullmatch(cell) for cell in cells
        )

    @staticmethod
    def _split_markdown_table_row(row: str) -> list[str]:
        """Markdown 表の行を空白除去済みセルへ分割する（エスケープされた `\\|` は分割しない）。"""
        inner = row.strip()[1:-1]
        cells = ContextMixin.UNESCAPED_PIPE_PATTERN.split(inner)
        return [cell.strip().replace("\\|", "|") for cell in cells]

    def _format_severity_row(self, row: str, facet_path: Path) -> str:
        """重要度表の1行を Codex 向け箇条書きへ変換する。"""
        cells = self._split_markdown_table_row(row)
        if len(cells) < 2:
            print(
                f"エラー: 重要度の定義テーブルの列が不足しています ({row}): {facet_path}",
                file=sys.stderr,
            )
            sys.exit(1)
        severity = cells[0]
        if severity.startswith("**") and severity.endswith("**"):
            severity = severity[2:-2]
        return f"  - {severity}: {cells[1]}"

    def _update_file_if_needed(
        self,
        path: Path,
        content: str,
        label: str,
        dry_run: bool = False,
    ) -> bool:
        """差分がある場合のみファイルを更新する。"""
        existing: str | None = None
        if path.exists():
            try:
                existing = path.read_text(encoding="utf-8")
            except OSError:
                existing = None

        if existing == content:
            print(f"スキップ（差分なし）: {label}")
            return False

        if dry_run:
            print(f"[DRY-RUN] 更新: {label}")
            return True

        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"更新: {label}")
        return True

    def context_build(self, dry_run: bool = False) -> int:
        """templates/context から配布テンプレートを再生成する。"""
        changed = 0
        for spec in self.CONTEXT_SPECS:
            dst = self.orchestra_dir / spec.template_rel
            content = self._render_context_content(spec.source_rels, spec.managed_rels)
            label = str(dst.relative_to(self.orchestra_dir))
            if self._update_file_if_needed(dst, content, label, dry_run=dry_run):
                changed += 1

        if changed == 0:
            print("context build: 差分なし")
        return changed

    def context_check(self) -> bool:
        """templates/context 由来の生成結果とテンプレートの一致を検証する。"""
        mismatches: list[str] = []

        for spec in self.CONTEXT_SPECS:
            expected = self._render_context_content(spec.source_rels, spec.managed_rels)
            target = self.orchestra_dir / spec.template_rel
            label = str(target.relative_to(self.orchestra_dir))

            if not target.exists():
                mismatches.append(f"{label} (missing)")
                continue

            try:
                actual = target.read_text(encoding="utf-8")
            except OSError:
                mismatches.append(f"{label} (unreadable)")
                continue

            if actual != expected:
                mismatches.append(f"{label} (outdated)")

        if not mismatches:
            print("context check: OK")
            return True

        print("context check: NG")
        print("不一致ファイル:")
        for item in mismatches:
            print(f"- {item}")
        print("実行コマンド: orchex context build")
        return False

    def context_sync(self, project: str | None, dry_run: bool = False, force: bool = False) -> int:
        """生成済み context をプロジェクトのトップレベル文書へ同期する。"""
        project_dir = self.get_project_dir(project)
        project_root = project_dir.resolve()
        orch = self.load_orchestra_json(project_dir)
        installed_packages = set(orch.get("installed_packages", []))

        changed = 0
        core_required_seen = False
        core_ok = True
        for spec in self.CONTEXT_SPECS:
            if spec.required_pkg is not None and spec.required_pkg not in installed_packages:
                continue
            dst = project_dir / spec.project_rel
            outcome = self._sync_context_spec_dst(
                spec, dst, project_dir, project_root, dry_run, force
            )
            changed += 1 if outcome.changed else 0
            if spec.required_pkg is None:
                core_required_seen = True
                core_ok = core_ok and outcome.ok

        allow_claude_md_delete = core_ok if core_required_seen else False
        removed_or_pending, suppressed_paths = self._cleanup_legacy_context_files(
            project_dir,
            project_root,
            dry_run=dry_run,
            allow_claude_md_delete=allow_claude_md_delete,
        )
        changed += len(removed_or_pending)
        self._warn_shadowing_claude_files(project_dir, project_root, suppressed_paths)

        if changed == 0:
            print("context sync: 差分なし")
        return changed

    def _sync_context_spec_dst(
        self,
        spec: ContextSpecEntry,
        dst: Path,
        project_dir: Path,
        project_root: Path,
        dry_run: bool,
        force: bool,
    ) -> _SyncOutcome:
        """1つの context spec を配布先へ安全に同期する。"""
        label = spec.project_rel
        if dst.is_symlink():
            print(f"スキップ（安全性）: {label} (symlink)")
            return _SyncOutcome(False, False)
        try:
            dst_parent_resolved = dst.parent.resolve()
        except OSError:
            print(f"スキップ（安全性）: {label} (parent unreadable)")
            return _SyncOutcome(False, False)
        try:
            dst_parent_resolved.relative_to(project_root)
        except ValueError:
            print(f"スキップ（安全性）: {label} (outside project)")
            return _SyncOutcome(False, False)

        if dst.exists() and dst.is_dir():
            print(f"警告: ディレクトリのためスキップ: {label}", file=sys.stderr)
            return _SyncOutcome(False, False)

        full_render = self._render_context_content(spec.source_rels, spec.managed_rels)
        created = not dst.exists()
        if created or force:
            return self._write_full_context(dst, full_render, label, dry_run, created, project_dir)

        try:
            existing = self._read_text_keep_newlines(dst)
        except (OSError, UnicodeDecodeError) as e:
            print(
                f"警告: 読み込みに失敗したためスキップ: {label} ({e})",
                file=sys.stderr,
            )
            return _SyncOutcome(False, False)

        if existing.strip() == "":
            return self._write_full_context(dst, full_render, label, dry_run, True, project_dir)

        if self._first_line_is_generated_marker(existing):
            if dry_run:
                print(f"[DRY-RUN] 更新（旧生成物を移行、バックアップ後）: {label}")
                return _SyncOutcome(True, True)
            backup_path = self._backup_legacy_file(project_dir, label, dst)
            if backup_path is None:
                print(f"警告: バックアップに失敗したためスキップ: {label}", file=sys.stderr)
                return _SyncOutcome(False, False)
            self._atomic_write_text(dst, full_render)
            print(f"バックアップ: {backup_path.relative_to(project_dir)}")
            print(f"更新（旧生成物を移行）: {label}")
            return _SyncOutcome(True, True)

        if not spec.managed_rels:
            print(f"スキップ（既存）: {label}")
            return _SyncOutcome(True, False)

        return self._merge_managed_block(dst, existing, spec.managed_rels, label, dry_run)

    @staticmethod
    def _read_text_keep_newlines(path: Path) -> str:
        """改行コードを変換せずに読む（Path.read_text の newline 引数は 3.13 以降のため使わない）。"""
        with path.open(encoding="utf-8", newline="") as source:
            return source.read()

    def _write_full_context(
        self,
        dst: Path,
        content: str,
        label: str,
        dry_run: bool,
        created: bool,
        project_dir: Path,
    ) -> _SyncOutcome:
        """context 全体を差分がある場合だけ書き込む。既存ファイルを force で上書きする場合は先にバックアップする。"""
        existing: str | None = None
        if dst.exists():
            try:
                existing = self._read_text_keep_newlines(dst)
            except (OSError, UnicodeDecodeError):
                existing = None

        if existing == content:
            print(f"スキップ（差分なし）: {label}")
            return _SyncOutcome(True, False)

        verb = "作成" if created else "更新"
        if dry_run:
            print(f"[DRY-RUN] {verb}: {label}")
            return _SyncOutcome(True, True)

        if not created:
            backup_path = self._backup_legacy_file(project_dir, label, dst)
            if backup_path is None:
                print(f"警告: バックアップに失敗したためスキップ: {label}", file=sys.stderr)
                return _SyncOutcome(False, False)
            print(f"バックアップ: {backup_path.relative_to(project_dir)}")

        self._atomic_write_text(dst, content)
        print(f"{verb}: {label}")
        return _SyncOutcome(True, True)

    def _first_line_is_generated_marker(self, content: str) -> bool:
        """先頭行（BOM・末尾の空白/\r を除く）が GENERATED_MARKER と一致するかを判定する。"""
        first_line = content.split("\n", 1)[0]
        first_line = first_line.lstrip("﻿").rstrip()
        return first_line == self.GENERATED_MARKER

    def _backup_legacy_file(self, project_dir: Path, rel: str, src_path: Path) -> Path | None:
        """旧 context ファイルのバイト列を退避する。"""
        try:
            content = src_path.read_bytes()
        except OSError:
            return None

        backup_dir = project_dir / ".claude" / "state" / "legacy-context"
        if not self._is_safe_backup_dir(project_dir, backup_dir):
            print(
                f"警告: 退避先がプロジェクト外を指すため使えません: {backup_dir}", file=sys.stderr
            )
            return None

        timestamp = datetime.datetime.now(datetime.UTC).strftime("%Y%m%dT%H%M%S%fZ")
        stem = f"{rel.replace('/', '__')}.{timestamp}"
        for attempt in range(self.MAX_BACKUP_NAME_ATTEMPTS):
            suffix = "" if attempt == 0 else f".{attempt}"
            backup_path = backup_dir / f"{stem}{suffix}.bak"
            try:
                with backup_path.open("xb") as backup_file:
                    backup_file.write(content)
            except FileExistsError:
                continue
            except OSError:
                return None
            return backup_path
        return None

    def _is_safe_backup_dir(self, project_dir: Path, backup_dir: Path) -> bool:
        """退避先を作成し、symlink を経由せずプロジェクト内にあるかを確かめる。"""
        project_root = project_dir.resolve()
        for part in (backup_dir.parent.parent, backup_dir.parent, backup_dir):
            if part.is_symlink():
                return False
        try:
            backup_dir.mkdir(parents=True, exist_ok=True)
            backup_dir.resolve().relative_to(project_root)
        except (OSError, ValueError):
            return False
        return True

    def _splice_managed_block(self, existing: str, managed_body: str) -> tuple[str, str]:
        """管理ブロックを追記または置換し、変更種別とともに返す。"""
        plain_lines = existing.splitlines()
        fenced_indices = self._fenced_line_indices(plain_lines)
        begin_indices = [
            index
            for index, line in enumerate(plain_lines)
            if index not in fenced_indices and line.rstrip() == self.MANAGED_BLOCK_BEGIN
        ]
        end_indices = [
            index
            for index, line in enumerate(plain_lines)
            if index not in fenced_indices and line.rstrip() == self.MANAGED_BLOCK_END
        ]

        nl = "\r\n" if "\r\n" in existing else "\n"
        block = self._build_managed_block(managed_body, nl=nl)
        if not begin_indices and not end_indices:
            base = existing.rstrip("\r\n")
            if base == "":
                new_content = block + nl
            else:
                new_content = base + nl + nl + block + nl
            return new_content, "append"

        if len(begin_indices) == 1 and len(end_indices) == 1 and begin_indices[0] < end_indices[0]:
            begin_index = begin_indices[0]
            end_index = end_indices[0]
            raw_lines = existing.splitlines(keepends=True)
            offsets = [0]
            for raw_line in raw_lines:
                offsets.append(offsets[-1] + len(raw_line))
            begin_char = offsets[begin_index]
            end_char = offsets[end_index + 1]
            if raw_lines[end_index].endswith("\r\n"):
                end_terminator = "\r\n"
            elif raw_lines[end_index].endswith("\n"):
                end_terminator = "\n"
            else:
                end_terminator = ""
            new_content = existing[:begin_char] + block + end_terminator + existing[end_char:]
            return new_content, "replace"

        raise _MalformedManagedBlockError

    def _fenced_line_indices(self, lines: list[str]) -> set[int]:
        """``` / ~~~ フェンス内側の行インデックス集合を返す（フェンス行自体は含まない）。

        閉じフェンスは開始と同じ文字で、開始以上の長さを持ち、後ろに空白しか無い行に限る。
        """
        fenced: set[int] = set()
        open_fence: str | None = None
        for index, line in enumerate(lines):
            match = self.FENCE_LINE_PATTERN.match(line)
            if open_fence is None:
                if match:
                    open_fence = match.group(1)
                continue
            if match and self._closes_fence(line, match.group(1), open_fence):
                open_fence = None
                continue
            fenced.add(index)
        return fenced

    @staticmethod
    def _closes_fence(line: str, fence: str, open_fence: str) -> bool:
        """フェンス行が開いているフェンスを閉じるか判定する。"""
        if fence[0] != open_fence[0] or len(fence) < len(open_fence):
            return False
        return line.strip() == fence

    def _merge_managed_block(
        self,
        dst: Path,
        existing: str,
        managed_rels: tuple[str, ...],
        label: str,
        dry_run: bool,
    ) -> _SyncOutcome:
        """既存文書のプロジェクト記述を保ち、管理ブロックだけを反映する。"""
        managed_body = self._render_fragment_group(managed_rels, "\n\n")
        try:
            new_content, kind = self._splice_managed_block(existing, managed_body)
        except _MalformedManagedBlockError:
            print(
                f"警告: 管理ブロックの形式が不正なためスキップ: {label}",
                file=sys.stderr,
            )
            return _SyncOutcome(False, False)

        if new_content == existing:
            print(f"スキップ（差分なし）: {label}")
            return _SyncOutcome(True, False)

        verb = "更新（管理ブロックを反映）" if kind == "replace" else "追記（管理ブロックを追加）"
        if dry_run:
            print(f"[DRY-RUN] {verb}: {label}")
            return _SyncOutcome(True, True)

        self._atomic_write_text(dst, new_content)
        print(f"{verb}: {label}")
        return _SyncOutcome(True, True)

    def _atomic_write_text(self, path: Path, content: str) -> None:
        """同一ディレクトリ内の一時ファイルを使ってテキストを置換する。"""
        path.parent.mkdir(parents=True, exist_ok=True)
        existing_mode: int | None = None
        if path.exists():
            try:
                existing_mode = stat.S_IMODE(path.stat().st_mode)
            except OSError:
                existing_mode = None

        tmp_name: str | None = None
        try:
            file_descriptor, tmp_name = tempfile.mkstemp(
                dir=str(path.parent), prefix=f".{path.name}.", suffix=".tmp"
            )
            with os.fdopen(file_descriptor, "w", encoding="utf-8", newline="") as tmp_file:
                tmp_file.write(content)

            if existing_mode is not None:
                os.chmod(tmp_name, existing_mode)
            else:
                current_umask = os.umask(0)
                os.umask(current_umask)
                os.chmod(tmp_name, 0o666 & ~current_umask)

            os.replace(tmp_name, path)
            tmp_name = None
        except Exception:
            if tmp_name is not None:
                try:
                    os.unlink(tmp_name)
                except OSError:
                    pass
            raise

    def _cleanup_legacy_context_files(
        self,
        project_dir: Path,
        project_root: Path,
        dry_run: bool = False,
        allow_claude_md_delete: bool = True,
    ) -> tuple[list[Path], list[Path]]:
        """配布廃止済み context ファイルの生成物を安全に削除する。

        ユーザーが手書きしたファイルを誤って消さないよう、
        生成物マーカー（先頭行が GENERATED_MARKER と一致するファイル）のみ削除する。
        戻り値は (実際に削除した/dry-run なら削除するはずだったパス一覧, 汎用シャドー警告を
        重複させないために除外すべきパス一覧) のタプル。
        """
        removed_or_pending: list[Path] = []
        suppressed: list[Path] = []
        for rel in self.LEGACY_CONTEXT_FILES:
            path = project_dir / rel
            if path.is_symlink():
                continue
            if not path.is_file():
                continue
            try:
                path.parent.resolve().relative_to(project_root)
            except (OSError, ValueError):
                continue
            try:
                content = path.read_text(encoding="utf-8")
            except (OSError, UnicodeDecodeError):
                continue
            if not self._first_line_is_generated_marker(content):
                print(f"スキップ（手書きファイルの可能性）: {rel}")
                continue

            if rel == "CLAUDE.md" and not allow_claude_md_delete:
                print(
                    "警告: AGENTS.md の同期に失敗したため CLAUDE.md を残しました。"
                    "AGENTS.md の管理ブロックを直して再実行してください",
                    file=sys.stderr,
                )
                suppressed.append(path.resolve())
                continue

            if dry_run:
                print(f"[DRY-RUN] 削除（配布廃止、バックアップ後）: {rel}")
                removed_or_pending.append(path.resolve())
                suppressed.append(path.resolve())
                continue
            backup_path = self._backup_legacy_file(project_dir, rel, path)
            if backup_path is None:
                print(f"警告: バックアップに失敗したためスキップ: {rel}", file=sys.stderr)
                continue
            print(f"バックアップ: {backup_path.relative_to(project_dir)}")
            try:
                path.unlink()
            except OSError:
                print(f"警告: 削除に失敗しました: {rel}", file=sys.stderr)
                continue
            message = f"削除（配布廃止）: {rel}"
            if rel == "CLAUDE.md":
                message += (
                    " — プロジェクト固有の記述は退避先から AGENTS.md の記述欄へ移してください"
                )
            print(message)
            removed_or_pending.append(path.resolve())
            suppressed.append(path.resolve())
        return removed_or_pending, suppressed

    def _warn_shadowing_claude_files(
        self,
        project_dir: Path,
        project_root: Path,
        excluded_paths: list[Path],
    ) -> None:
        """AGENTS.md の読み込みを妨げる CLAUDE.md を警告する。"""
        excluded: set[Path] = set()
        for path in excluded_paths:
            try:
                excluded.add(path.resolve())
            except OSError:
                excluded.add(path)

        try:
            home_claude_md = (Path.home() / ".claude" / "CLAUDE.md").resolve()
        except OSError:
            home_claude_md = None

        warned: set[Path] = set()
        for ancestor in [project_root, *project_root.parents]:
            for rel in self.SHADOWING_CLAUDE_FILENAMES:
                candidate = ancestor / rel
                if not candidate.is_file():
                    continue
                try:
                    resolved = candidate.resolve()
                except OSError:
                    resolved = candidate
                if (
                    rel == ".claude/CLAUDE.md"
                    and home_claude_md is not None
                    and resolved == home_claude_md
                ):
                    continue
                if resolved in excluded or resolved in warned:
                    continue
                warned.add(resolved)
                print(
                    f"警告: {resolved} があるため Claude Code は AGENTS.md を読み込みません。"
                    "内容を AGENTS.md に移して削除してください",
                    file=sys.stderr,
                )

    # --- gitignore ---

    def sync_gitignore(self, project_dir: Path, dry_run: bool = False) -> bool:
        """プロジェクトの .gitignore に AI Orchestra ブロックを追加/更新する。"""
        from lib import gitignore_sync

        path = project_dir / ".gitignore"
        existing = ""
        if path.exists():
            try:
                existing = path.read_text(encoding="utf-8")
            except OSError:
                existing = ""

        merged = gitignore_sync.merge_content(existing)
        if merged == existing:
            print("スキップ（既存）: .gitignore (AI Orchestra block)")
            return False

        if dry_run:
            print("[DRY-RUN] .gitignore 更新: AI Orchestra block")
            return True

        path.write_text(merged, encoding="utf-8")
        print(".gitignore 更新: AI Orchestra block")
        return True
