"""Context テンプレートの生成・検証・同期を担当する Mixin。"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import TYPE_CHECKING, Any, Protocol

if TYPE_CHECKING:
    ContextSpecEntry = tuple[str, tuple[str, ...], str, str, str | None]


class _ContextHost(Protocol):
    """ContextMixin が利用側に要求するインターフェース。"""

    orchestra_dir: Path
    CONTEXT_SPECS: tuple[ContextSpecEntry, ...]
    CONTEXT_SHARED_REL: str

    def get_project_dir(self, project: str | None) -> Path: ...
    def load_orchestra_json(self, project_dir: Path) -> dict[str, Any]: ...


class ContextMixin:
    """OrchestraManager に context 管理機能を提供する Mixin。

    利用側は _ContextHost Protocol を満たすこと。
    """

    # Protocol で宣言した属性を型チェッカーに認識させる
    orchestra_dir: Path
    CONTEXT_SPECS: tuple[ContextSpecEntry, ...]
    CONTEXT_SHARED_REL: str

    def get_project_dir(self, project: str | None) -> Path: ...

    def _load_context_file(self, path: Path) -> str:
        """context テンプレートファイルを読み込む（存在しなければ終了）。"""
        if not path.exists():
            print(f"エラー: context テンプレートが見つかりません: {path}", file=sys.stderr)
            sys.exit(1)
        try:
            return path.read_text(encoding="utf-8").strip()
        except OSError as e:
            print(
                f"エラー: context テンプレートの読み込みに失敗: {path} ({e})",
                file=sys.stderr,
            )
            sys.exit(1)

    def _render_context_content(
        self,
        source_rels: tuple[str, ...] | str,
        shared_content: str | None = None,
    ) -> str:
        """templates/context の断片から1つの文書を生成する。

        source_rels が複数の場合は区切り線で連結する
        （例: AGENTS.md = codex.md + antigravity.md のセクション合成）。
        """
        if isinstance(source_rels, str):
            source_rels = (source_rels,)
        source_contents = [
            self._load_context_file(self.orchestra_dir / "templates" / "context" / rel)
            for rel in source_rels
        ]
        if shared_content is None:
            shared_path = self.orchestra_dir / self.CONTEXT_SHARED_REL
            shared_content = self._load_context_file(shared_path)

        source_labels = ", ".join(f"templates/context/{rel}" for rel in source_rels)
        sections = [
            "<!-- DO NOT EDIT: generated by `orchex context build` -->",
            f"<!-- Sources: {source_labels}, {self.CONTEXT_SHARED_REL} -->",
            "",
            "\n\n---\n\n".join(source_contents),
        ]
        if shared_content:
            sections.extend(["", "---", "", shared_content])
        return "\n".join(sections).rstrip() + "\n"

    def _update_file_if_needed(
        self,
        path: Path,
        content: str,
        label: str,
        dry_run: bool = False,
        skip_if_exists: bool = False,
    ) -> bool:
        """差分がある場合のみファイルを更新する。"""
        if skip_if_exists and path.exists():
            print(f"スキップ（既存）: {label}")
            return False

        existing: str | None = None
        if path.exists():
            try:
                existing = path.read_text(encoding="utf-8")
            except OSError:
                existing = None

        if existing == content:
            print(f"スキップ（差分なし）: {label}")
            return False

        if dry_run:
            print(f"[DRY-RUN] 更新: {label}")
            return True

        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"更新: {label}")
        return True

    def _load_shared_content(self) -> str:
        """shared.md を読み込んで返す（キャッシュ用途）。"""
        return self._load_context_file(self.orchestra_dir / self.CONTEXT_SHARED_REL)

    def context_build(self, dry_run: bool = False) -> int:
        """templates/context から配布テンプレートを再生成する。"""
        shared_content = self._load_shared_content()
        changed = 0
        for _, source_rels, template_rel, _, _ in self.CONTEXT_SPECS:
            dst = self.orchestra_dir / template_rel
            content = self._render_context_content(source_rels, shared_content)
            label = str(dst.relative_to(self.orchestra_dir))
            if self._update_file_if_needed(dst, content, label, dry_run=dry_run):
                changed += 1

        if changed == 0:
            print("context build: 差分なし")
        return changed

    def context_check(self) -> bool:
        """templates/context 由来の生成結果とテンプレートの一致を検証する。"""
        shared_content = self._load_shared_content()
        mismatches: list[str] = []

        for _, source_rels, template_rel, _, _ in self.CONTEXT_SPECS:
            expected = self._render_context_content(source_rels, shared_content)
            target = self.orchestra_dir / template_rel
            label = str(target.relative_to(self.orchestra_dir))

            if not target.exists():
                mismatches.append(f"{label} (missing)")
                continue

            try:
                actual = target.read_text(encoding="utf-8")
            except OSError:
                mismatches.append(f"{label} (unreadable)")
                continue

            if actual != expected:
                mismatches.append(f"{label} (outdated)")

        if not mismatches:
            print("context check: OK")
            return True

        print("context check: NG")
        print("不一致ファイル:")
        for item in mismatches:
            print(f"- {item}")
        print("実行コマンド: orchex context build")
        return False

    def context_sync(self, project: str | None, dry_run: bool = False, force: bool = False) -> int:
        """生成済み context をプロジェクトのトップレベル文書へ同期する。"""
        project_dir = self.get_project_dir(project)
        project_root = project_dir.resolve()
        shared_content = self._load_shared_content()
        changed = 0
        skip_existing = not force

        orch = self.load_orchestra_json(project_dir)
        installed_packages = set(orch.get("installed_packages", []))

        for _, source_rels, _, project_rel, required_pkg in self.CONTEXT_SPECS:
            if required_pkg is not None and required_pkg not in installed_packages:
                continue
            dst = project_dir / project_rel

            if dst.is_symlink():
                print(f"スキップ（安全性）: {project_rel} (symlink)")
                continue
            try:
                dst_parent_resolved = dst.parent.resolve()
            except OSError:
                print(f"スキップ（安全性）: {project_rel} (parent unreadable)")
                continue
            try:
                dst_parent_resolved.relative_to(project_root)
            except ValueError:
                print(f"スキップ（安全性）: {project_rel} (outside project)")
                continue

            content = self._render_context_content(source_rels, shared_content)
            if self._update_file_if_needed(
                dst,
                content,
                project_rel,
                dry_run=dry_run,
                skip_if_exists=skip_existing,
            ):
                changed += 1

        changed += self._cleanup_legacy_context_files(project_dir, dry_run=dry_run)

        if changed == 0:
            print("context sync: 差分なし")
        return changed

    # 生成物マーカー（このマーカーを含むファイルだけが自動削除の対象）
    GENERATED_MARKER = "<!-- DO NOT EDIT: generated by `orchex context build` -->"

    # 配布を廃止した context ファイル（生成物のみクリーンアップする）
    LEGACY_CONTEXT_FILES = (".gemini/GEMINI.md",)

    def _cleanup_legacy_context_files(self, project_dir: Path, dry_run: bool = False) -> int:
        """配布廃止済み context ファイルの生成物を安全に削除する。

        ユーザーが手書きしたファイルを誤って消さないよう、
        GENERATED_MARKER を含むファイルのみ削除する。
        """
        removed = 0
        for rel in self.LEGACY_CONTEXT_FILES:
            path = project_dir / rel
            if not path.is_file() or path.is_symlink():
                continue
            try:
                content = path.read_text(encoding="utf-8")
            except OSError:
                continue
            if self.GENERATED_MARKER not in content:
                print(f"スキップ（手書きファイルの可能性）: {rel}")
                continue
            if dry_run:
                print(f"[DRY-RUN] 削除（配布廃止）: {rel}")
                removed += 1
                continue
            try:
                path.unlink()
                print(f"削除（配布廃止）: {rel}")
                removed += 1
            except OSError:
                pass
        return removed

    # --- gitignore ---

    def sync_gitignore(self, project_dir: Path, dry_run: bool = False) -> bool:
        """プロジェクトの .gitignore に AI Orchestra ブロックを追加/更新する。"""
        from lib import gitignore_sync

        path = project_dir / ".gitignore"
        existing = ""
        if path.exists():
            try:
                existing = path.read_text(encoding="utf-8")
            except OSError:
                existing = ""

        merged = gitignore_sync.merge_content(existing)
        if merged == existing:
            print("スキップ（既存）: .gitignore (AI Orchestra block)")
            return False

        if dry_run:
            print("[DRY-RUN] .gitignore 更新: AI Orchestra block")
            return True

        path.write_text(merged, encoding="utf-8")
        print(".gitignore 更新: AI Orchestra block")
        return True
