"""プロジェクト scaffold と .claudeignore 管理。"""

from __future__ import annotations

import shutil
from pathlib import Path

CLAUDEIGNORE_HEADER = """\
# =============================================================================
# .claudeignore (auto-generated by AI Orchestra)
# DO NOT EDIT — managed by sync-orchestra.py
# Project-specific patterns: create .claudeignore.local
# =============================================================================
"""

LOCAL_SECTION_HEADER = """\
# =============================================================================
# Project-specific patterns (from .claudeignore.local)
# =============================================================================
"""


def _strip_header(content: str) -> str:
    """先頭の連続コメント行 + 空行ブロック（= ヘッダー）を除去してボディを返す。"""
    lines = content.splitlines(keepends=True)
    idx = 0
    while idx < len(lines):
        stripped = lines[idx].strip()
        if stripped == "" or stripped.startswith("#"):
            idx += 1
        else:
            break
    return "".join(lines[idx:])


def ensure_claude_scaffold(project_dir: Path, orchestra_path: Path) -> int:
    """`.claude` の最低限ディレクトリとテンプレートを不足時のみ作成する。"""
    created = 0
    claude_dirs = [
        project_dir / ".claude" / "docs",
        project_dir / ".claude" / "docs" / "research",
        project_dir / ".claude" / "docs" / "libraries",
        project_dir / ".claude" / "logs",
        project_dir / ".claude" / "logs" / "orchestration",
        project_dir / ".claude" / "state",
        project_dir / ".claude" / "checkpoints",
    ]

    for d in claude_dirs:
        if d.is_dir():
            continue
        try:
            d.mkdir(parents=True, exist_ok=True)
            created += 1
        except OSError:
            continue

    template_root = orchestra_path / "templates" / "project"
    template_pairs: list[tuple[str, str]] = [
        ("docs/DESIGN.md", ".claude/docs/DESIGN.md"),
        ("docs/libraries/_TEMPLATE.md", ".claude/docs/libraries/_TEMPLATE.md"),
        ("docs/research/.gitkeep", ".claude/docs/research/.gitkeep"),
        ("logs/orchestration/.gitkeep", ".claude/logs/orchestration/.gitkeep"),
        ("state/.gitkeep", ".claude/state/.gitkeep"),
        ("checkpoints/.gitkeep", ".claude/checkpoints/.gitkeep"),
        ("Plans.md", ".claude/Plans.md"),
    ]

    for src_rel, dst_rel in template_pairs:
        src = template_root / src_rel
        dst = project_dir / dst_rel
        if not src.is_file() or dst.exists():
            continue
        try:
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dst)
            created += 1
        except OSError:
            continue

    return created


def sync_claudeignore(project_dir: Path, orchestra_path: Path) -> bool:
    """ベーステンプレートと .claudeignore.local をマージして .claudeignore を生成する。

    Returns:
        True if .claudeignore was updated, False otherwise.
    """
    template_path = orchestra_path / "templates" / "project" / ".claudeignore"
    if not template_path.exists():
        return False

    try:
        base_content = template_path.read_text(encoding="utf-8")
    except OSError:
        return False

    base_body = _strip_header(base_content)

    # .claudeignore.local のマージ
    local_path = project_dir / ".claudeignore.local"
    local_section = ""
    if local_path.is_file():
        try:
            local_content = local_path.read_text(encoding="utf-8")
            local_body = _strip_header(local_content)
            if local_body.strip():
                local_section = "\n" + LOCAL_SECTION_HEADER + "\n" + local_body
        except OSError:
            pass

    merged = CLAUDEIGNORE_HEADER + "\n" + base_body + local_section

    # 末尾改行を正規化
    if not merged.endswith("\n"):
        merged += "\n"

    # 内容ベース差分チェック
    dst_path = project_dir / ".claudeignore"
    if dst_path.is_file():
        try:
            existing = dst_path.read_text(encoding="utf-8")
            if existing == merged:
                return False
        except OSError:
            pass

    try:
        dst_path.write_text(merged, encoding="utf-8")
    except OSError:
        return False

    return True
