"""パッケージ同期エンジン（SessionStart hook のコアロジック）。"""

from __future__ import annotations

import hashlib
import json
import re
import shutil
import subprocess
import sys
import tomllib
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:  # pragma: no cover
    yaml = None  # type: ignore[assignment]

from lib.hook_utils import (
    add_hook_to_settings,
    find_hook_in_settings,
    get_hook_command,
    is_orchestra_hook,
    is_sync_hook_command,
    migrate_hook_interpreters,
    parse_hook_entry,
    parse_pkg_from_command,
    remove_hook_from_settings,
)
from lib.toml_merge import (
    find_toml_section,
    upsert_toml_key_in_section,
    upsert_toml_section,
    upsert_toml_top_level_key,
)

_PERMISSIONS_SECTION_PREFIX = "permissions."
_CODEX_HARNESS_CONFIG_REL = Path("codex") / "config-harness.toml"
_LEGACY_CODEX_HARNESS_PROFILE = "project-edit"
_LEGACY_CODEX_HARNESS_PROFILE_SECTIONS = (
    'permissions.project-edit.filesystem.":workspace_roots"',
    "permissions.project-edit",
)
_LEGACY_CODEX_HARNESS_DENY_SENTINELS = (
    "**/.codex/hooks/**",
    "**/.codex/validation.json",
    "**/.claude/orchestra.json",
)


def config_target_relative_path(package_name: str, manifest_path: str) -> Path:
    """Map a manifest config path into its package-scoped project path."""
    source_path = Path(manifest_path)
    parts = source_path.parts
    config_relative = Path(*parts[1:]) if parts and parts[0] == "config" else source_path
    if config_relative.is_absolute() or ".." in config_relative.parts:
        raise ValueError(f"unsafe config path: {manifest_path}")
    return Path("config") / package_name / config_relative


def _toml_scalar(value: Any) -> str:
    """Python 値を TOML の値リテラル文字列に変換する（bool/str/int 限定の簡易実装）。"""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        return json.dumps(value)
    return str(value)


def _iter_toml_sections(content: str, header_prefix: str) -> list[tuple[str, str]]:
    """content 内の `[<header_prefix>...]` セクションをヘッダ名とセクション全文のペアで返す。"""
    header_re = re.compile(rf"^\[({re.escape(header_prefix)}[^\]]*)\]", re.MULTILINE)
    lines = content.splitlines()
    sections: list[tuple[str, str]] = []
    for match in header_re.finditer(content):
        header = match.group(1)
        span = find_toml_section(content, header)
        if span is None:
            continue
        sections.append((header, "\n".join(lines[span[0] : span[1]])))
    return sections


def _remove_toml_top_level_key(content: str, key: str) -> str:
    """Remove a top-level scalar key if present."""
    lines = content.splitlines()
    top_end = len(lines)
    for i, line in enumerate(lines):
        if re.match(r"^\s*\[[^\[\]]+\]\s*(?:#.*)?$", line.strip()):
            top_end = i
            break

    key_re = re.compile(rf"^\s*{re.escape(key)}\s*=")
    for i in range(top_end):
        if key_re.match(lines[i]):
            merged = "\n".join(lines[:i] + lines[i + 1 :]) + "\n"
            tomllib.loads(merged)
            return merged
    return content


def _remove_toml_section(content: str, section_name: str) -> str:
    """Remove an exact TOML section if present."""
    span = find_toml_section(content, section_name)
    if span is None:
        return content
    lines = content.splitlines()
    merged = "\n".join(lines[: span[0]] + lines[span[1] :]) + "\n"
    tomllib.loads(merged)
    return merged


def _looks_like_legacy_codex_harness_profile(original_data: dict[str, Any]) -> bool:
    """Detect the old harness-owned `project-edit` profile narrowly.

    The migration must not delete user-managed permission profiles just because
    they happen to share the same name. Require the old `:workspace` extension
    plus guardrail deny sentinels that were generated by codex-harness.
    """
    permissions = original_data.get("permissions")
    if not isinstance(permissions, dict):
        return False
    project_edit = permissions.get(_LEGACY_CODEX_HARNESS_PROFILE)
    if not isinstance(project_edit, dict):
        return False
    if project_edit.get("extends") != ":workspace":
        return False

    filesystem = project_edit.get("filesystem")
    if not isinstance(filesystem, dict):
        return False
    workspace_roots = filesystem.get(":workspace_roots")
    if not isinstance(workspace_roots, dict):
        return False
    if workspace_roots.get(".") != "write":
        return False
    return all(workspace_roots.get(path) == "deny" for path in _LEGACY_CODEX_HARNESS_DENY_SENTINELS)


def _remove_legacy_codex_harness_profile(
    content: str, original_data: dict[str, Any], harness_data: dict[str, Any]
) -> str:
    """Remove stale config written by older codex-harness releases.

    Current codex-harness no longer owns `default_permissions` or
    `[permissions.*]` because forcing a repo-local profile broke interactive
    Git/gh flows in worktrees. When upgrading an already-synced project, remove
    only the exact old harness-owned `project-edit` profile and top-level
    default that selected it. User-managed values are left untouched.
    """
    if "default_permissions" in harness_data or "permissions" in harness_data:
        return content

    migrated = content
    if _looks_like_legacy_codex_harness_profile(original_data):
        if original_data.get("default_permissions") == _LEGACY_CODEX_HARNESS_PROFILE:
            migrated = _remove_toml_top_level_key(migrated, "default_permissions")
        for section_name in _LEGACY_CODEX_HARNESS_PROFILE_SECTIONS:
            migrated = _remove_toml_section(migrated, section_name)

    return migrated


def _warn_if_kept_value_conflicts(existing_value: Any, harness_value: Any, key_label: str) -> None:
    """Warn to stderr when an add-if-missing key's kept value conflicts with the harness intent.

    The merge behavior itself never changes (existing user values are always
    kept as-is); this only surfaces a warning so the operator notices that
    the harness's config is effectively disabled/overridden for that key.
    """
    if existing_value is None or existing_value == harness_value:
        return
    if key_label == "features.hooks" and existing_value is False:
        print(
            "[warn] codex-harness: features.hooks=false のためハーネスの hooks は無効のままです",
            file=sys.stderr,
        )
        return
    print(
        f"[warn] codex-harness: {key_label} が {existing_value!r} のまま保持されました"
        f"（ハーネス既定値は {harness_value!r}）",
        file=sys.stderr,
    )


def apply_codex_harness_config(
    project_dir: Path,
    orchestra_path: Path,
    installed_packages: list[str],
    dry_run: bool = False,
) -> bool:
    """codex-harness の config-harness.toml をプロジェクトの `.codex/config.toml` へマージする。

    codex-harness が未インストール、または `.codex/config.toml` が存在しない場合は
    何もせず False を返す（config.toml の初期所有は codex-suggestions のため、
    ここでは新規作成しない）。

    マージ規則:
      - `[features].hooks`: add-if-missing（ユーザー値を上書きしない）。
      - 現行 harness は `default_permissions` / `[permissions.*]` を所有しない。
        ただし過去に harness が同期した旧 `project-edit` profile は、アップグレード時に
        narrowly targeted migration として削除する。

    dry_run=True の場合、マージ結果の計算までは行うが `.codex/config.toml`
    は書き換えず、更新が発生する場合のみ `[DRY-RUN]` プレビューを表示する。

    Returns:
        True: config.toml を更新した（dry_run 時は更新予定）。
        False: 変更なし、またはスキップした。
    """
    if "codex-harness" not in installed_packages:
        return False

    config_path = project_dir / ".codex" / "config.toml"
    if not config_path.is_file():
        print(
            "[warn] .codex/config.toml が見つからないため codex-harness 設定マージをスキップしました"
            "（config.toml の初期配置は codex-suggestions が担当）",
            file=sys.stderr,
        )
        return False

    harness_toml_path = orchestra_path / "packages" / "codex-harness" / _CODEX_HARNESS_CONFIG_REL
    if not harness_toml_path.is_file():
        return False

    harness_content = harness_toml_path.read_text(encoding="utf-8")
    try:
        harness_data = tomllib.loads(harness_content)
    except tomllib.TOMLDecodeError:
        print(
            "[warn] config-harness.toml が不正な TOML のためマージをスキップしました",
            file=sys.stderr,
        )
        return False

    original = config_path.read_text(encoding="utf-8")
    content = original

    try:
        original_data = tomllib.loads(original)
    except tomllib.TOMLDecodeError:
        original_data = {}

    content = _remove_legacy_codex_harness_profile(content, original_data, harness_data)

    if "default_permissions" in harness_data:
        harness_value = harness_data["default_permissions"]
        _warn_if_kept_value_conflicts(
            existing_value=original_data.get("default_permissions"),
            harness_value=harness_value,
            key_label="default_permissions",
        )
        value = _toml_scalar(harness_value)
        content = upsert_toml_top_level_key(content, "default_permissions", value, overwrite=False)

    if "hooks" in harness_data.get("features", {}):
        harness_value = harness_data["features"]["hooks"]
        original_features = original_data.get("features")
        existing_hooks_value = (
            original_features.get("hooks") if isinstance(original_features, dict) else None
        )
        _warn_if_kept_value_conflicts(
            existing_value=existing_hooks_value,
            harness_value=harness_value,
            key_label="features.hooks",
        )
        value = _toml_scalar(harness_value)
        content = upsert_toml_key_in_section(content, "features", "hooks", value, overwrite=False)

    for section_name, section_text in _iter_toml_sections(
        harness_content, _PERMISSIONS_SECTION_PREFIX
    ):
        content = upsert_toml_section(content, section_name, section_text)

    if content == original:
        return False

    if dry_run:
        print("[DRY-RUN] .codex/config.toml を codex-harness 設定で更新予定")
        return True

    config_path.write_text(content, encoding="utf-8")
    return True


def needs_sync(src: Path, dst: Path) -> bool:
    """ソースがデスティネーションより新しいか、デスティネーションが存在しないか判定する。"""
    if not dst.exists():
        return True
    return src.stat().st_mtime > dst.stat().st_mtime


def is_local_override(category: str, rel_path: Path) -> bool:
    """プロジェクト固有の上書きファイル（*.local.yaml / *.local.json）かどうか判定する。"""
    name = rel_path.name
    return category == "config" and (name.endswith(".local.yaml") or name.endswith(".local.json"))


# --- 配布時ハッシュ記録（uninstall / 再 install でのユーザー編集保護） ---


def compute_file_hash(path: Path) -> str:
    """ファイルの SHA-256 ハッシュ（16進文字列）を計算する。"""
    return hashlib.sha256(path.read_bytes()).hexdigest()


def record_file_hash(orch: dict, pkg_name: str, file_key: str, file_hash: str) -> None:
    """orchestra.json の file_hashes[pkg_name][file_key] を更新する。"""
    file_hashes = orch.setdefault("file_hashes", {})
    pkg_hashes = file_hashes.setdefault(pkg_name, {})
    pkg_hashes[file_key] = file_hash


def get_recorded_file_hash(orch: dict, pkg_name: str, file_key: str) -> str | None:
    """orchestra.json に記録された配布時ハッシュを返す（記録がなければ None）。

    file_hashes キー自体が存在しない旧形式の orchestra.json でも None を返す
    （後方互換）。
    """
    return orch.get("file_hashes", {}).get(pkg_name, {}).get(file_key)


def is_user_modified(orch: dict, pkg_name: str, file_key: str, dst: Path) -> bool:
    """dst が配布時記録ハッシュと異なる（= ユーザーが編集済み）かどうかを判定する。

    dst が存在しない、またはハッシュ未記録（初回同期・旧形式の orchestra.json）の
    場合は False を返し、従来どおりの上書きを許可する（保護は record 開始以降のみ
    有効。_copy_config_if_safe と同じ「安全側だが後方互換」の方針）。
    """
    if not dst.exists():
        return False
    recorded = get_recorded_file_hash(orch, pkg_name, file_key)
    if recorded is None:
        return False
    return compute_file_hash(dst) != recorded


def refresh_patched_agent_hashes(orch: dict, claude_dir: Path, patched_paths: list[Path]) -> None:
    """model パッチ適用後の agents ファイルについて、file_hashes 台帳を最新内容で更新する。

    patch_all_agents_paths() が model: 行を書き換えた直後に呼び出す。パッチ前の
    内容で記録されたハッシュのままだと、次回セッションで is_user_modified() が
    パッチ済み内容を「ユーザー編集」と誤判定し、正当な上流更新までスキップして
    しまうため（PR #244 レビュー指摘）、パッチ後の内容でハッシュを記録し直す。
    file_hashes に該当エントリが無いパッケージ/ファイルは何もしない。
    """
    file_hashes = orch.get("file_hashes")
    if not file_hashes:
        return

    for patched_path in patched_paths:
        try:
            file_key = str(patched_path.relative_to(claude_dir))
        except ValueError:
            continue
        new_hash = compute_file_hash(patched_path)
        for pkg_hashes in file_hashes.values():
            if file_key in pkg_hashes:
                pkg_hashes[file_key] = new_hash


def collect_managed_agent_stems(orchestra_path: Path, installed_packages: list[str]) -> set[str]:
    """インストール済みパッケージの manifest.agents からファイル名 stem 集合を収集する。

    patch_all_agents() の allowlist として使い、パッケージが宣言していない
    ユーザー独自エージェント .md を model パッチ対象から除外する。
    """
    stems: set[str] = set()
    for pkg_name in installed_packages:
        manifest_path = orchestra_path / "packages" / pkg_name / "manifest.json"
        if not manifest_path.is_file():
            continue
        try:
            with open(manifest_path, encoding="utf-8") as f:
                manifest = json.load(f)
        except (json.JSONDecodeError, OSError):
            continue
        for rel_path in manifest.get("agents", []):
            if isinstance(rel_path, str) and rel_path:
                stems.add(Path(rel_path).stem)
    return stems


def remove_stale_files(
    claude_dir: Path,
    prev_synced: list[str],
    current_synced: set[str],
    facet_managed: set[str] | None = None,
) -> int:
    """前回同期したが今回は対象外になったファイルを削除する。

    facet_managed に含まれるパスは facet build が管理するため削除しない。
    削除後に空になったディレクトリも再帰的に削除する。
    """
    removed = 0
    for file_key in prev_synced:
        if file_key in current_synced:
            continue
        if facet_managed and file_key in facet_managed:
            continue
        parts = file_key.split("/", 1)
        if len(parts) == 2 and is_local_override(parts[0], Path(parts[1])):
            continue
        target = claude_dir / file_key
        if target.is_file():
            target.unlink()
            removed += 1
            parent = target.parent
            while parent != claude_dir and parent.is_dir():
                try:
                    parent.rmdir()
                    parent = parent.parent
                except OSError:
                    break
    return removed


def collect_facet_managed_paths(orchestra_path: Path, project_dir: Path) -> set[str]:
    """facet composition で管理される skill/rule のパスを収集する。

    返すパスは .claude/ 相対（例: "skills/review/SKILL.md", "rules/coding-principles.md"）。
    """
    managed: set[str] = set()
    dirs = []
    compositions_dir = orchestra_path / "facets" / "compositions"
    if compositions_dir.is_dir():
        dirs.append(compositions_dir)
    local_dir = project_dir / ".claude" / "facets" / "compositions"
    if local_dir.is_dir():
        dirs.append(local_dir)

    for d in dirs:
        for ypath in d.rglob("*.yaml"):
            try:
                with open(ypath, encoding="utf-8") as f:
                    if yaml:
                        comp = yaml.safe_load(f)
                    else:
                        text = f.read()
                        m_name = re.search(r"^name:\s*(.+)$", text, re.MULTILINE)
                        m_type = re.search(r"^type:\s*(.+)$", text, re.MULTILINE)
                        comp = {}
                        if m_name:
                            comp["name"] = m_name.group(1).strip()
                        if m_type:
                            comp["type"] = m_type.group(1).strip()
            except OSError:
                continue
            if not isinstance(comp, dict) or "name" not in comp:
                continue
            name = comp["name"]
            comp_type = comp.get("type", "skill")
            if comp_type == "rule":
                managed.add(f"rules/{name}.md")
            else:
                managed.add(f"skills/{name}/SKILL.md")
                for kname in comp.get("knowledge") or []:
                    if isinstance(kname, str):
                        managed.add(f"skills/{name}/references/{kname}.md")
                for sname in comp.get("scripts") or []:
                    if isinstance(sname, str):
                        managed.add(f"skills/{name}/scripts/{sname}")
    return managed


def collect_manifest_compositions(
    orchestra_path: Path,
) -> dict[str, str]:
    """Collect composition names from skills/rules fields of ALL package manifests.

    Scans every package directory (not just installed ones) so that
    package-owned compositions can be distinguished from global ones.

    Returns:
        {composition_name: package_name} mapping
    """
    compositions: dict[str, str] = {}
    packages_dir = orchestra_path / "packages"
    if not packages_dir.is_dir():
        return compositions
    for pkg_dir in sorted(packages_dir.iterdir()):
        manifest_path = pkg_dir / "manifest.json"
        if not manifest_path.is_file():
            continue
        try:
            with open(manifest_path, encoding="utf-8") as f:
                manifest = json.load(f)
        except (json.JSONDecodeError, OSError):
            continue
        pkg_name = manifest.get("name", pkg_dir.name)
        for field in ("skills", "rules"):
            for name in manifest.get(field, []):
                if isinstance(name, str):
                    if name in compositions:
                        print(
                            f"[warn] composition '{name}' claimed by both"
                            f" '{compositions[name]}' and '{pkg_name}'",
                            file=sys.stderr,
                        )
                    compositions[name] = pkg_name
    return compositions


def sync_codex_files(
    project_dir: Path,
    orchestra_path: Path,
    installed_packages: list[str],
    orch: dict,
    force: bool = False,
    dry_run: bool = False,
) -> int:
    """manifest.json の codex_files をプロジェクトへ同期する（配布時ハッシュ保護付き）。

    ハッシュ台帳は orch["codex_file_hashes"][target] にフラット記録する
    （agents/config 用の orch["file_hashes"][pkg_name][file_key] とは別台帳）。
    dry_run=True の場合、実際のコピー/ハッシュ台帳更新は行わず、同期予定の
    ファイルを `[DRY-RUN]` として表示するだけに留める。

    Returns:
        コピー/更新した（dry_run 時は同期予定の）ファイル数
    """
    synced_count = 0
    hashes: dict[str, str] = orch.setdefault("codex_file_hashes", {})

    for pkg_name in installed_packages:
        manifest_path = orchestra_path / "packages" / pkg_name / "manifest.json"
        if not manifest_path.is_file():
            continue

        try:
            with open(manifest_path, encoding="utf-8") as f:
                manifest = json.load(f)
        except (json.JSONDecodeError, OSError):
            continue

        pkg_dir = orchestra_path / "packages" / pkg_name
        for entry in manifest.get("codex_files", []):
            source_rel = entry.get("source") if isinstance(entry, dict) else None
            target_rel = entry.get("target") if isinstance(entry, dict) else None
            if not source_rel or not target_rel:
                continue

            src = pkg_dir / source_rel
            if not src.is_file():
                continue

            dst = project_dir / target_rel
            if _sync_codex_file(src, dst, target_rel, hashes, force, project_dir, dry_run):
                synced_count += 1

    return synced_count


def _is_within_project(dst: Path, project_dir: Path) -> bool:
    """dst の解決後パスが project_dir 配下（またはそれ自身）かどうかを判定する。

    manifest.json の codex_files.target は本来プロジェクト相対パスの想定だが、
    絶対パス（例: "/etc/passwd"）や `../` を含むパスが混入すると
    `project_dir / target_rel` はプロジェクト外を指し得る（絶対パスの場合、
    pathlib の `/` 演算子は左辺を無視して右辺の絶対パスに置き換わる）。
    書き込み前にこのチェックで必ず脱出を検出する。
    """
    resolved_project = project_dir.resolve()
    resolved_dst = dst.resolve()
    return resolved_dst == resolved_project or resolved_project in resolved_dst.parents


def _sync_codex_file(
    src: Path,
    dst: Path,
    target_key: str,
    hashes: dict[str, str],
    force: bool,
    project_dir: Path,
    dry_run: bool = False,
) -> bool:
    """1 ファイル分の codex_files 同期判定と適用。コピー/更新した（dry_run 時は予定）なら True。"""
    if not _is_within_project(dst, project_dir):
        print(
            f"[warn] {target_key} はプロジェクト外を指すため同期をスキップしました"
            "（絶対パスまたは ../ による脱出の疑い）",
            file=sys.stderr,
        )
        return False

    if not dst.exists():
        if dry_run:
            print(f"[DRY-RUN] 同期: {target_key}")
            return True
        _copy_codex_file(src, dst, target_key, hashes)
        return True

    current_hash = compute_file_hash(dst)
    recorded_hash = hashes.get(target_key)

    if recorded_hash is None:
        if not force:
            print(
                f"[warn] {dst} は配布記録がないため上書きをスキップしました（force で上書き可）",
                file=sys.stderr,
            )
            return False
        if dry_run:
            print(f"[DRY-RUN] 同期: {target_key}")
            return True
        _copy_codex_file(src, dst, target_key, hashes)
        return True

    if current_hash != recorded_hash:
        if not force:
            print(
                f"[warn] {dst} はインストール後に変更されているため上書きをスキップしました（force で上書き可）",
                file=sys.stderr,
            )
            return False
        if dry_run:
            print(f"[DRY-RUN] 同期: {target_key}")
            return True
        _copy_codex_file(src, dst, target_key, hashes)
        return True

    if current_hash == compute_file_hash(src):
        return False

    if dry_run:
        print(f"[DRY-RUN] 同期: {target_key}")
        return True
    _copy_codex_file(src, dst, target_key, hashes)
    return True


def _copy_codex_file(src: Path, dst: Path, target_key: str, hashes: dict[str, str]) -> None:
    """codex_files の1ファイルをコピーし、ハッシュ台帳を更新する。"""
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)
    hashes[target_key] = compute_file_hash(dst)


def collect_facet_build_targets(
    orchestra_path: Path,
    installed_packages: list[str] | None,
) -> list[str]:
    """installed_packages の manifest.facet_targets から追加ビルド対象を収集する。

    "claude" は常に含む。パッケージ名の決め打ち（例: "codex-suggestions"）を廃し、
    manifest の facet_targets 宣言（capability）で判定する。
    """
    targets = ["claude"]
    if not installed_packages:
        return targets

    for pkg_name in installed_packages:
        manifest_path = orchestra_path / "packages" / pkg_name / "manifest.json"
        if not manifest_path.is_file():
            continue
        try:
            with open(manifest_path, encoding="utf-8") as f:
                manifest = json.load(f)
        except (json.JSONDecodeError, OSError):
            continue

        for target in manifest.get("facet_targets", []):
            if target not in targets:
                targets.append(target)

    return targets


def sync_hooks(
    project_dir: Path,
    orchestra_path: Path,
    installed_packages: list[str],
) -> int:
    """manifest.json の hooks と settings.local.json を比較し差分を同期する。

    未登録の hook は追加し、登録済みでも manifest 側の timeout と食い違う場合は
    settings.local.json 側を manifest の値に更新する（内部制限とホスト側の
    kill タイムアウトが乖離したまま放置されないようにするため）。

    Returns:
        変更があった hook 数（追加 + timeout 更新 + 削除）
    """
    settings_path = project_dir / ".claude" / "settings.local.json"
    if not settings_path.exists():
        return 0

    try:
        with open(settings_path, encoding="utf-8") as f:
            settings = json.load(f)
    except (json.JSONDecodeError, OSError):
        return 0

    settings_hooks = settings.get("hooks", {})

    migrated = migrate_hook_interpreters(settings_hooks)

    # (event, command, matcher) -> manifest 側で期待される timeout
    expected_hooks: dict[tuple[str, str, str | None], int] = {}
    installed_set = set(installed_packages)

    for pkg_name in installed_packages:
        manifest_path = orchestra_path / "packages" / pkg_name / "manifest.json"
        if not manifest_path.exists():
            continue
        try:
            with open(manifest_path, encoding="utf-8") as f:
                manifest = json.load(f)
        except (json.JSONDecodeError, OSError):
            continue

        for event, entries in manifest.get("hooks", {}).items():
            for raw_entry in entries:
                filename, matcher, timeout = parse_hook_entry(raw_entry)
                if not filename:
                    continue
                command = get_hook_command(pkg_name, filename)
                expected_hooks[(event, command, matcher)] = timeout

    added = 0
    updated = 0
    for (event, command, matcher), timeout in expected_hooks.items():
        if not find_hook_in_settings(settings_hooks, event, command, matcher):
            add_hook_to_settings(settings_hooks, event, command, matcher, timeout)
            added += 1
        elif add_hook_to_settings(settings_hooks, event, command, matcher, timeout):
            updated += 1

    removed = 0
    for event, entries in list(settings_hooks.items()):
        for entry in list(entries):
            matcher = entry.get("matcher")
            for hook in list(entry.get("hooks", [])):
                command = hook.get("command", "")
                if is_sync_hook_command(command):
                    continue
                if not is_orchestra_hook(command):
                    continue
                pkg_name = parse_pkg_from_command(command)
                if pkg_name is not None and pkg_name not in installed_set:
                    remove_hook_from_settings(settings_hooks, event, command, matcher)
                    removed += 1
                    continue
                if (event, command, matcher) not in expected_hooks:
                    remove_hook_from_settings(settings_hooks, event, command, matcher)
                    removed += 1

    changes = added + updated + removed + migrated
    if changes > 0:
        settings["hooks"] = settings_hooks
        try:
            with open(settings_path, "w", encoding="utf-8") as f:
                json.dump(settings, f, indent=2, ensure_ascii=False)
                f.write("\n")
        except OSError:
            pass

    return changes


def sync_packages(
    claude_dir: Path,
    orchestra_path: Path,
    installed_packages: list[str],
    facet_managed: set[str],
    orch: dict | None = None,
) -> tuple[int, set[str]]:
    """パッケージ単位のファイル同期を実行する。

    orch を渡すと agents カテゴリのみ配布時ハッシュ台帳（orch["file_hashes"]）で
    ユーザー編集を保護する: needs_sync（mtime）が同期を示した場合のみ
    is_user_modified() でハッシュ検証するため、無変更時の毎セッションコストは
    増えない。orch が None の場合は従来どおり mtime のみで判定する
    （呼び出し側が台帳を持たないテスト等との後方互換）。

    Returns:
        (synced_count, synced_files)
    """
    synced_count = 0
    synced_files: set[str] = set()
    file_hashes = orch.setdefault("file_hashes", {}) if orch is not None else None

    for pkg_name in installed_packages:
        manifest_path = orchestra_path / "packages" / pkg_name / "manifest.json"
        if not manifest_path.exists():
            continue

        try:
            with open(manifest_path, encoding="utf-8") as f:
                manifest = json.load(f)
        except (json.JSONDecodeError, OSError):
            continue

        pkg_dir = orchestra_path / "packages" / pkg_name

        # "skills" / "rules" は facet build に完全委譲（manifest-SSOT: Issue #20）
        for category in ("agents", "config"):
            file_list = manifest.get(category, [])
            for rel_path in file_list:
                src = pkg_dir / rel_path
                if not src.exists():
                    continue

                if src.is_dir():
                    for src_file in src.rglob("*"):
                        if not src_file.is_file():
                            continue
                        file_rel = str(src_file.relative_to(pkg_dir))
                        if file_rel in facet_managed:
                            continue
                        synced_files.add(file_rel)
                        dst = claude_dir / file_rel
                        if not needs_sync(src_file, dst):
                            continue
                        if (
                            category == "agents"
                            and file_hashes is not None
                            and is_user_modified(orch, pkg_name, file_rel, dst)
                        ):
                            print(
                                f"[warn] {dst} はユーザーにより変更されているため"
                                "同期をスキップしました",
                                file=sys.stderr,
                            )
                            continue
                        dst.parent.mkdir(parents=True, exist_ok=True)
                        shutil.copy2(src_file, dst)
                        if category == "agents" and file_hashes is not None:
                            record_file_hash(orch, pkg_name, file_rel, compute_file_hash(dst))
                        synced_count += 1
                else:
                    if category == "config":
                        dst_key_path = config_target_relative_path(pkg_name, rel_path)
                        dst = claude_dir / dst_key_path
                        dst_key = str(dst_key_path)
                    else:
                        dst = claude_dir / rel_path
                        dst_key = rel_path

                    if dst_key in facet_managed:
                        continue

                    synced_files.add(dst_key)

                    if not needs_sync(src, dst):
                        continue

                    if (
                        category == "agents"
                        and file_hashes is not None
                        and is_user_modified(orch, pkg_name, dst_key, dst)
                    ):
                        print(
                            f"[warn] {dst} はユーザーにより変更されているため同期をスキップしました",
                            file=sys.stderr,
                        )
                        continue

                    dst.parent.mkdir(parents=True, exist_ok=True)
                    shutil.copy2(src, dst)
                    if category == "agents" and file_hashes is not None:
                        record_file_hash(orch, pkg_name, dst_key, compute_file_hash(dst))
                    synced_count += 1

    return synced_count, synced_files


def build_facets(
    orchestra_path: Path,
    project_dir: Path,
    installed_packages: list[str] | None = None,
) -> int:
    """facet composition から SKILL.md / ルール .md を自動生成する。"""

    compositions_dir = orchestra_path / "facets" / "compositions"
    local_compositions_dir = project_dir / ".claude" / "facets" / "compositions"

    has_orchestra = compositions_dir.is_dir() and any(compositions_dir.rglob("*.yaml"))
    has_local = local_compositions_dir.is_dir() and any(local_compositions_dir.rglob("*.yaml"))
    if not has_orchestra and not has_local:
        # composition が 1 件も見つからない状態は、意図的な全削除よりも orchestra_dir の
        # 設定ミス・導入破損である可能性が高い。この状態で先へ進むと facet_builder 側の
        # _cleanup_orphans が前回マニフェストの全スキルを削除しうるため、ここで打ち切る
        # （facet_builder.build_all も同じ理由で 0 件時に fail-closed する）。
        return 0

    yamls: list[Path] = []
    if has_orchestra:
        yamls.extend(compositions_dir.rglob("*.yaml"))
    if has_local:
        yamls.extend(local_compositions_dir.rglob("*.yaml"))

    latest_src = max(p.stat().st_mtime for p in yamls)
    facets_dir = orchestra_path / "facets"
    facet_mds = list(facets_dir.glob("**/*.md"))
    if facet_mds:
        latest_src = max(latest_src, max(p.stat().st_mtime for p in facet_mds))
    local_facets_dir = project_dir / ".claude" / "facets"
    if local_facets_dir.is_dir():
        local_facet_mds = list(local_facets_dir.glob("**/*.md"))
        if local_facet_mds:
            latest_src = max(latest_src, max(p.stat().st_mtime for p in local_facet_mds))

    orch_json = project_dir / ".claude" / "orchestra.json"
    pkgs_str = ""
    if orch_json.is_file():
        try:
            orch_data = json.loads(orch_json.read_text(encoding="utf-8"))
            pkgs_str = ",".join(sorted(orch_data.get("installed_packages", [])))
        except (json.JSONDecodeError, OSError):
            pass
    compositions_str = ",".join(sorted(path.name for path in yamls))
    pkgs_hash = hashlib.md5(f"{pkgs_str}|{compositions_str}".encode()).hexdigest()
    hash_file = project_dir / ".claude" / ".cache" / "packages-hash"
    prev_hash = ""
    if hash_file.is_file():
        try:
            prev_hash = hash_file.read_text(encoding="utf-8").strip()
        except OSError:
            pass
    if pkgs_hash != prev_hash:
        try:
            hash_file.parent.mkdir(parents=True, exist_ok=True)
            hash_file.write_text(pkgs_hash, encoding="utf-8")
        except OSError:
            pass
        import time

        latest_src = time.time()

    claude_skills = project_dir / ".claude" / "skills"
    claude_rules = project_dir / ".claude" / "rules"
    generated: list[Path] = []
    if claude_skills.is_dir():
        generated.extend(claude_skills.glob("*/SKILL.md"))
    if claude_rules.is_dir():
        generated.extend(claude_rules.glob("*.md"))
    if generated and min(p.stat().st_mtime for p in generated) >= latest_src:
        return 0

    script = orchestra_path / "scripts" / "orchestra-manager.py"
    if not script.is_file():
        return 0

    targets = collect_facet_build_targets(orchestra_path, installed_packages)

    total_built = 0
    for target in targets:
        try:
            result = subprocess.run(
                [
                    sys.executable,
                    str(script),
                    "facet",
                    "build",
                    "--target",
                    target,
                    "--project",
                    str(project_dir),
                ],
                capture_output=True,
                text=True,
                timeout=30,
            )
        except subprocess.TimeoutExpired:
            print(f"[orchestra] facet build ({target}) timed out", file=sys.stderr)
            continue
        except OSError as e:
            print(f"[orchestra] facet build ({target}) failed: {e}", file=sys.stderr)
            continue

        if result.returncode != 0:
            print(
                f"[orchestra] facet build ({target}) error: {result.stderr.strip()}",
                file=sys.stderr,
            )
            continue

        total_built += result.stdout.count("[facet] built")
        for line in result.stdout.splitlines():
            if "[facet] removed" in line or "[facet] cleanup" in line:
                print(line)

    return total_built
