"""orchestra-manager.py の context 管理機能テスト。"""

from __future__ import annotations

import json
from pathlib import Path


def _setup_context_packages(orchestra_dir: Path, extra_packages: dict | None = None) -> None:
    """context_files を含む minimal manifest を作成する。"""
    packages = {
        "core": {
            "name": "core",
            "version": "0.0.0",
            "depends": [],
            "context_files": {
                "source": "claude.md",
                "template": "templates/project/CLAUDE.md",
                "init": ["CLAUDE.md"],
                "sync": ["CLAUDE.md"],
            },
        },
        "codex-suggestions": {
            "name": "codex-suggestions",
            "version": "0.0.0",
            "depends": [],
            "context_files": {
                "source": "codex.md",
                "fragments": ["antigravity.md"],
                "template": "templates/codex/AGENTS.md",
                "init": ["AGENTS.md"],
                "sync": ["AGENTS.md"],
            },
        },
    }
    if extra_packages:
        packages.update(extra_packages)
    packages_dir = orchestra_dir / "packages"
    packages_dir.mkdir(parents=True, exist_ok=True)
    for pkg_name, manifest in packages.items():
        pkg_dir = packages_dir / pkg_name
        pkg_dir.mkdir(parents=True, exist_ok=True)
        (pkg_dir / "manifest.json").write_text(json.dumps(manifest), encoding="utf-8")


import pytest

from tests.module_loader import REPO_ROOT, load_module

manager_mod = load_module("orchestra_manager", "scripts/orchestra-manager.py")
OrchestraManager = manager_mod.OrchestraManager


def _setup_context_sources(orchestra_dir: Path, extra_packages: dict | None = None) -> None:
    context_dir = orchestra_dir / "templates" / "context"
    context_dir.mkdir(parents=True, exist_ok=True)

    (context_dir / "shared.md").write_text("## Shared\n\nshared guidance\n", encoding="utf-8")
    (context_dir / "claude.md").write_text("# CLAUDE\n\nclaude body\n", encoding="utf-8")
    (context_dir / "codex.md").write_text("# AGENTS\n\ncodex body\n", encoding="utf-8")
    (context_dir / "antigravity.md").write_text(
        "# ANTIGRAVITY\n\nantigravity body\n", encoding="utf-8"
    )

    _setup_context_packages(orchestra_dir, extra_packages)


def _setup_orchestra_json(
    project_dir: Path,
    installed_packages: list[str] | None = None,
) -> None:
    """Create .claude/orchestra.json with specified installed packages."""
    if installed_packages is None:
        installed_packages = ["codex-suggestions"]
    claude_dir = project_dir / ".claude"
    claude_dir.mkdir(parents=True, exist_ok=True)
    orch = {"installed_packages": installed_packages, "orchestra_dir": "", "last_sync": ""}
    (claude_dir / "orchestra.json").write_text(json.dumps(orch), encoding="utf-8")


class TestContextBuildAndCheck:
    def test_build_generates_all_template_docs(self, tmp_path: Path) -> None:
        _setup_context_sources(tmp_path)
        manager = OrchestraManager(tmp_path)

        changed = manager.context_build()

        assert changed == 2
        assert (tmp_path / "templates" / "project" / "CLAUDE.md").is_file()
        assert (tmp_path / "templates" / "codex" / "AGENTS.md").is_file()
        generated = (tmp_path / "templates" / "project" / "CLAUDE.md").read_text(encoding="utf-8")
        assert "generated by `orchex context build`" in generated
        assert "claude body" in generated
        assert "shared guidance" in generated

    def test_build_composes_agents_md_from_fragments(self, tmp_path: Path) -> None:
        """AGENTS.md は codex.md + antigravity.md のセクション合成で生成される。"""
        _setup_context_sources(tmp_path)
        manager = OrchestraManager(tmp_path)

        manager.context_build()

        agents = (tmp_path / "templates" / "codex" / "AGENTS.md").read_text(encoding="utf-8")
        assert "codex body" in agents
        assert "antigravity body" in agents
        assert agents.index("codex body") < agents.index("antigravity body")
        assert "templates/context/codex.md" in agents
        assert "templates/context/antigravity.md" in agents

    def test_check_returns_true_after_build(self, tmp_path: Path) -> None:
        _setup_context_sources(tmp_path)
        manager = OrchestraManager(tmp_path)
        manager.context_build()

        assert manager.context_check() is True

    def test_check_returns_false_when_template_outdated(self, tmp_path: Path) -> None:
        _setup_context_sources(tmp_path)
        manager = OrchestraManager(tmp_path)
        manager.context_build()

        target = tmp_path / "templates" / "project" / "CLAUDE.md"
        target.write_text("# stale\n", encoding="utf-8")

        assert manager.context_check() is False


class TestContextSync:
    def test_sync_creates_missing_files(self, tmp_path: Path) -> None:
        orchestra_dir = tmp_path / "orchestra"
        project_dir = tmp_path / "project"
        project_dir.mkdir(parents=True)

        _setup_context_sources(orchestra_dir)
        _setup_orchestra_json(project_dir)
        manager = OrchestraManager(orchestra_dir)

        changed = manager.context_sync(str(project_dir))

        assert changed == 2
        assert (project_dir / "CLAUDE.md").is_file()
        assert (project_dir / "AGENTS.md").is_file()
        agents = (project_dir / "AGENTS.md").read_text(encoding="utf-8")
        assert "codex body" in agents
        assert "antigravity body" in agents

    def test_sync_without_force_keeps_existing(self, tmp_path: Path) -> None:
        orchestra_dir = tmp_path / "orchestra"
        project_dir = tmp_path / "project"
        project_dir.mkdir(parents=True)

        _setup_context_sources(orchestra_dir)
        _setup_orchestra_json(project_dir)
        manager = OrchestraManager(orchestra_dir)

        claude_file = project_dir / "CLAUDE.md"
        claude_file.write_text("manual\n", encoding="utf-8")

        changed = manager.context_sync(str(project_dir), force=False)

        assert changed == 1
        assert claude_file.read_text(encoding="utf-8") == "manual\n"

    def test_sync_with_force_overwrites_existing(self, tmp_path: Path) -> None:
        orchestra_dir = tmp_path / "orchestra"
        project_dir = tmp_path / "project"
        project_dir.mkdir(parents=True)

        _setup_context_sources(orchestra_dir)
        _setup_orchestra_json(project_dir)
        manager = OrchestraManager(orchestra_dir)

        claude_file = project_dir / "CLAUDE.md"
        claude_file.write_text("manual\n", encoding="utf-8")

        changed = manager.context_sync(str(project_dir), force=True)

        assert changed == 2
        assert "generated by `orchex context build`" in claude_file.read_text(encoding="utf-8")

    def test_sync_skips_symlink_target_file(self, tmp_path: Path) -> None:
        orchestra_dir = tmp_path / "orchestra"
        project_dir = tmp_path / "project"
        project_dir.mkdir(parents=True)

        _setup_context_sources(orchestra_dir)
        _setup_orchestra_json(project_dir)
        manager = OrchestraManager(orchestra_dir)

        outside_file = tmp_path / "outside.md"
        outside_file.write_text("outside\n", encoding="utf-8")
        claude_file = project_dir / "CLAUDE.md"
        try:
            claude_file.symlink_to(outside_file)
        except OSError:
            pytest.skip("symlink unsupported in this environment")

        changed = manager.context_sync(str(project_dir), force=True)

        assert changed == 1
        assert outside_file.read_text(encoding="utf-8") == "outside\n"

    def test_sync_skips_symlinked_parent_outside_project(self, tmp_path: Path) -> None:
        orchestra_dir = tmp_path / "orchestra"
        project_dir = tmp_path / "project"
        project_dir.mkdir(parents=True)

        nested_pkg = {
            "nested-docs": {
                "name": "nested-docs",
                "version": "0.0.0",
                "depends": [],
                "context_files": {
                    "source": "claude.md",
                    "template": "templates/nested/NOTES.md",
                    "init": [".sub/NOTES.md"],
                    "sync": [".sub/NOTES.md"],
                },
            }
        }
        _setup_context_sources(orchestra_dir, extra_packages=nested_pkg)
        _setup_orchestra_json(project_dir, installed_packages=["codex-suggestions", "nested-docs"])
        manager = OrchestraManager(orchestra_dir)

        external_dir = tmp_path / "external"
        external_dir.mkdir(parents=True)
        sub_dir = project_dir / ".sub"
        try:
            sub_dir.symlink_to(external_dir, target_is_directory=True)
        except OSError:
            pytest.skip("symlink unsupported in this environment")

        changed = manager.context_sync(str(project_dir), force=True)

        assert changed == 2
        assert not (external_dir / "NOTES.md").exists()

    def test_sync_skips_codex_when_package_not_installed(self, tmp_path: Path) -> None:
        """codex-suggestions がインストールされていない場合、AGENTS.md を配布しない"""
        orchestra_dir = tmp_path / "orchestra"
        project_dir = tmp_path / "project"
        project_dir.mkdir(parents=True)

        _setup_context_sources(orchestra_dir)
        _setup_orchestra_json(project_dir, installed_packages=["antigravity-suggestions"])
        manager = OrchestraManager(orchestra_dir)

        changed = manager.context_sync(str(project_dir))

        assert changed == 1
        assert (project_dir / "CLAUDE.md").is_file()
        assert not (project_dir / "AGENTS.md").exists()

    def test_sync_only_claude_when_no_packages_installed(self, tmp_path: Path) -> None:
        """suggestions パッケージが未インストールの場合、CLAUDE.md のみ配布"""
        orchestra_dir = tmp_path / "orchestra"
        project_dir = tmp_path / "project"
        project_dir.mkdir(parents=True)

        _setup_context_sources(orchestra_dir)
        _setup_orchestra_json(project_dir, installed_packages=[])
        manager = OrchestraManager(orchestra_dir)

        changed = manager.context_sync(str(project_dir))

        assert changed == 1
        assert (project_dir / "CLAUDE.md").is_file()
        assert not (project_dir / "AGENTS.md").exists()


class TestLegacyContextCleanup:
    """配布廃止済み context ファイル（.gemini/GEMINI.md）の安全クリーンアップ。"""

    GENERATED_GEMINI = (
        "<!-- DO NOT EDIT: generated by `orchex context build` -->\n\n# GEMINI\n\nold body\n"
    )

    def _make_project(self, tmp_path: Path) -> tuple[OrchestraManager, Path]:
        orchestra_dir = tmp_path / "orchestra"
        project_dir = tmp_path / "project"
        project_dir.mkdir(parents=True)
        _setup_context_sources(orchestra_dir)
        _setup_orchestra_json(project_dir)
        return OrchestraManager(orchestra_dir), project_dir

    def test_generated_gemini_md_is_removed(self, tmp_path: Path) -> None:
        manager, project_dir = self._make_project(tmp_path)
        legacy = project_dir / ".gemini" / "GEMINI.md"
        legacy.parent.mkdir(parents=True)
        legacy.write_text(self.GENERATED_GEMINI, encoding="utf-8")

        manager.context_sync(str(project_dir))

        assert not legacy.exists()

    def test_handwritten_gemini_md_is_kept(self, tmp_path: Path) -> None:
        """生成物マーカーのないファイル（ユーザー手書き）は削除しない。"""
        manager, project_dir = self._make_project(tmp_path)
        legacy = project_dir / ".gemini" / "GEMINI.md"
        legacy.parent.mkdir(parents=True)
        legacy.write_text("# My custom Gemini instructions\n", encoding="utf-8")

        manager.context_sync(str(project_dir))

        assert legacy.exists()
        assert "My custom" in legacy.read_text(encoding="utf-8")

    def test_dry_run_does_not_remove(self, tmp_path: Path) -> None:
        manager, project_dir = self._make_project(tmp_path)
        legacy = project_dir / ".gemini" / "GEMINI.md"
        legacy.parent.mkdir(parents=True)
        legacy.write_text(self.GENERATED_GEMINI, encoding="utf-8")

        manager.context_sync(str(project_dir), dry_run=True)

        assert legacy.exists()

    def test_no_gemini_md_is_noop(self, tmp_path: Path) -> None:
        manager, project_dir = self._make_project(tmp_path)

        changed = manager.context_sync(str(project_dir))

        assert changed == 2


class TestInstallContextInitFiles:
    def test_root_file_is_copied(self, tmp_path: Path) -> None:
        orchestra_dir = tmp_path / "orchestra"
        project_dir = tmp_path / "project"
        project_dir.mkdir(parents=True)

        tmpl = orchestra_dir / "templates" / "project" / "CLAUDE.md"
        tmpl.parent.mkdir(parents=True, exist_ok=True)
        tmpl.write_text("claude content", encoding="utf-8")

        pkg_dir = orchestra_dir / "packages" / "core"
        pkg_dir.mkdir(parents=True, exist_ok=True)
        manifest = {
            "name": "core",
            "version": "0.0.0",
            "depends": [],
            "context_files": {
                "source": "claude.md",
                "template": "templates/project/CLAUDE.md",
                "init": ["CLAUDE.md"],
                "sync": ["CLAUDE.md"],
            },
        }
        (pkg_dir / "manifest.json").write_text(json.dumps(manifest), encoding="utf-8")

        manager = OrchestraManager(orchestra_dir)
        pkg = manager.load_packages()["core"]
        manager._install_context_init_files(pkg, project_dir, dry_run=False)

        dest = project_dir / "CLAUDE.md"
        assert dest.is_file()
        assert dest.read_text(encoding="utf-8") == "claude content"

    def test_prefixed_file_is_copied(self, tmp_path: Path) -> None:
        orchestra_dir = tmp_path / "orchestra"
        project_dir = tmp_path / "project"
        project_dir.mkdir(parents=True)

        tmpl_dir = orchestra_dir / "templates" / "codex"
        tmpl_dir.mkdir(parents=True, exist_ok=True)
        (tmpl_dir / "AGENTS.md").write_text("agents content", encoding="utf-8")
        (tmpl_dir / "config.toml").write_text("toml content", encoding="utf-8")

        pkg_dir = orchestra_dir / "packages" / "codex-suggestions"
        pkg_dir.mkdir(parents=True, exist_ok=True)
        manifest = {
            "name": "codex-suggestions",
            "version": "0.0.0",
            "depends": [],
            "context_files": {
                "source": "codex.md",
                "template": "templates/codex/AGENTS.md",
                "init": ["AGENTS.md", ".codex/config.toml"],
                "sync": ["AGENTS.md"],
            },
        }
        (pkg_dir / "manifest.json").write_text(json.dumps(manifest), encoding="utf-8")

        manager = OrchestraManager(orchestra_dir)
        pkg = manager.load_packages()["codex-suggestions"]
        manager._install_context_init_files(pkg, project_dir, dry_run=False)

        assert (project_dir / "AGENTS.md").is_file()
        toml_dest = project_dir / ".codex" / "config.toml"
        assert toml_dest.is_file()
        assert toml_dest.read_text(encoding="utf-8") == "toml content"

    def test_directory_entry_is_copied_recursively(self, tmp_path: Path) -> None:
        orchestra_dir = tmp_path / "orchestra"
        project_dir = tmp_path / "project"
        project_dir.mkdir(parents=True)

        tmpl_dir = orchestra_dir / "templates" / "codex"
        tmpl_dir.mkdir(parents=True, exist_ok=True)
        (tmpl_dir / "AGENTS.md").write_text("placeholder", encoding="utf-8")

        skill_dir = tmpl_dir / "skills" / "context-loader"
        skill_dir.mkdir(parents=True, exist_ok=True)
        (skill_dir / "SKILL.md").write_text("skill content", encoding="utf-8")

        pkg_dir = orchestra_dir / "packages" / "codex-suggestions"
        pkg_dir.mkdir(parents=True, exist_ok=True)
        manifest = {
            "name": "codex-suggestions",
            "version": "0.0.0",
            "depends": [],
            "context_files": {
                "source": "codex.md",
                "template": "templates/codex/AGENTS.md",
                "init": [".codex/skills/context-loader/"],
                "sync": ["AGENTS.md"],
            },
        }
        (pkg_dir / "manifest.json").write_text(json.dumps(manifest), encoding="utf-8")

        manager = OrchestraManager(orchestra_dir)
        pkg = manager.load_packages()["codex-suggestions"]
        manager._install_context_init_files(pkg, project_dir, dry_run=False)

        dest = project_dir / ".codex" / "skills" / "context-loader" / "SKILL.md"
        assert dest.is_file()
        assert dest.read_text(encoding="utf-8") == "skill content"

    def test_missing_template_root_prints_warning_and_no_crash(
        self, tmp_path: Path, capsys: pytest.CaptureFixture[str]
    ) -> None:
        orchestra_dir = tmp_path / "orchestra"
        project_dir = tmp_path / "project"
        project_dir.mkdir(parents=True)

        pkg_dir = orchestra_dir / "packages" / "core"
        pkg_dir.mkdir(parents=True, exist_ok=True)
        manifest = {
            "name": "core",
            "version": "0.0.0",
            "depends": [],
            "context_files": {
                "source": "claude.md",
                "template": "templates/nonexistent/FILE.md",
                "init": ["FILE.md"],
                "sync": [],
            },
        }
        (pkg_dir / "manifest.json").write_text(json.dumps(manifest), encoding="utf-8")

        manager = OrchestraManager(orchestra_dir)
        pkg = manager.load_packages()["core"]
        manager._install_context_init_files(pkg, project_dir, dry_run=False)

        captured = capsys.readouterr()
        assert "テンプレートディレクトリ" in captured.err

    def test_existing_file_is_not_overwritten(self, tmp_path: Path) -> None:
        orchestra_dir = tmp_path / "orchestra"
        project_dir = tmp_path / "project"
        project_dir.mkdir(parents=True)

        tmpl = orchestra_dir / "templates" / "project" / "CLAUDE.md"
        tmpl.parent.mkdir(parents=True, exist_ok=True)
        tmpl.write_text("new content", encoding="utf-8")

        existing = project_dir / "CLAUDE.md"
        existing.write_text("existing content", encoding="utf-8")

        pkg_dir = orchestra_dir / "packages" / "core"
        pkg_dir.mkdir(parents=True, exist_ok=True)
        manifest = {
            "name": "core",
            "version": "0.0.0",
            "depends": [],
            "context_files": {
                "source": "claude.md",
                "template": "templates/project/CLAUDE.md",
                "init": ["CLAUDE.md"],
                "sync": ["CLAUDE.md"],
            },
        }
        (pkg_dir / "manifest.json").write_text(json.dumps(manifest), encoding="utf-8")

        manager = OrchestraManager(orchestra_dir)
        pkg = manager.load_packages()["core"]
        manager._install_context_init_files(pkg, project_dir, dry_run=False)

        assert existing.read_text(encoding="utf-8") == "existing content"

    def test_empty_init_list_is_noop(self, tmp_path: Path) -> None:
        orchestra_dir = tmp_path / "orchestra"
        project_dir = tmp_path / "project"
        project_dir.mkdir(parents=True)

        tmpl = orchestra_dir / "templates" / "project" / "CLAUDE.md"
        tmpl.parent.mkdir(parents=True, exist_ok=True)
        tmpl.write_text("content", encoding="utf-8")

        pkg_dir = orchestra_dir / "packages" / "core"
        pkg_dir.mkdir(parents=True, exist_ok=True)
        manifest = {
            "name": "core",
            "version": "0.0.0",
            "depends": [],
            "context_files": {
                "source": "claude.md",
                "template": "templates/project/CLAUDE.md",
                "init": [],
                "sync": ["CLAUDE.md"],
            },
        }
        (pkg_dir / "manifest.json").write_text(json.dumps(manifest), encoding="utf-8")

        manager = OrchestraManager(orchestra_dir)
        pkg = manager.load_packages()["core"]
        manager._install_context_init_files(pkg, project_dir, dry_run=False)

        assert list(project_dir.iterdir()) == []


class TestSeverityDefinitionsExpansion:
    MARKER = "<!-- severity-definitions: output-contracts/tiered-review -->"
    SEVERITY_ROWS = (
        ("Critical", "critical criteria", "critical response"),
        ("High", "high criteria", "high response"),
        ("Medium", "medium criteria", "medium response"),
        ("Low", "low criteria", "low response"),
    )
    EXPECTED_LINES = (
        "  - Critical: critical criteria",
        "  - High: high criteria",
        "  - Medium: medium criteria",
        "  - Low: low criteria",
    )

    def _setup_marker_source(self, orchestra_dir: Path, marker: str | None = None) -> None:
        """重要度定義マーカーを含む context ソースを作成する。"""
        _setup_context_sources(orchestra_dir)
        marker_line = marker or self.MARKER
        (orchestra_dir / "templates" / "context" / "codex.md").write_text(
            f"# AGENTS\n\n{marker_line}\n",
            encoding="utf-8",
        )

    def _write_facet(self, orchestra_dir: Path, padded: bool = False) -> Path:
        """前後に別セクションを持つ重要度定義 facet を作成する。"""
        facet_path = orchestra_dir / "facets" / "output-contracts" / "tiered-review.md"
        facet_path.parent.mkdir(parents=True, exist_ok=True)
        if padded:
            table_lines = [
                "| 重要度         | 基準              | 対応              |",
                "| -------------- | ----------------- | ----------------- |",
                *(
                    f"| **{severity}**{' ' * (10 - len(severity))} | "
                    f"{criteria:<17} | {response:<17} |"
                    for severity, criteria, response in self.SEVERITY_ROWS
                ),
            ]
        else:
            table_lines = [
                "| 重要度 | 基準 | 対応 |",
                "|---|---|---|",
                *(
                    f"| **{severity}** | {criteria} | {response} |"
                    for severity, criteria, response in self.SEVERITY_ROWS
                ),
            ]
        facet_path.write_text(
            "\n".join(
                [
                    "# Contract",
                    "",
                    "## Before",
                    "",
                    "before body",
                    "",
                    "## 重要度の定義",
                    "",
                    *table_lines,
                    "",
                    "## After",
                    "",
                    "after body",
                    "",
                ]
            ),
            encoding="utf-8",
        )
        return facet_path

    @staticmethod
    def _built_agents_path(orchestra_dir: Path) -> Path:
        """生成された Codex 向け AGENTS.md のパスを返す。"""
        return orchestra_dir / "templates" / "codex" / "AGENTS.md"

    @staticmethod
    def _repo_severity_lines() -> list[str]:
        """実リポジトリの重要度表を実装から独立した単純な方法で読む。"""
        facet_path = REPO_ROOT / "facets" / "output-contracts" / "tiered-review.md"
        content = facet_path.read_text(encoding="utf-8")
        section = content.split("## 重要度の定義\n", maxsplit=1)[1]
        section = section.split("\n## ", maxsplit=1)[0]
        table_rows = [line for line in section.splitlines() if line.startswith("|")]
        severity_lines: list[str] = []
        for row in table_rows[2:]:
            cells = [cell.strip() for cell in row.strip("|").split("|")]
            severity_lines.append(f"  - {cells[0].strip('*')}: {cells[1]}")
        assert len(severity_lines) == 4
        return severity_lines

    def test_build_expands_severity_definitions_marker(self, tmp_path: Path) -> None:
        self._setup_marker_source(tmp_path)
        self._write_facet(tmp_path)

        OrchestraManager(tmp_path).context_build()

        generated = self._built_agents_path(tmp_path).read_text(encoding="utf-8")
        for expected_line in self.EXPECTED_LINES:
            assert expected_line in generated
        assert "critical response" not in generated
        assert self.MARKER not in generated
        assert (
            "<!-- Sources: templates/context/codex.md, "
            "templates/context/antigravity.md, "
            "facets/output-contracts/tiered-review.md, "
            "templates/context/shared.md -->"
        ) in generated

    def test_sync_expands_severity_definitions_marker(self, tmp_path: Path) -> None:
        orchestra_dir = tmp_path / "orchestra"
        project_dir = tmp_path / "project"
        project_dir.mkdir(parents=True)
        self._setup_marker_source(orchestra_dir)
        self._write_facet(orchestra_dir)
        _setup_orchestra_json(project_dir)

        OrchestraManager(orchestra_dir).context_sync(str(project_dir))

        agents = (project_dir / "AGENTS.md").read_text(encoding="utf-8")
        for expected_line in self.EXPECTED_LINES:
            assert expected_line in agents
        assert self.MARKER not in agents

    def test_facet_change_is_detected_and_rebuilt(self, tmp_path: Path) -> None:
        self._setup_marker_source(tmp_path)
        facet_path = self._write_facet(tmp_path)
        manager = OrchestraManager(tmp_path)
        manager.context_build()

        facet_content = facet_path.read_text(encoding="utf-8")
        facet_path.write_text(
            facet_content.replace("critical criteria", "updated critical criteria"),
            encoding="utf-8",
        )

        assert manager.context_check() is False
        manager.context_build()
        generated = self._built_agents_path(tmp_path).read_text(encoding="utf-8")
        assert "  - Critical: updated critical criteria" in generated

    def test_missing_facet_exits(self, tmp_path: Path) -> None:
        self._setup_marker_source(tmp_path)

        with pytest.raises(SystemExit):
            OrchestraManager(tmp_path).context_build()

    def test_unreadable_facet_exits(self, tmp_path: Path) -> None:
        self._setup_marker_source(tmp_path)
        facet_path = tmp_path / "facets" / "output-contracts" / "tiered-review.md"
        facet_path.mkdir(parents=True)

        with pytest.raises(SystemExit):
            OrchestraManager(tmp_path).context_build()

    def test_missing_severity_section_exits(self, tmp_path: Path) -> None:
        self._setup_marker_source(tmp_path)
        facet_path = tmp_path / "facets" / "output-contracts" / "tiered-review.md"
        facet_path.parent.mkdir(parents=True)
        facet_path.write_text("# Contract\n\n## Different section\n", encoding="utf-8")

        with pytest.raises(SystemExit):
            OrchestraManager(tmp_path).context_build()

    def test_empty_severity_table_exits(self, tmp_path: Path) -> None:
        self._setup_marker_source(tmp_path)
        facet_path = tmp_path / "facets" / "output-contracts" / "tiered-review.md"
        facet_path.parent.mkdir(parents=True)
        facet_path.write_text(
            "## 重要度の定義\n\n| 重要度 | 基準 | 対応 |\n|---|---|---|\n",
            encoding="utf-8",
        )

        with pytest.raises(SystemExit):
            OrchestraManager(tmp_path).context_build()

    def test_malformed_marker_exits(self, tmp_path: Path) -> None:
        malformed = "<!-- severity-definitions: output-contracts/../x -->"
        self._setup_marker_source(tmp_path, marker=malformed)

        with pytest.raises(SystemExit):
            OrchestraManager(tmp_path).context_build()

    def test_table_body_row_with_too_few_columns_exits(self, tmp_path: Path) -> None:
        self._setup_marker_source(tmp_path)
        facet_path = tmp_path / "facets" / "output-contracts" / "tiered-review.md"
        facet_path.parent.mkdir(parents=True)
        facet_path.write_text(
            "## 重要度の定義\n\n| 重要度 | 基準 |\n|---|---|\n| **Critical** |\n",
            encoding="utf-8",
        )

        with pytest.raises(SystemExit):
            OrchestraManager(tmp_path).context_build()

    def test_prettier_aligned_table_matches_plain_table(self, tmp_path: Path) -> None:
        self._setup_marker_source(tmp_path)
        self._write_facet(tmp_path)
        manager = OrchestraManager(tmp_path)
        manager.context_build()
        plain_output = self._built_agents_path(tmp_path).read_text(encoding="utf-8")

        self._write_facet(tmp_path, padded=True)
        manager.context_build()
        padded_output = self._built_agents_path(tmp_path).read_text(encoding="utf-8")

        assert padded_output == plain_output
        for expected_line in self.EXPECTED_LINES:
            assert expected_line in padded_output

    def test_generated_codex_template_matches_repo_severity_table(self) -> None:
        expected_lines = self._repo_severity_lines()
        generated = (REPO_ROOT / "templates" / "codex" / "AGENTS.md").read_text(encoding="utf-8")

        for expected_line in expected_lines:
            assert expected_line in generated

    def test_root_agents_matches_repo_severity_table(self) -> None:
        """手動管理のルート AGENTS.md も facet の重要度定義と同期させる。"""
        expected_lines = self._repo_severity_lines()
        root_agents = (REPO_ROOT / "AGENTS.md").read_text(encoding="utf-8")

        for expected_line in expected_lines:
            assert expected_line in root_agents

    def test_codex_context_uses_marker_instead_of_handwritten_rows(self) -> None:
        context_source = (REPO_ROOT / "templates" / "context" / "codex.md").read_text(
            encoding="utf-8"
        )

        assert self.MARKER in context_source
        assert "  - Critical:" not in context_source
