"""orchestra-manager.py の context 管理機能テスト。"""

from __future__ import annotations

from pathlib import Path

import pytest

from tests.module_loader import load_module

manager_mod = load_module("orchestra_manager", "scripts/orchestra-manager.py")
OrchestraManager = manager_mod.OrchestraManager


def _setup_context_sources(orchestra_dir: Path) -> None:
    context_dir = orchestra_dir / "templates" / "context"
    context_dir.mkdir(parents=True, exist_ok=True)

    (context_dir / "shared.md").write_text("## Shared\n\nshared guidance\n", encoding="utf-8")
    (context_dir / "claude.md").write_text("# CLAUDE\n\nclaude body\n", encoding="utf-8")
    (context_dir / "codex.md").write_text("# AGENTS\n\ncodex body\n", encoding="utf-8")
    (context_dir / "gemini.md").write_text("# GEMINI\n\ngemini body\n", encoding="utf-8")


class TestContextBuildAndCheck:
    def test_build_generates_all_template_docs(self, tmp_path: Path) -> None:
        _setup_context_sources(tmp_path)
        manager = OrchestraManager(tmp_path)

        changed = manager.context_build()

        assert changed == 3
        assert (tmp_path / "templates" / "project" / "CLAUDE.md").is_file()
        assert (tmp_path / "templates" / "codex" / "AGENTS.md").is_file()
        assert (tmp_path / "templates" / "gemini" / "GEMINI.md").is_file()
        generated = (tmp_path / "templates" / "project" / "CLAUDE.md").read_text(encoding="utf-8")
        assert "generated by `orchex context build`" in generated
        assert "claude body" in generated
        assert "shared guidance" in generated

    def test_check_returns_true_after_build(self, tmp_path: Path) -> None:
        _setup_context_sources(tmp_path)
        manager = OrchestraManager(tmp_path)
        manager.context_build()

        assert manager.context_check() is True

    def test_check_returns_false_when_template_outdated(self, tmp_path: Path) -> None:
        _setup_context_sources(tmp_path)
        manager = OrchestraManager(tmp_path)
        manager.context_build()

        target = tmp_path / "templates" / "project" / "CLAUDE.md"
        target.write_text("# stale\n", encoding="utf-8")

        assert manager.context_check() is False


class TestContextSync:
    def test_sync_creates_missing_files(self, tmp_path: Path) -> None:
        orchestra_dir = tmp_path / "orchestra"
        project_dir = tmp_path / "project"
        project_dir.mkdir(parents=True)

        _setup_context_sources(orchestra_dir)
        manager = OrchestraManager(orchestra_dir)

        changed = manager.context_sync(str(project_dir))

        assert changed == 3
        assert (project_dir / "CLAUDE.md").is_file()
        assert (project_dir / "AGENTS.md").is_file()
        assert (project_dir / ".gemini" / "GEMINI.md").is_file()

    def test_sync_without_force_keeps_existing(self, tmp_path: Path) -> None:
        orchestra_dir = tmp_path / "orchestra"
        project_dir = tmp_path / "project"
        project_dir.mkdir(parents=True)

        _setup_context_sources(orchestra_dir)
        manager = OrchestraManager(orchestra_dir)

        claude_file = project_dir / "CLAUDE.md"
        claude_file.write_text("manual\n", encoding="utf-8")

        changed = manager.context_sync(str(project_dir), force=False)

        assert changed == 2
        assert claude_file.read_text(encoding="utf-8") == "manual\n"

    def test_sync_with_force_overwrites_existing(self, tmp_path: Path) -> None:
        orchestra_dir = tmp_path / "orchestra"
        project_dir = tmp_path / "project"
        project_dir.mkdir(parents=True)

        _setup_context_sources(orchestra_dir)
        manager = OrchestraManager(orchestra_dir)

        claude_file = project_dir / "CLAUDE.md"
        claude_file.write_text("manual\n", encoding="utf-8")

        changed = manager.context_sync(str(project_dir), force=True)

        assert changed == 3
        assert "generated by `orchex context build`" in claude_file.read_text(encoding="utf-8")

    def test_sync_skips_symlink_target_file(self, tmp_path: Path) -> None:
        orchestra_dir = tmp_path / "orchestra"
        project_dir = tmp_path / "project"
        project_dir.mkdir(parents=True)

        _setup_context_sources(orchestra_dir)
        manager = OrchestraManager(orchestra_dir)

        outside_file = tmp_path / "outside.md"
        outside_file.write_text("outside\n", encoding="utf-8")
        claude_file = project_dir / "CLAUDE.md"
        try:
            claude_file.symlink_to(outside_file)
        except OSError:
            pytest.skip("symlink unsupported in this environment")

        changed = manager.context_sync(str(project_dir), force=True)

        assert changed == 2
        assert outside_file.read_text(encoding="utf-8") == "outside\n"

    def test_sync_skips_symlinked_parent_outside_project(self, tmp_path: Path) -> None:
        orchestra_dir = tmp_path / "orchestra"
        project_dir = tmp_path / "project"
        project_dir.mkdir(parents=True)

        _setup_context_sources(orchestra_dir)
        manager = OrchestraManager(orchestra_dir)

        external_dir = tmp_path / "external"
        external_dir.mkdir(parents=True)
        gemini_dir = project_dir / ".gemini"
        try:
            gemini_dir.symlink_to(external_dir, target_is_directory=True)
        except OSError:
            pytest.skip("symlink unsupported in this environment")

        changed = manager.context_sync(str(project_dir), force=True)

        assert changed == 2
        assert not (external_dir / "GEMINI.md").exists()
